C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(-2,-4,-3)*Gamma(-2,2,-6)*Gamma(-1,-6,-5)*Gamma(-1,4,-4)*Pro
C     jP(-5,1)*ProjP(-3,3) + Gamma(-2,-4,-3)*Gamma(-2,4,-6)*Gamma(-1,-6
C     ,-5)*Gamma(-1,2,-4)*ProjP(-5,3)*ProjP(-3,1) +
C      Gamma(-2,-4,-3)*Gamma(-2,2,-6)*Gamma(-1,-6,-5)*Gamma(-1,4,-4)*Pr
C     ojM(-5,1)*ProjM(-3,3)
C     
      SUBROUTINE FFFF29_0(F1, F2, F3, F4, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 F3(*)
      COMPLEX*16 TMP64
      COMPLEX*16 VERTEX
      COMPLEX*16 TMP62
      COMPLEX*16 COUP
      COMPLEX*16 TMP63
      COMPLEX*16 F4(*)
      TMP62 = (F1(3)*F4(3)*(F2(3)*F3(3)+F2(4)*F3(4))+F1(4)*F4(4)*(F2(3)
     $ *F3(3)+F2(4)*F3(4)))
      TMP63 = (F1(5)*F4(5)*(F2(5)*F3(5)+F2(6)*F3(6))+F1(6)*F4(6)*(F2(5)
     $ *F3(5)+F2(6)*F3(6)))
      TMP64 = (F1(5)*F4(5)*(F2(5)*F3(5)+F2(6)*F3(6))+F1(6)*F4(6)*(F2(5)
     $ *F3(5)+F2(6)*F3(6)))
      VERTEX = COUP*(-8D0)*(+CI*(TMP63+TMP64+TMP62))
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(-2,-4,-3)*Gamma(-2,2,-6)*Gamma(-1,-6,-5)*Gamma(-1,4,-4)*Pro
C     jP(-5,1)*ProjP(-3,3) + Gamma(-2,-4,-3)*Gamma(-2,4,-6)*Gamma(-1,-6
C     ,-5)*Gamma(-1,2,-4)*ProjP(-5,3)*ProjP(-3,1) +
C      Gamma(-2,-4,-3)*Gamma(-2,2,-6)*Gamma(-1,-6,-5)*Gamma(-1,4,-4)*Pr
C     ojM(-5,1)*ProjM(-3,3)
C     
      SUBROUTINE FFFF29_26_0(F1, F2, F3, F4, COUP1, COUP2,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP2
      COMPLEX*16 F1(*)
      COMPLEX*16 COUP1
      COMPLEX*16 F2(*)
      COMPLEX*16 F3(*)
      COMPLEX*16 TMP
      COMPLEX*16 VERTEX
      COMPLEX*16 F4(*)
      CALL FFFF29_0(F1,F2,F3,F4,COUP1,VERTEX)
      CALL FFFF26_0(F1,F2,F3,F4,COUP2,TMP)
      VERTEX = VERTEX + TMP
      END


