C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(-2,-6,-5)*Gamma(-2,-4,-3)*Gamma(-1,2,-4)*Gamma(-1,4,-6)*Pro
C     jP(-5,3)*ProjP(-3,1) + Gamma(-2,-6,-5)*Gamma(-2,-4,-3)*Gamma(-1,2
C     ,-4)*Gamma(-1,4,-6)*ProjM(-5,3)*ProjM(-3,1)
C     
      SUBROUTINE FFFF26_0(F1, F2, F3, F4, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 F3(*)
      COMPLEX*16 VERTEX
      COMPLEX*16 TMP68
      COMPLEX*16 TMP69
      COMPLEX*16 F4(*)
      TMP68 = (F1(5)*F3(6)*(F2(5)*F4(6)-F2(6)*F4(5))+F1(6)*F3(5)*(F2(6)
     $ *F4(5)-F2(5)*F4(6)))
      TMP69 = (F1(3)*F3(4)*(F2(3)*F4(4)-F2(4)*F4(3))+F1(4)*F3(3)*(F2(4)
     $ *F4(3)-F2(3)*F4(4)))
      VERTEX = COUP*(-8D0)*(+CI*(TMP68+TMP69))
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(-2,-6,-5)*Gamma(-2,-4,-3)*Gamma(-1,2,-4)*Gamma(-1,4,-6)*Pro
C     jP(-5,3)*ProjP(-3,1) + Gamma(-2,-6,-5)*Gamma(-2,-4,-3)*Gamma(-1,2
C     ,-4)*Gamma(-1,4,-6)*ProjM(-5,3)*ProjM(-3,1)
C     
      SUBROUTINE FFFF26_27_0(F1, F2, F3, F4, COUP1, COUP2,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP2
      COMPLEX*16 F1(*)
      COMPLEX*16 COUP1
      COMPLEX*16 F2(*)
      COMPLEX*16 TMP
      COMPLEX*16 F3(*)
      COMPLEX*16 VERTEX
      COMPLEX*16 F4(*)
      CALL FFFF26_0(F1,F2,F3,F4,COUP1,VERTEX)
      CALL FFFF27_0(F1,F2,F3,F4,COUP2,TMP)
      VERTEX = VERTEX + TMP
      END


