C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(-2,-6,-5)*Gamma(-2,-4,-3)*Gamma(-1,2,-4)*Gamma(-1,4,-6)*Pro
C     jP(-5,3)*ProjP(-3,1)
C     
      SUBROUTINE FFFF21_0(F1, F2, F3, F4, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 F3(*)
      COMPLEX*16 VERTEX
      COMPLEX*16 TMP68
      COMPLEX*16 COUP
      COMPLEX*16 F4(*)
      TMP68 = (F1(5)*F3(6)*(F2(5)*F4(6)-F2(6)*F4(5))+F1(6)*F3(5)*(F2(6)
     $ *F4(5)-F2(5)*F4(6)))
      VERTEX = COUP*(-8D0 * CI * TMP68)
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(-2,-6,-5)*Gamma(-2,-4,-3)*Gamma(-1,2,-4)*Gamma(-1,4,-6)*Pro
C     jP(-5,3)*ProjP(-3,1)
C     
      SUBROUTINE FFFF21_8_25_28_0(F1, F2, F3, F4, COUP1, COUP2, COUP3,
     $  COUP4,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP2
      COMPLEX*16 F1(*)
      COMPLEX*16 COUP1
      COMPLEX*16 F2(*)
      COMPLEX*16 TMP
      COMPLEX*16 F3(*)
      COMPLEX*16 VERTEX
      COMPLEX*16 COUP4
      COMPLEX*16 COUP3
      COMPLEX*16 F4(*)
      CALL FFFF21_0(F1,F2,F3,F4,COUP1,VERTEX)
      CALL FFFF8_0(F1,F2,F3,F4,COUP2,TMP)
      VERTEX = VERTEX + TMP
      CALL FFFF25_0(F1,F2,F3,F4,COUP3,TMP)
      VERTEX = VERTEX + TMP
      CALL FFFF28_0(F1,F2,F3,F4,COUP4,TMP)
      VERTEX = VERTEX + TMP
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(-2,-6,-5)*Gamma(-2,-4,-3)*Gamma(-1,2,-4)*Gamma(-1,4,-6)*Pro
C     jP(-5,3)*ProjP(-3,1)
C     
      SUBROUTINE FFFF21_8_23_25_0(F1, F2, F3, F4, COUP1, COUP2, COUP3,
     $  COUP4,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP2
      COMPLEX*16 F1(*)
      COMPLEX*16 COUP1
      COMPLEX*16 F2(*)
      COMPLEX*16 TMP
      COMPLEX*16 F3(*)
      COMPLEX*16 VERTEX
      COMPLEX*16 COUP4
      COMPLEX*16 COUP3
      COMPLEX*16 F4(*)
      CALL FFFF21_0(F1,F2,F3,F4,COUP1,VERTEX)
      CALL FFFF8_0(F1,F2,F3,F4,COUP2,TMP)
      VERTEX = VERTEX + TMP
      CALL FFFF23_0(F1,F2,F3,F4,COUP3,TMP)
      VERTEX = VERTEX + TMP
      CALL FFFF25_0(F1,F2,F3,F4,COUP4,TMP)
      VERTEX = VERTEX + TMP
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(-2,-6,-5)*Gamma(-2,-4,-3)*Gamma(-1,2,-4)*Gamma(-1,4,-6)*Pro
C     jP(-5,3)*ProjP(-3,1)
C     
      SUBROUTINE FFFF21_8_25_23_0(F1, F2, F3, F4, COUP1, COUP2, COUP3,
     $  COUP4,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP2
      COMPLEX*16 F1(*)
      COMPLEX*16 COUP1
      COMPLEX*16 F2(*)
      COMPLEX*16 TMP
      COMPLEX*16 F3(*)
      COMPLEX*16 VERTEX
      COMPLEX*16 COUP4
      COMPLEX*16 COUP3
      COMPLEX*16 F4(*)
      CALL FFFF21_0(F1,F2,F3,F4,COUP1,VERTEX)
      CALL FFFF8_0(F1,F2,F3,F4,COUP2,TMP)
      VERTEX = VERTEX + TMP
      CALL FFFF25_0(F1,F2,F3,F4,COUP3,TMP)
      VERTEX = VERTEX + TMP
      CALL FFFF23_0(F1,F2,F3,F4,COUP4,TMP)
      VERTEX = VERTEX + TMP
      END


