C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     ProjM(2,1)*ProjP(4,3) + ProjM(4,3)*ProjP(2,1)
C     
      SUBROUTINE FFFF22_0(F1, F2, F3, F4, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 TMP37
      COMPLEX*16 TMP36
      COMPLEX*16 TMP56
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 TMP40
      COMPLEX*16 F3(*)
      COMPLEX*16 VERTEX
      COMPLEX*16 COUP
      COMPLEX*16 F4(*)
      TMP40 = (F1(5)*F2(5)+F1(6)*F2(6))
      TMP37 = (F1(3)*F2(3)+F1(4)*F2(4))
      TMP36 = (F4(5)*F3(5)+F4(6)*F3(6))
      TMP56 = (F4(3)*F3(3)+F4(4)*F3(4))
      VERTEX = COUP*(-1D0)*(+CI*(TMP36*TMP37+TMP40*TMP56))
      END


