C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(-2,-4,-3)*Gamma(-2,2,-6)*Gamma(-1,-6,-5)*Gamma(-1,4,-4)*Pro
C     jM(-5,1)*ProjM(-3,3) + Gamma(-2,-4,-3)*Gamma(-2,4,-6)*Gamma(-1,-6
C     ,-5)*Gamma(-1,2,-4)*ProjM(-5,3)*ProjM(-3,1)
C     
      SUBROUTINE FFFF23_0(F1, F2, F3, F4, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 TMP59
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 F3(*)
      COMPLEX*16 VERTEX
      COMPLEX*16 TMP62
      COMPLEX*16 COUP
      COMPLEX*16 F4(*)
      TMP59 = (F1(3)*F4(3)*(F2(3)*F3(3)+F2(4)*F3(4))+F1(4)*F4(4)*(F2(3)
     $ *F3(3)+F2(4)*F3(4)))
      TMP62 = (F1(3)*F4(3)*(F2(3)*F3(3)+F2(4)*F3(4))+F1(4)*F4(4)*(F2(3)
     $ *F3(3)+F2(4)*F3(4)))
      VERTEX = COUP*(-8D0)*(+CI*(TMP62+TMP59))
      END


