C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     -(P(1,2)*P(2,3)*P(3,1)) + P(1,3)*P(2,1)*P(3,2) +
C      P(-1,2)*P(-1,3)*P(3,1)*Metric(1,2) - P(-1,1)*P(-1,3)*P(3,2)*Metr
C     ic(1,2) - P(-1,2)*P(-1,3)*P(2,1)*Metric(1,3) +
C      P(-1,1)*P(-1,2)*P(2,3)*Metric(1,3) + P(-1,1)*P(-1,3)*P(1,2)*Metr
C     ic(2,3) - P(-1,1)*P(-1,2)*P(1,3)*Metric(2,3)
C     
      SUBROUTINE VVVS7P0_1(V2, V3, S4, COUP, M1, W1,V1)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 V2(*)
      COMPLEX*16 DENOM
      COMPLEX*16 V3(*)
      REAL*8 P1(0:3)
      COMPLEX*16 TMP22
      REAL*8 P2(0:3)
      COMPLEX*16 TMP23
      REAL*8 P3(0:3)
      COMPLEX*16 TMP20
      COMPLEX*16 TMP33
      COMPLEX*16 TMP32
      COMPLEX*16 TMP28
      REAL*8 W1
      REAL*8 M1
      COMPLEX*16 COUP
      COMPLEX*16 S4(*)
      COMPLEX*16 TMP19
      COMPLEX*16 V1(6)
      COMPLEX*16 TMP18
      P2(0) = DBLE(V2(1))
      P2(1) = DBLE(V2(2))
      P2(2) = DIMAG(V2(2))
      P2(3) = DIMAG(V2(1))
      P3(0) = DBLE(V3(1))
      P3(1) = DBLE(V3(2))
      P3(2) = DIMAG(V3(2))
      P3(3) = DIMAG(V3(1))
      V1(1) = +V2(1)+V3(1)+S4(1)
      V1(2) = +V2(2)+V3(2)+S4(2)
      P1(0) = -DBLE(V1(1))
      P1(1) = -DBLE(V1(2))
      P1(2) = -DIMAG(V1(2))
      P1(3) = -DIMAG(V1(1))
      TMP20 = (P1(0)*V2(3)-P1(1)*V2(4)-P1(2)*V2(5)-P1(3)*V2(6))
      TMP22 = (P3(0)*V2(3)-P3(1)*V2(4)-P3(2)*V2(5)-P3(3)*V2(6))
      TMP23 = (V3(3)*V2(3)-V3(4)*V2(4)-V3(5)*V2(5)-V3(6)*V2(6))
      TMP28 = (P1(0)*P2(0)-P1(1)*P2(1)-P1(2)*P2(2)-P1(3)*P2(3))
      TMP19 = (V3(3)*P2(0)-V3(4)*P2(1)-V3(5)*P2(2)-V3(6)*P2(3))
      TMP18 = (V3(3)*P1(0)-V3(4)*P1(1)-V3(5)*P1(2)-V3(6)*P1(3))
      TMP33 = (P3(0)*P2(0)-P3(1)*P2(1)-P3(2)*P2(2)-P3(3)*P2(3))
      TMP32 = (P3(0)*P1(0)-P3(1)*P1(1)-P3(2)*P1(2)-P3(3)*P1(3))
      DENOM = COUP/(P1(0)**2-P1(1)**2-P1(2)**2-P1(3)**2 - M1 * (M1 -CI
     $ * W1))
      V1(3)= DENOM*S4(3)*(P2(0)*(-CI*(TMP23*TMP32)+CI*(TMP18*TMP22))
     $ +(P3(0)*(-CI*(TMP19*TMP20)+CI*(TMP23*TMP28))+(TMP33*(-CI*(V2(3)
     $ *TMP18)+CI*(V3(3)*TMP20))+(-CI*(V3(3)*TMP22*TMP28)+CI*(V2(3)
     $ *TMP19*TMP32)))))
      V1(4)= DENOM*S4(3)*(P2(1)*(-CI*(TMP23*TMP32)+CI*(TMP18*TMP22))
     $ +(P3(1)*(-CI*(TMP19*TMP20)+CI*(TMP23*TMP28))+(TMP33*(-CI*(V2(4)
     $ *TMP18)+CI*(V3(4)*TMP20))+(-CI*(V3(4)*TMP22*TMP28)+CI*(V2(4)
     $ *TMP19*TMP32)))))
      V1(5)= DENOM*S4(3)*(P2(2)*(-CI*(TMP23*TMP32)+CI*(TMP18*TMP22))
     $ +(P3(2)*(-CI*(TMP19*TMP20)+CI*(TMP23*TMP28))+(TMP33*(-CI*(V2(5)
     $ *TMP18)+CI*(V3(5)*TMP20))+(-CI*(V3(5)*TMP22*TMP28)+CI*(V2(5)
     $ *TMP19*TMP32)))))
      V1(6)= DENOM*S4(3)*(P2(3)*(-CI*(TMP23*TMP32)+CI*(TMP18*TMP22))
     $ +(P3(3)*(-CI*(TMP19*TMP20)+CI*(TMP23*TMP28))+(TMP33*(-CI*(V2(6)
     $ *TMP18)+CI*(V3(6)*TMP20))+(-CI*(V3(6)*TMP22*TMP28)+CI*(V2(6)
     $ *TMP19*TMP32)))))
      END


