C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(1,2)*P(2,1)*P(3,1) - P(1,3)*P(2,1)*P(3,1) +
C      3*P(1,2)*P(2,3)*P(3,1) + P(1,3)*P(2,3)*P(3,1) -
C      P(1,2)*P(2,1)*P(3,2) - 3*P(1,3)*P(2,1)*P(3,2) +
C      P(1,2)*P(2,3)*P(3,2) - P(1,3)*P(2,3)*P(3,2) +
C      (P(-1,1)**2*P(3,1)*Metric(1,2))/2. - P(-1,1)*P(-1,2)*P(3,1)*Metr
C     ic(1,2) + (P(-1,2)**2*P(3,1)*Metric(1,2))/2. -
C      2*P(-1,2)*P(-1,3)*P(3,1)*Metric(1,2) + (P(-1,3)**2*P(3,1)*Metric
C     (1,2))/2. - (P(-1,1)**2*P(3,2)*Metric(1,2))/2. +
C      P(-1,1)*P(-1,2)*P(3,2)*Metric(1,2) - (P(-1,2)**2*P(3,2)*Metric(1
C     ,2))/2. + 2*P(-1,1)*P(-1,3)*P(3,2)*Metric(1,2) -
C      (P(-1,3)**2*P(3,2)*Metric(1,2))/2. - (P(-1,1)**2*P(2,1)*Metric(1
C     ,3))/2. - (P(-1,2)**2*P(2,1)*Metric(1,3))/2. +
C      P(-1,1)*P(-1,3)*P(2,1)*Metric(1,3) + 2*P(-1,2)*P(-1,3)*P(2,1)*Me
C     tric(1,3) - (P(-1,3)**2*P(2,1)*Metric(1,3))/2. +
C      (P(-1,1)**2*P(2,3)*Metric(1,3))/2. - 2*P(-1,1)*P(-1,2)*P(2,3)*Me
C     tric(1,3) + (P(-1,2)**2*P(2,3)*Metric(1,3))/2. -
C      P(-1,1)*P(-1,3)*P(2,3)*Metric(1,3) + (P(-1,3)**2*P(2,3)*Metric(1
C     ,3))/2. + (P(-1,1)**2*P(1,2)*Metric(2,3))/2. +
C      (P(-1,2)**2*P(1,2)*Metric(2,3))/2. - 2*P(-1,1)*P(-1,3)*P(1,2)*Me
C     tric(2,3) - P(-1,2)*P(-1,3)*P(1,2)*Metric(2,3) +
C      (P(-1,3)**2*P(1,2)*Metric(2,3))/2. - (P(-1,1)**2*P(1,3)*Metric(2
C     ,3))/2. + 2*P(-1,1)*P(-1,2)*P(1,3)*Metric(2,3) -
C      (P(-1,2)**2*P(1,3)*Metric(2,3))/2. + P(-1,2)*P(-1,3)*P(1,3)*Metr
C     ic(2,3) - (P(-1,3)**2*P(1,3)*Metric(2,3))/2.
C     
      SUBROUTINE VVVS10_0(V1, V2, V3, S4, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      REAL*8 P3(0:3)
      COMPLEX*16 TMP21
      COMPLEX*16 TMP32
      COMPLEX*16 TMP28
      COMPLEX*16 TMP25
      COMPLEX*16 S4(*)
      COMPLEX*16 V3(*)
      REAL*8 P2(0:3)
      COMPLEX*16 TMP20
      COMPLEX*16 TMP33
      COMPLEX*16 TMP24
      COMPLEX*16 TMP18
      COMPLEX*16 TMP19
      COMPLEX*16 V2(*)
      REAL*8 P1(0:3)
      COMPLEX*16 TMP23
      COMPLEX*16 TMP30
      COMPLEX*16 VERTEX
      COMPLEX*16 V1(*)
      COMPLEX*16 TMP22
      COMPLEX*16 TMP17
      COMPLEX*16 TMP14
      COMPLEX*16 COUP
      COMPLEX*16 TMP31
      P1(0) = DBLE(V1(1))
      P1(1) = DBLE(V1(2))
      P1(2) = DIMAG(V1(2))
      P1(3) = DIMAG(V1(1))
      P2(0) = DBLE(V2(1))
      P2(1) = DBLE(V2(2))
      P2(2) = DIMAG(V2(2))
      P2(3) = DIMAG(V2(1))
      P3(0) = DBLE(V3(1))
      P3(1) = DBLE(V3(2))
      P3(2) = DIMAG(V3(2))
      P3(3) = DIMAG(V3(1))
      TMP24 = (P2(0)*V1(3)-P2(1)*V1(4)-P2(2)*V1(5)-P2(3)*V1(6))
      TMP25 = (P3(0)*V1(3)-P3(1)*V1(4)-P3(2)*V1(5)-P3(3)*V1(6))
      TMP20 = (P1(0)*V2(3)-P1(1)*V2(4)-P1(2)*V2(5)-P1(3)*V2(6))
      TMP21 = (V3(3)*V1(3)-V3(4)*V1(4)-V3(5)*V1(5)-V3(6)*V1(6))
      TMP22 = (P3(0)*V2(3)-P3(1)*V2(4)-P3(2)*V2(5)-P3(3)*V2(6))
      TMP23 = (V3(3)*V2(3)-V3(4)*V2(4)-V3(5)*V2(5)-V3(6)*V2(6))
      TMP28 = (P1(0)*P2(0)-P1(1)*P2(1)-P1(2)*P2(2)-P1(3)*P2(3))
      TMP19 = (V3(3)*P2(0)-V3(4)*P2(1)-V3(5)*P2(2)-V3(6)*P2(3))
      TMP18 = (V3(3)*P1(0)-V3(4)*P1(1)-V3(5)*P1(2)-V3(6)*P1(3))
      TMP14 = (P3(0)*P3(0)-P3(1)*P3(1)-P3(2)*P3(2)-P3(3)*P3(3))
      TMP33 = (P3(0)*P2(0)-P3(1)*P2(1)-P3(2)*P2(2)-P3(3)*P2(3))
      TMP32 = (P3(0)*P1(0)-P3(1)*P1(1)-P3(2)*P1(2)-P3(3)*P1(3))
      TMP17 = (V2(3)*V1(3)-V2(4)*V1(4)-V2(5)*V1(5)-V2(6)*V1(6))
      TMP30 = (P1(0)*P1(0)-P1(1)*P1(1)-P1(2)*P1(2)-P1(3)*P1(3))
      TMP31 = (P2(0)*P2(0)-P2(1)*P2(1)-P2(2)*P2(2)-P2(3)*P2(3))
      VERTEX = COUP*1D0/2D0 * S4(3)*(TMP17*(TMP18*(-1D0)*(-2D0 * CI
     $ *(TMP28)+CI*(TMP30+TMP31+TMP14)-4D0 * CI*(TMP33))+TMP19*(-2D0 *
     $  CI*(TMP28)+CI*(TMP30+TMP31+TMP14)-4D0 * CI*(TMP32)))+(TMP21
     $ *(TMP20*(-2D0 * CI*(TMP32)+CI*(TMP30+TMP31+TMP14)-4D0 * CI
     $ *(TMP33))-TMP22*(-2D0 * CI*(TMP32)+CI*(TMP30+TMP31+TMP14)-4D0 *
     $  CI*(TMP28)))+(TMP23*(TMP24*(-1D0)*(-2D0 * CI*(TMP33)+CI*(TMP30
     $ +TMP31+TMP14)-4D0 * CI*(TMP32))+TMP25*(-2D0 * CI*(TMP33)+CI
     $ *(TMP30+TMP31+TMP14)-4D0 * CI*(TMP28)))+(TMP18*(TMP20*2D0*(-CI
     $ *(TMP24)+CI*(TMP25))-2D0*(TMP22*(+3D0 * CI*(TMP24)+CI*(TMP25))))
     $ +TMP19*(TMP20*2D0*(+3D0 * CI*(TMP25)+CI*(TMP24))+2D0*(TMP22*(
     $ -CI*(TMP24)+CI*(TMP25))))))))
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(1,2)*P(2,1)*P(3,1) - P(1,3)*P(2,1)*P(3,1) +
C      3*P(1,2)*P(2,3)*P(3,1) + P(1,3)*P(2,3)*P(3,1) -
C      P(1,2)*P(2,1)*P(3,2) - 3*P(1,3)*P(2,1)*P(3,2) +
C      P(1,2)*P(2,3)*P(3,2) - P(1,3)*P(2,3)*P(3,2) +
C      (P(-1,1)**2*P(3,1)*Metric(1,2))/2. - P(-1,1)*P(-1,2)*P(3,1)*Metr
C     ic(1,2) + (P(-1,2)**2*P(3,1)*Metric(1,2))/2. -
C      2*P(-1,2)*P(-1,3)*P(3,1)*Metric(1,2) + (P(-1,3)**2*P(3,1)*Metric
C     (1,2))/2. - (P(-1,1)**2*P(3,2)*Metric(1,2))/2. +
C      P(-1,1)*P(-1,2)*P(3,2)*Metric(1,2) - (P(-1,2)**2*P(3,2)*Metric(1
C     ,2))/2. + 2*P(-1,1)*P(-1,3)*P(3,2)*Metric(1,2) -
C      (P(-1,3)**2*P(3,2)*Metric(1,2))/2. - (P(-1,1)**2*P(2,1)*Metric(1
C     ,3))/2. - (P(-1,2)**2*P(2,1)*Metric(1,3))/2. +
C      P(-1,1)*P(-1,3)*P(2,1)*Metric(1,3) + 2*P(-1,2)*P(-1,3)*P(2,1)*Me
C     tric(1,3) - (P(-1,3)**2*P(2,1)*Metric(1,3))/2. +
C      (P(-1,1)**2*P(2,3)*Metric(1,3))/2. - 2*P(-1,1)*P(-1,2)*P(2,3)*Me
C     tric(1,3) + (P(-1,2)**2*P(2,3)*Metric(1,3))/2. -
C      P(-1,1)*P(-1,3)*P(2,3)*Metric(1,3) + (P(-1,3)**2*P(2,3)*Metric(1
C     ,3))/2. + (P(-1,1)**2*P(1,2)*Metric(2,3))/2. +
C      (P(-1,2)**2*P(1,2)*Metric(2,3))/2. - 2*P(-1,1)*P(-1,3)*P(1,2)*Me
C     tric(2,3) - P(-1,2)*P(-1,3)*P(1,2)*Metric(2,3) +
C      (P(-1,3)**2*P(1,2)*Metric(2,3))/2. - (P(-1,1)**2*P(1,3)*Metric(2
C     ,3))/2. + 2*P(-1,1)*P(-1,2)*P(1,3)*Metric(2,3) -
C      (P(-1,2)**2*P(1,3)*Metric(2,3))/2. + P(-1,2)*P(-1,3)*P(1,3)*Metr
C     ic(2,3) - (P(-1,3)**2*P(1,3)*Metric(2,3))/2.
C     
      SUBROUTINE VVVS10_6_8_9_0(V1, V2, V3, S4, COUP1, COUP2, COUP3,
     $  COUP4,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      REAL*8 P3(0:3)
      COMPLEX*16 COUP2
      COMPLEX*16 TMP
      COMPLEX*16 S4(*)
      COMPLEX*16 V3(*)
      REAL*8 P2(0:3)
      COMPLEX*16 COUP1
      COMPLEX*16 COUP3
      COMPLEX*16 COUP4
      COMPLEX*16 V2(*)
      REAL*8 P1(0:3)
      COMPLEX*16 VERTEX
      COMPLEX*16 V1(*)
      CALL VVVS10_0(V1,V2,V3,S4,COUP1,VERTEX)
      CALL VVVS6_0(V1,V2,V3,S4,COUP2,TMP)
      VERTEX = VERTEX + TMP
      CALL VVVS8_0(V1,V2,V3,S4,COUP3,TMP)
      VERTEX = VERTEX + TMP
      CALL VVVS9_0(V1,V2,V3,S4,COUP4,TMP)
      VERTEX = VERTEX + TMP
      END


