C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(1,2)*P(2,1)*P(3,1) - P(1,3)*P(2,1)*P(3,1) +
C      3*P(1,2)*P(2,3)*P(3,1) + P(1,3)*P(2,3)*P(3,1) -
C      P(1,2)*P(2,1)*P(3,2) - 3*P(1,3)*P(2,1)*P(3,2) +
C      P(1,2)*P(2,3)*P(3,2) - P(1,3)*P(2,3)*P(3,2) +
C      (P(-1,1)**2*P(3,1)*Metric(1,2))/2. - P(-1,1)*P(-1,2)*P(3,1)*Metr
C     ic(1,2) + (P(-1,2)**2*P(3,1)*Metric(1,2))/2. -
C      2*P(-1,2)*P(-1,3)*P(3,1)*Metric(1,2) + (P(-1,3)**2*P(3,1)*Metric
C     (1,2))/2. - (P(-1,1)**2*P(3,2)*Metric(1,2))/2. +
C      P(-1,1)*P(-1,2)*P(3,2)*Metric(1,2) - (P(-1,2)**2*P(3,2)*Metric(1
C     ,2))/2. + 2*P(-1,1)*P(-1,3)*P(3,2)*Metric(1,2) -
C      (P(-1,3)**2*P(3,2)*Metric(1,2))/2. - (P(-1,1)**2*P(2,1)*Metric(1
C     ,3))/2. - (P(-1,2)**2*P(2,1)*Metric(1,3))/2. +
C      P(-1,1)*P(-1,3)*P(2,1)*Metric(1,3) + 2*P(-1,2)*P(-1,3)*P(2,1)*Me
C     tric(1,3) - (P(-1,3)**2*P(2,1)*Metric(1,3))/2. +
C      (P(-1,1)**2*P(2,3)*Metric(1,3))/2. - 2*P(-1,1)*P(-1,2)*P(2,3)*Me
C     tric(1,3) + (P(-1,2)**2*P(2,3)*Metric(1,3))/2. -
C      P(-1,1)*P(-1,3)*P(2,3)*Metric(1,3) + (P(-1,3)**2*P(2,3)*Metric(1
C     ,3))/2. + (P(-1,1)**2*P(1,2)*Metric(2,3))/2. +
C      (P(-1,2)**2*P(1,2)*Metric(2,3))/2. - 2*P(-1,1)*P(-1,3)*P(1,2)*Me
C     tric(2,3) - P(-1,2)*P(-1,3)*P(1,2)*Metric(2,3) +
C      (P(-1,3)**2*P(1,2)*Metric(2,3))/2. - (P(-1,1)**2*P(1,3)*Metric(2
C     ,3))/2. + 2*P(-1,1)*P(-1,2)*P(1,3)*Metric(2,3) -
C      (P(-1,2)**2*P(1,3)*Metric(2,3))/2. + P(-1,2)*P(-1,3)*P(1,3)*Metr
C     ic(2,3) - (P(-1,3)**2*P(1,3)*Metric(2,3))/2.
C     
      SUBROUTINE VVVS10P0_1(V2, V3, S4, COUP, M1, W1,V1)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      REAL*8 P3(0:3)
      REAL*8 W1
      COMPLEX*16 TMP32
      COMPLEX*16 TMP28
      COMPLEX*16 COUP
      COMPLEX*16 S4(*)
      COMPLEX*16 V3(*)
      REAL*8 M1
      REAL*8 P2(0:3)
      COMPLEX*16 TMP20
      COMPLEX*16 TMP33
      COMPLEX*16 TMP18
      COMPLEX*16 TMP19
      COMPLEX*16 V2(*)
      REAL*8 P1(0:3)
      COMPLEX*16 TMP23
      COMPLEX*16 TMP30
      COMPLEX*16 DENOM
      COMPLEX*16 V1(6)
      COMPLEX*16 TMP22
      COMPLEX*16 TMP31
      COMPLEX*16 TMP14
      P2(0) = DBLE(V2(1))
      P2(1) = DBLE(V2(2))
      P2(2) = DIMAG(V2(2))
      P2(3) = DIMAG(V2(1))
      P3(0) = DBLE(V3(1))
      P3(1) = DBLE(V3(2))
      P3(2) = DIMAG(V3(2))
      P3(3) = DIMAG(V3(1))
      V1(1) = +V2(1)+V3(1)+S4(1)
      V1(2) = +V2(2)+V3(2)+S4(2)
      P1(0) = -DBLE(V1(1))
      P1(1) = -DBLE(V1(2))
      P1(2) = -DIMAG(V1(2))
      P1(3) = -DIMAG(V1(1))
      TMP20 = (P1(0)*V2(3)-P1(1)*V2(4)-P1(2)*V2(5)-P1(3)*V2(6))
      TMP22 = (P3(0)*V2(3)-P3(1)*V2(4)-P3(2)*V2(5)-P3(3)*V2(6))
      TMP23 = (V3(3)*V2(3)-V3(4)*V2(4)-V3(5)*V2(5)-V3(6)*V2(6))
      TMP28 = (P1(0)*P2(0)-P1(1)*P2(1)-P1(2)*P2(2)-P1(3)*P2(3))
      TMP19 = (V3(3)*P2(0)-V3(4)*P2(1)-V3(5)*P2(2)-V3(6)*P2(3))
      TMP18 = (V3(3)*P1(0)-V3(4)*P1(1)-V3(5)*P1(2)-V3(6)*P1(3))
      TMP14 = (P3(0)*P3(0)-P3(1)*P3(1)-P3(2)*P3(2)-P3(3)*P3(3))
      TMP33 = (P3(0)*P2(0)-P3(1)*P2(1)-P3(2)*P2(2)-P3(3)*P2(3))
      TMP32 = (P3(0)*P1(0)-P3(1)*P1(1)-P3(2)*P1(2)-P3(3)*P1(3))
      TMP31 = (P2(0)*P2(0)-P2(1)*P2(1)-P2(2)*P2(2)-P2(3)*P2(3))
      TMP30 = (P1(0)*P1(0)-P1(1)*P1(1)-P1(2)*P1(2)-P1(3)*P1(3))
      DENOM = COUP/(P1(0)**2-P1(1)**2-P1(2)**2-P1(3)**2 - M1 * (M1 -CI
     $ * W1))
      V1(3)= DENOM*1D0/2D0 * S4(3)*(TMP23*(P2(0)*(-1D0)*(-2D0 * CI
     $ *(TMP33)+CI*(TMP30+TMP31+TMP14)-4D0 * CI*(TMP32))+P3(0)*(-2D0 *
     $  CI*(TMP33)+CI*(TMP30+TMP31+TMP14)-4D0 * CI*(TMP28)))+(V2(3)
     $ *(TMP18*(-1D0)*(-2D0 * CI*(TMP28)+CI*(TMP30+TMP31+TMP14)-4D0 *
     $  CI*(TMP33))+TMP19*(-2D0 * CI*(TMP28)+CI*(TMP30+TMP31+TMP14)
     $ -4D0 * CI*(TMP32)))+(V3(3)*(TMP20*(-2D0 * CI*(TMP32)+CI*(TMP30
     $ +TMP31+TMP14)-4D0 * CI*(TMP33))-TMP22*(-2D0 * CI*(TMP32)+CI
     $ *(TMP30+TMP31+TMP14)-4D0 * CI*(TMP28)))+(P2(0)*(TMP18*(-2D0)*(
     $ +3D0 * CI*(TMP22)+CI*(TMP20))+2D0*(TMP19*(-CI*(TMP22)+CI*(TMP20)
     $ )))+P3(0)*(TMP18*2D0*(-CI*(TMP22)+CI*(TMP20))+2D0*(TMP19*(+3D0 
     $ * CI*(TMP20)+CI*(TMP22))))))))
      V1(4)= DENOM*1D0/2D0 * S4(3)*(TMP23*(P2(1)*(-1D0)*(-2D0 * CI
     $ *(TMP33)+CI*(TMP30+TMP31+TMP14)-4D0 * CI*(TMP32))+P3(1)*(-2D0 *
     $  CI*(TMP33)+CI*(TMP30+TMP31+TMP14)-4D0 * CI*(TMP28)))+(V2(4)
     $ *(TMP18*(-1D0)*(-2D0 * CI*(TMP28)+CI*(TMP30+TMP31+TMP14)-4D0 *
     $  CI*(TMP33))+TMP19*(-2D0 * CI*(TMP28)+CI*(TMP30+TMP31+TMP14)
     $ -4D0 * CI*(TMP32)))+(V3(4)*(TMP20*(-2D0 * CI*(TMP32)+CI*(TMP30
     $ +TMP31+TMP14)-4D0 * CI*(TMP33))-TMP22*(-2D0 * CI*(TMP32)+CI
     $ *(TMP30+TMP31+TMP14)-4D0 * CI*(TMP28)))+(P2(1)*(TMP18*(-2D0)*(
     $ +3D0 * CI*(TMP22)+CI*(TMP20))+2D0*(TMP19*(-CI*(TMP22)+CI*(TMP20)
     $ )))+P3(1)*(TMP18*2D0*(-CI*(TMP22)+CI*(TMP20))+2D0*(TMP19*(+3D0 
     $ * CI*(TMP20)+CI*(TMP22))))))))
      V1(5)= DENOM*1D0/2D0 * S4(3)*(TMP23*(P2(2)*(-1D0)*(-2D0 * CI
     $ *(TMP33)+CI*(TMP30+TMP31+TMP14)-4D0 * CI*(TMP32))+P3(2)*(-2D0 *
     $  CI*(TMP33)+CI*(TMP30+TMP31+TMP14)-4D0 * CI*(TMP28)))+(V2(5)
     $ *(TMP18*(-1D0)*(-2D0 * CI*(TMP28)+CI*(TMP30+TMP31+TMP14)-4D0 *
     $  CI*(TMP33))+TMP19*(-2D0 * CI*(TMP28)+CI*(TMP30+TMP31+TMP14)
     $ -4D0 * CI*(TMP32)))+(V3(5)*(TMP20*(-2D0 * CI*(TMP32)+CI*(TMP30
     $ +TMP31+TMP14)-4D0 * CI*(TMP33))-TMP22*(-2D0 * CI*(TMP32)+CI
     $ *(TMP30+TMP31+TMP14)-4D0 * CI*(TMP28)))+(P2(2)*(TMP18*(-2D0)*(
     $ +3D0 * CI*(TMP22)+CI*(TMP20))+2D0*(TMP19*(-CI*(TMP22)+CI*(TMP20)
     $ )))+P3(2)*(TMP18*2D0*(-CI*(TMP22)+CI*(TMP20))+2D0*(TMP19*(+3D0 
     $ * CI*(TMP20)+CI*(TMP22))))))))
      V1(6)= DENOM*1D0/2D0 * S4(3)*(TMP23*(P2(3)*(-1D0)*(-2D0 * CI
     $ *(TMP33)+CI*(TMP30+TMP31+TMP14)-4D0 * CI*(TMP32))+P3(3)*(-2D0 *
     $  CI*(TMP33)+CI*(TMP30+TMP31+TMP14)-4D0 * CI*(TMP28)))+(V2(6)
     $ *(TMP18*(-1D0)*(-2D0 * CI*(TMP28)+CI*(TMP30+TMP31+TMP14)-4D0 *
     $  CI*(TMP33))+TMP19*(-2D0 * CI*(TMP28)+CI*(TMP30+TMP31+TMP14)
     $ -4D0 * CI*(TMP32)))+(V3(6)*(TMP20*(-2D0 * CI*(TMP32)+CI*(TMP30
     $ +TMP31+TMP14)-4D0 * CI*(TMP33))-TMP22*(-2D0 * CI*(TMP32)+CI
     $ *(TMP30+TMP31+TMP14)-4D0 * CI*(TMP28)))+(P2(3)*(TMP18*(-2D0)*(
     $ +3D0 * CI*(TMP22)+CI*(TMP20))+2D0*(TMP19*(-CI*(TMP22)+CI*(TMP20)
     $ )))+P3(3)*(TMP18*2D0*(-CI*(TMP22)+CI*(TMP20))+2D0*(TMP19*(+3D0 
     $ * CI*(TMP20)+CI*(TMP22))))))))
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(1,2)*P(2,1)*P(3,1) - P(1,3)*P(2,1)*P(3,1) +
C      3*P(1,2)*P(2,3)*P(3,1) + P(1,3)*P(2,3)*P(3,1) -
C      P(1,2)*P(2,1)*P(3,2) - 3*P(1,3)*P(2,1)*P(3,2) +
C      P(1,2)*P(2,3)*P(3,2) - P(1,3)*P(2,3)*P(3,2) +
C      (P(-1,1)**2*P(3,1)*Metric(1,2))/2. - P(-1,1)*P(-1,2)*P(3,1)*Metr
C     ic(1,2) + (P(-1,2)**2*P(3,1)*Metric(1,2))/2. -
C      2*P(-1,2)*P(-1,3)*P(3,1)*Metric(1,2) + (P(-1,3)**2*P(3,1)*Metric
C     (1,2))/2. - (P(-1,1)**2*P(3,2)*Metric(1,2))/2. +
C      P(-1,1)*P(-1,2)*P(3,2)*Metric(1,2) - (P(-1,2)**2*P(3,2)*Metric(1
C     ,2))/2. + 2*P(-1,1)*P(-1,3)*P(3,2)*Metric(1,2) -
C      (P(-1,3)**2*P(3,2)*Metric(1,2))/2. - (P(-1,1)**2*P(2,1)*Metric(1
C     ,3))/2. - (P(-1,2)**2*P(2,1)*Metric(1,3))/2. +
C      P(-1,1)*P(-1,3)*P(2,1)*Metric(1,3) + 2*P(-1,2)*P(-1,3)*P(2,1)*Me
C     tric(1,3) - (P(-1,3)**2*P(2,1)*Metric(1,3))/2. +
C      (P(-1,1)**2*P(2,3)*Metric(1,3))/2. - 2*P(-1,1)*P(-1,2)*P(2,3)*Me
C     tric(1,3) + (P(-1,2)**2*P(2,3)*Metric(1,3))/2. -
C      P(-1,1)*P(-1,3)*P(2,3)*Metric(1,3) + (P(-1,3)**2*P(2,3)*Metric(1
C     ,3))/2. + (P(-1,1)**2*P(1,2)*Metric(2,3))/2. +
C      (P(-1,2)**2*P(1,2)*Metric(2,3))/2. - 2*P(-1,1)*P(-1,3)*P(1,2)*Me
C     tric(2,3) - P(-1,2)*P(-1,3)*P(1,2)*Metric(2,3) +
C      (P(-1,3)**2*P(1,2)*Metric(2,3))/2. - (P(-1,1)**2*P(1,3)*Metric(2
C     ,3))/2. + 2*P(-1,1)*P(-1,2)*P(1,3)*Metric(2,3) -
C      (P(-1,2)**2*P(1,3)*Metric(2,3))/2. + P(-1,2)*P(-1,3)*P(1,3)*Metr
C     ic(2,3) - (P(-1,3)**2*P(1,3)*Metric(2,3))/2.
C     
      SUBROUTINE VVVS10_6_8_9P0_1(V2, V3, S4, COUP1, COUP2, COUP3,
     $  COUP4, M1, W1,V1)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      REAL*8 P3(0:3)
      REAL*8 W1
      COMPLEX*16 COUP2
      COMPLEX*16 VTMP(6)
      COMPLEX*16 S4(*)
      COMPLEX*16 V3(*)
      REAL*8 M1
      REAL*8 P2(0:3)
      COMPLEX*16 COUP1
      COMPLEX*16 COUP3
      COMPLEX*16 COUP4
      COMPLEX*16 V2(*)
      REAL*8 P1(0:3)
      COMPLEX*16 DENOM
      INTEGER*4 I
      COMPLEX*16 V1(6)
      CALL VVVS10P0_1(V2,V3,S4,COUP1,M1,W1,V1)
      CALL VVVS6P0_1(V2,V3,S4,COUP2,M1,W1,VTMP)
      DO I = 3, 6
        V1(I) = V1(I) + VTMP(I)
      ENDDO
      CALL VVVS8P0_1(V2,V3,S4,COUP3,M1,W1,VTMP)
      DO I = 3, 6
        V1(I) = V1(I) + VTMP(I)
      ENDDO
      CALL VVVS9P0_1(V2,V3,S4,COUP4,M1,W1,VTMP)
      DO I = 3, 6
        V1(I) = V1(I) + VTMP(I)
      ENDDO
      END


