C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(1,1)*P(2,2)*P(3,1) + 2*P(1,2)*P(2,2)*P(3,1) +
C      2*P(1,1)*P(2,3)*P(3,1) - 2*P(1,1)*P(2,1)*P(3,2) -
C      P(1,1)*P(2,2)*P(3,2) - 2*P(1,3)*P(2,2)*P(3,2) -
C      P(1,1)*P(2,1)*P(3,3) - 2*P(1,3)*P(2,1)*P(3,3) +
C      P(1,2)*P(2,2)*P(3,3) - P(1,3)*P(2,2)*P(3,3) +
C      P(1,1)*P(2,3)*P(3,3) + 2*P(1,2)*P(2,3)*P(3,3) -
C      2*P(-1,2)**2*P(3,1)*Metric(1,2) - P(-1,3)**2*P(3,1)*Metric(1,2)
C      + 2*P(-1,1)**2*P(3,2)*Metric(1,2) + P(-1,3)**2*P(3,2)*Metric(1,2)
C      + P(-1,1)**2*P(3,3)*Metric(1,2) - P(-1,2)**2*P(3,3)*Metric(1,2)
C      + P(-1,1)*P(-1,3)*P(3,3)*Metric(1,2) - P(-1,2)*P(-1,3)*P(3,3)*Me
C     tric(1,2) + P(-1,2)**2*P(2,1)*Metric(1,3) + 2*P(-1,3)**2*P(2,1)*M
C     etric(1,3) - P(-1,1)**2*P(2,2)*Metric(1,3) - P(-1,1)*P(-1,2)*P(2,
C     2)*Metric(1,3) + P(-1,2)*P(-1,3)*P(2,2)*Metric(1,3) +
C      P(-1,3)**2*P(2,2)*Metric(1,3) - 2*P(-1,1)**2*P(2,3)*Metric(1,3)
C      - P(-1,2)**2*P(2,3)*Metric(1,3) + P(-1,1)*P(-1,2)*P(1,1)*Metric(
C     2,3) + P(-1,2)**2*P(1,1)*Metric(2,3) - P(-1,1)*P(-1,3)*P(1,1)*Met
C     ric(2,3) - P(-1,3)**2*P(1,1)*Metric(2,3) - P(-1,1)**2*P(1,2)*Metr
C     ic(2,3) - 2*P(-1,3)**2*P(1,2)*Metric(2,3) + P(-1,1)**2*P(1,3)*Met
C     ric(2,3) + 2*P(-1,2)**2*P(1,3)*Metric(2,3)
C     
      SUBROUTINE VVVS9_0(V1, V2, V3, S4, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      REAL*8 P3(0:3)
      COMPLEX*16 TMP21
      COMPLEX*16 TMP14
      COMPLEX*16 TMP28
      COMPLEX*16 TMP25
      COMPLEX*16 TMP18
      COMPLEX*16 V3(*)
      REAL*8 P2(0:3)
      COMPLEX*16 TMP20
      COMPLEX*16 TMP33
      COMPLEX*16 TMP67
      COMPLEX*16 TMP24
      COMPLEX*16 S4(*)
      COMPLEX*16 TMP19
      COMPLEX*16 V2(*)
      REAL*8 P1(0:3)
      COMPLEX*16 TMP23
      COMPLEX*16 TMP30
      COMPLEX*16 TMP66
      COMPLEX*16 VERTEX
      COMPLEX*16 V1(*)
      COMPLEX*16 TMP22
      COMPLEX*16 TMP17
      COMPLEX*16 TMP32
      COMPLEX*16 TMP65
      COMPLEX*16 COUP
      COMPLEX*16 TMP31
      P1(0) = DBLE(V1(1))
      P1(1) = DBLE(V1(2))
      P1(2) = DIMAG(V1(2))
      P1(3) = DIMAG(V1(1))
      P2(0) = DBLE(V2(1))
      P2(1) = DBLE(V2(2))
      P2(2) = DIMAG(V2(2))
      P2(3) = DIMAG(V2(1))
      P3(0) = DBLE(V3(1))
      P3(1) = DBLE(V3(2))
      P3(2) = DIMAG(V3(2))
      P3(3) = DIMAG(V3(1))
      TMP24 = (P2(0)*V1(3)-P2(1)*V1(4)-P2(2)*V1(5)-P2(3)*V1(6))
      TMP25 = (P3(0)*V1(3)-P3(1)*V1(4)-P3(2)*V1(5)-P3(3)*V1(6))
      TMP20 = (P1(0)*V2(3)-P1(1)*V2(4)-P1(2)*V2(5)-P1(3)*V2(6))
      TMP21 = (V3(3)*V1(3)-V3(4)*V1(4)-V3(5)*V1(5)-V3(6)*V1(6))
      TMP22 = (P3(0)*V2(3)-P3(1)*V2(4)-P3(2)*V2(5)-P3(3)*V2(6))
      TMP23 = (V3(3)*V2(3)-V3(4)*V2(4)-V3(5)*V2(5)-V3(6)*V2(6))
      TMP28 = (P1(0)*P2(0)-P1(1)*P2(1)-P1(2)*P2(2)-P1(3)*P2(3))
      TMP65 = (P2(0)*V2(3)-P2(1)*V2(4)-P2(2)*V2(5)-P2(3)*V2(6))
      TMP66 = (P1(0)*V1(3)-P1(1)*V1(4)-P1(2)*V1(5)-P1(3)*V1(6))
      TMP67 = (V3(3)*P3(0)-V3(4)*P3(1)-V3(5)*P3(2)-V3(6)*P3(3))
      TMP19 = (V3(3)*P2(0)-V3(4)*P2(1)-V3(5)*P2(2)-V3(6)*P2(3))
      TMP18 = (V3(3)*P1(0)-V3(4)*P1(1)-V3(5)*P1(2)-V3(6)*P1(3))
      TMP32 = (P3(0)*P1(0)-P3(1)*P1(1)-P3(2)*P1(2)-P3(3)*P1(3))
      TMP33 = (P3(0)*P2(0)-P3(1)*P2(1)-P3(2)*P2(2)-P3(3)*P2(3))
      TMP14 = (P3(0)*P3(0)-P3(1)*P3(1)-P3(2)*P3(2)-P3(3)*P3(3))
      TMP17 = (V2(3)*V1(3)-V2(4)*V1(4)-V2(5)*V1(5)-V2(6)*V1(6))
      TMP30 = (P1(0)*P1(0)-P1(1)*P1(1)-P1(2)*P1(2)-P1(3)*P1(3))
      TMP31 = (P2(0)*P2(0)-P2(1)*P2(1)-P2(2)*P2(2)-P2(3)*P2(3))
      VERTEX = COUP*S4(3)*(TMP65*(TMP21*(-CI*(TMP33+TMP14)+CI*(TMP30
     $ +TMP28))+(TMP18*(-1D0)*(+CI*(TMP66)+2D0 * CI*(TMP24))+(TMP19*(
     $ +CI*(TMP66)+2D0 * CI*(TMP25))+TMP67*(-CI*(TMP24)+CI*(TMP25)))))
     $ +(TMP17*(TMP67*(-CI*(TMP30+TMP32)+CI*(TMP31+TMP33))+(TMP14*(-CI
     $ *(TMP19)+CI*(TMP18))+(-2D0 * CI*(TMP19*TMP30)+2D0 * CI*(TMP18
     $ *TMP31))))+(TMP23*(TMP66*(-CI*(TMP28+TMP31)+CI*(TMP32+TMP14))
     $ +(TMP24*(+CI*(TMP30)+2D0 * CI*(TMP14))-TMP25*(+CI*(TMP30)+2D0 *
     $  CI*(TMP31))))+(TMP20*(TMP21*(-1D0)*(+CI*(TMP31)+2D0 * CI
     $ *(TMP14))+(TMP66*(+CI*(TMP67)+2D0 * CI*(TMP19))+2D0 * CI*(TMP25
     $ *TMP67)))+TMP22*(TMP21*(+CI*(TMP31)+2D0 * CI*(TMP30))+(TMP66*(
     $ -1D0)*(+CI*(TMP67)+2D0 * CI*(TMP18))-2D0 * CI*(TMP24*TMP67))))))
     $ )
      END


