C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(1,2)*P(2,1)*P(3,1) - P(1,3)*P(2,1)*P(3,1) +
C      P(1,3)*P(2,3)*P(3,1) - P(1,2)*P(2,1)*P(3,2) +
C      P(1,2)*P(2,3)*P(3,2) - P(1,3)*P(2,3)*P(3,2) -
C      2*P(-1,1)*P(-1,2)*P(3,1)*Metric(1,2) - P(-1,1)*P(-1,3)*P(3,1)*Me
C     tric(1,2) + 2*P(-1,1)*P(-1,2)*P(3,2)*Metric(1,2) +
C      P(-1,2)*P(-1,3)*P(3,2)*Metric(1,2) + P(-1,1)*P(-1,2)*P(2,1)*Metr
C     ic(1,3) + 2*P(-1,1)*P(-1,3)*P(2,1)*Metric(1,3) -
C      2*P(-1,1)*P(-1,3)*P(2,3)*Metric(1,3) - P(-1,2)*P(-1,3)*P(2,3)*Me
C     tric(1,3) - P(-1,1)*P(-1,2)*P(1,2)*Metric(2,3) -
C      2*P(-1,2)*P(-1,3)*P(1,2)*Metric(2,3) + P(-1,1)*P(-1,3)*P(1,3)*Me
C     tric(2,3) + 2*P(-1,2)*P(-1,3)*P(1,3)*Metric(2,3)
C     
      SUBROUTINE VVVS8_4(V1, V2, V3, COUP, M4, W4,S4)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      REAL*8 P3(0:3)
      COMPLEX*16 TMP21
      COMPLEX*16 TMP32
      COMPLEX*16 TMP28
      REAL*8 M4
      COMPLEX*16 COUP
      COMPLEX*16 TMP18
      COMPLEX*16 V3(*)
      REAL*8 P2(0:3)
      COMPLEX*16 TMP20
      COMPLEX*16 TMP33
      COMPLEX*16 TMP24
      COMPLEX*16 S4(3)
      COMPLEX*16 TMP19
      COMPLEX*16 V2(*)
      REAL*8 P1(0:3)
      COMPLEX*16 TMP23
      COMPLEX*16 DENOM
      REAL*8 P4(0:3)
      COMPLEX*16 V1(*)
      COMPLEX*16 TMP22
      COMPLEX*16 TMP17
      COMPLEX*16 TMP25
      REAL*8 W4
      P1(0) = DBLE(V1(1))
      P1(1) = DBLE(V1(2))
      P1(2) = DIMAG(V1(2))
      P1(3) = DIMAG(V1(1))
      P2(0) = DBLE(V2(1))
      P2(1) = DBLE(V2(2))
      P2(2) = DIMAG(V2(2))
      P2(3) = DIMAG(V2(1))
      P3(0) = DBLE(V3(1))
      P3(1) = DBLE(V3(2))
      P3(2) = DIMAG(V3(2))
      P3(3) = DIMAG(V3(1))
      S4(1) = +V1(1)+V2(1)+V3(1)
      S4(2) = +V1(2)+V2(2)+V3(2)
      P4(0) = -DBLE(S4(1))
      P4(1) = -DBLE(S4(2))
      P4(2) = -DIMAG(S4(2))
      P4(3) = -DIMAG(S4(1))
      TMP24 = (P2(0)*V1(3)-P2(1)*V1(4)-P2(2)*V1(5)-P2(3)*V1(6))
      TMP25 = (P3(0)*V1(3)-P3(1)*V1(4)-P3(2)*V1(5)-P3(3)*V1(6))
      TMP20 = (P1(0)*V2(3)-P1(1)*V2(4)-P1(2)*V2(5)-P1(3)*V2(6))
      TMP21 = (V3(3)*V1(3)-V3(4)*V1(4)-V3(5)*V1(5)-V3(6)*V1(6))
      TMP22 = (P3(0)*V2(3)-P3(1)*V2(4)-P3(2)*V2(5)-P3(3)*V2(6))
      TMP23 = (V3(3)*V2(3)-V3(4)*V2(4)-V3(5)*V2(5)-V3(6)*V2(6))
      TMP28 = (P1(0)*P2(0)-P1(1)*P2(1)-P1(2)*P2(2)-P1(3)*P2(3))
      TMP19 = (V3(3)*P2(0)-V3(4)*P2(1)-V3(5)*P2(2)-V3(6)*P2(3))
      TMP18 = (V3(3)*P1(0)-V3(4)*P1(1)-V3(5)*P1(2)-V3(6)*P1(3))
      TMP33 = (P3(0)*P2(0)-P3(1)*P2(1)-P3(2)*P2(2)-P3(3)*P2(3))
      TMP32 = (P3(0)*P1(0)-P3(1)*P1(1)-P3(2)*P1(2)-P3(3)*P1(3))
      TMP17 = (V2(3)*V1(3)-V2(4)*V1(4)-V2(5)*V1(5)-V2(6)*V1(6))
      DENOM = COUP/(P4(0)**2-P4(1)**2-P4(2)**2-P4(3)**2 - M4 * (M4 -CI
     $ * W4))
      S4(3)= DENOM*(TMP18*(TMP17*(-1D0)*(+CI*(TMP32)+2D0 * CI*(TMP28))
     $ +(TMP20*(-CI*(TMP25)+CI*(TMP24))+CI*(TMP22*TMP25)))+(TMP19
     $ *(TMP17*(+CI*(TMP33)+2D0 * CI*(TMP28))+(TMP22*(-CI*(TMP25)+CI
     $ *(TMP24))-CI*(TMP20*TMP24)))+(TMP21*(TMP20*(+CI*(TMP28)+2D0 *
     $  CI*(TMP32))-TMP22*(+CI*(TMP33)+2D0 * CI*(TMP32)))+TMP23*(TMP24
     $ *(-1D0)*(+CI*(TMP28)+2D0 * CI*(TMP33))+TMP25*(+CI*(TMP32)+2D0 *
     $  CI*(TMP33))))))
      END


