      SUBROUTINE M46_SMATRIXHEL(P,HEL,ANS)
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=5)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=16)
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: HEL
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)

C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
      INTEGER HEL
C     
C     GLOBAL VARIABLES
C     
      INTEGER USERHEL
      COMMON/M46_HELUSERCHOICE/USERHEL
C     ----------
C     BEGIN CODE
C     ----------
      USERHEL=HEL
      CALL M46_SMATRIX(P,ANS)
      USERHEL=-1

      END

      SUBROUTINE M46_SMATRIX(P,ANS)
C     
C     Generated by MadGraph5_aMC@NLO v. 2.6.7, 2019-10-16
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     MadGraph5_aMC@NLO StandAlone Version
C     
C     Returns amplitude squared summed/avg over colors
C     and helicities
C     for the point in phase space P(0:3,NEXTERNAL)
C     
C     Process: d d~ > h mu+ mu- NP<=1 @1
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=5)
      INTEGER    NINITIAL
      PARAMETER (NINITIAL=2)
      INTEGER NPOLENTRIES
      PARAMETER (NPOLENTRIES=(NEXTERNAL+1)*6)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=16)
      INTEGER HELAVGFACTOR
      PARAMETER (HELAVGFACTOR=4)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
C     
C     LOCAL VARIABLES 
C     
      INTEGER NHEL(NEXTERNAL,NCOMB),NTRY
C     put in common block to expose this variable to python interface
      COMMON/M46_PROCESS_NHEL/NHEL
      REAL*8 T
      REAL*8 M46_MATRIX
      INTEGER IHEL,IDEN, I, J
C     For a 1>N process, them BEAMTWO_HELAVGFACTOR would be set to 1.
      INTEGER BEAMS_HELAVGFACTOR(2)
      DATA (BEAMS_HELAVGFACTOR(I),I=1,2)/2,2/
      INTEGER JC(NEXTERNAL)
      LOGICAL GOODHEL(NCOMB)
      DATA NTRY/0/
      DATA GOODHEL/NCOMB*.FALSE./

C     
C     GLOBAL VARIABLES
C     
      INTEGER USERHEL
      COMMON/M46_HELUSERCHOICE/USERHEL
      DATA USERHEL/-1/

      DATA (NHEL(I,   1),I=1,5) / 1,-1, 0, 1,-1/
      DATA (NHEL(I,   2),I=1,5) / 1,-1, 0, 1, 1/
      DATA (NHEL(I,   3),I=1,5) / 1,-1, 0,-1,-1/
      DATA (NHEL(I,   4),I=1,5) / 1,-1, 0,-1, 1/
      DATA (NHEL(I,   5),I=1,5) / 1, 1, 0, 1,-1/
      DATA (NHEL(I,   6),I=1,5) / 1, 1, 0, 1, 1/
      DATA (NHEL(I,   7),I=1,5) / 1, 1, 0,-1,-1/
      DATA (NHEL(I,   8),I=1,5) / 1, 1, 0,-1, 1/
      DATA (NHEL(I,   9),I=1,5) /-1,-1, 0, 1,-1/
      DATA (NHEL(I,  10),I=1,5) /-1,-1, 0, 1, 1/
      DATA (NHEL(I,  11),I=1,5) /-1,-1, 0,-1,-1/
      DATA (NHEL(I,  12),I=1,5) /-1,-1, 0,-1, 1/
      DATA (NHEL(I,  13),I=1,5) /-1, 1, 0, 1,-1/
      DATA (NHEL(I,  14),I=1,5) /-1, 1, 0, 1, 1/
      DATA (NHEL(I,  15),I=1,5) /-1, 1, 0,-1,-1/
      DATA (NHEL(I,  16),I=1,5) /-1, 1, 0,-1, 1/
      DATA IDEN/36/

      INTEGER POLARIZATIONS(0:NEXTERNAL,0:5)
      COMMON/M46_BORN_BEAM_POL/POLARIZATIONS
      DATA ((POLARIZATIONS(I,J),I=0,NEXTERNAL),J=0,5)/NPOLENTRIES*-1/

C     
C     FUNCTIONS
C     
      LOGICAL M46_IS_BORN_HEL_SELECTED

C     ----------
C     BEGIN CODE
C     ----------
      IF(USERHEL.EQ.-1) NTRY=NTRY+1
      DO IHEL=1,NEXTERNAL
        JC(IHEL) = +1
      ENDDO
C     When spin-2 particles are involved, the Helicity filtering is
C      dangerous for the 2->1 topology.
C     This is because depending on the MC setup the initial PS points
C      have back-to-back initial states
C     for which some of the spin-2 helicity configurations are zero.
C      But they are no longer zero
C     if the point is boosted on the z-axis. Remember that HELAS
C      helicity amplitudes are no longer
C     lorentz invariant with expternal spin-2 particles (only the
C      helicity sum is).
C     For this reason, we simply remove the filterin when there is
C      only three external particles.
      IF (NEXTERNAL.LE.3) THEN
        DO IHEL=1,NCOMB
          GOODHEL(IHEL)=.TRUE.
        ENDDO
      ENDIF
      ANS = 0D0
      DO IHEL=1,NCOMB
        IF (USERHEL.EQ.-1.OR.USERHEL.EQ.IHEL) THEN
          IF (GOODHEL(IHEL) .OR. NTRY .LT. 20.OR.USERHEL.NE.-1) THEN
            IF(NTRY.GE.2.AND.POLARIZATIONS(0,0).NE.
     $       -1.AND.(.NOT.M46_IS_BORN_HEL_SELECTED(IHEL))) THEN
              CYCLE
            ENDIF
            T=M46_MATRIX(P ,NHEL(1,IHEL),JC(1))
            IF(POLARIZATIONS(0,0).EQ.-1.OR.M46_IS_BORN_HEL_SELECTED(IHE
     $L)) THEN
              ANS=ANS+T
            ENDIF
            IF (T .NE. 0D0 .AND. .NOT.    GOODHEL(IHEL)) THEN
              GOODHEL(IHEL)=.TRUE.
            ENDIF
          ENDIF
        ENDIF
      ENDDO
      ANS=ANS/DBLE(IDEN)
      IF(USERHEL.NE.-1) THEN
        ANS=ANS*HELAVGFACTOR
      ELSE
        DO J=1,NINITIAL
          IF (POLARIZATIONS(J,0).NE.-1) THEN
            ANS=ANS*BEAMS_HELAVGFACTOR(J)
            ANS=ANS/POLARIZATIONS(J,0)
          ENDIF
        ENDDO
      ENDIF
      END


      REAL*8 FUNCTION M46_MATRIX(P,NHEL,IC)
C     
C     Generated by MadGraph5_aMC@NLO v. 2.6.7, 2019-10-16
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Returns amplitude squared summed/avg over colors
C     for the point with external lines W(0:6,NEXTERNAL)
C     
C     Process: d d~ > h mu+ mu- NP<=1 @1
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=601)
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=5)
      INTEGER    NWAVEFUNCS, NCOLOR
      PARAMETER (NWAVEFUNCS=59, NCOLOR=1)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
      COMPLEX*16 IMAG1
      PARAMETER (IMAG1=(0D0,1D0))
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL), IC(NEXTERNAL)
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,J
      COMPLEX*16 ZTEMP
      REAL*8 DENOM(NCOLOR), CF(NCOLOR,NCOLOR)
      COMPLEX*16 AMP(NGRAPHS), JAMP(NCOLOR)
      COMPLEX*16 W(20,NWAVEFUNCS)
      COMPLEX*16 DUM0,DUM1
      DATA DUM0, DUM1/(0D0, 0D0), (1D0, 0D0)/
C     
C     GLOBAL VARIABLES
C     
      INCLUDE 'coupl.inc'

C     
C     COLOR DATA
C     
      DATA DENOM(1)/1/
      DATA (CF(I,  1),I=  1,  1) /    3/
C     1 T(2,1)
C     ----------
C     BEGIN CODE
C     ----------
      CALL IXXXXX(P(0,1),MDL_MD,NHEL(1),+1*IC(1),W(1,1))
      CALL OXXXXX(P(0,2),MDL_MD,NHEL(2),-1*IC(2),W(1,2))
      CALL SXXXXX(P(0,3),+1*IC(3),W(1,3))
      CALL IXXXXX(P(0,4),MDL_MMU,NHEL(4),-1*IC(4),W(1,4))
      CALL OXXXXX(P(0,5),MDL_MMU,NHEL(5),+1*IC(5),W(1,5))
      CALL FFV2P0_3(W(1,1),W(1,2),GC_619,ZERO,ZERO,W(1,6))
      CALL FFS2_2(W(1,4),W(1,3),GC_756,MDL_MMU,ZERO,W(1,7))
C     Amplitude(s) for diagram number 1
      CALL FFV1_0(W(1,7),W(1,5),W(1,6),GC_4,AMP(1))
      CALL FFV1P0_3(W(1,1),W(1,2),GC_1,ZERO,ZERO,W(1,8))
C     Amplitude(s) for diagram number 2
      CALL FFV2_0(W(1,7),W(1,5),W(1,8),GC_784,AMP(2))
C     Amplitude(s) for diagram number 3
      CALL FFV1_0(W(1,7),W(1,5),W(1,8),GC_4,AMP(3))
C     Amplitude(s) for diagram number 4
      CALL FFV9_0(W(1,7),W(1,5),W(1,8),GC_785,AMP(4))
C     Amplitude(s) for diagram number 5
      CALL FFV2_0(W(1,7),W(1,5),W(1,8),GC_798,AMP(5))
C     Amplitude(s) for diagram number 6
      CALL FFV1_0(W(1,7),W(1,5),W(1,8),GC_333,AMP(6))
C     Amplitude(s) for diagram number 7
      CALL FFV9_0(W(1,7),W(1,5),W(1,8),GC_799,AMP(7))
C     Amplitude(s) for diagram number 8
      CALL FFV1_0(W(1,7),W(1,5),W(1,8),GC_344,AMP(8))
C     Amplitude(s) for diagram number 9
      CALL FFV1_0(W(1,7),W(1,5),W(1,8),GC_354,AMP(9))
C     Amplitude(s) for diagram number 10
      CALL FFV1_0(W(1,7),W(1,5),W(1,8),GC_417,AMP(10))
      CALL FFS1_2(W(1,4),W(1,3),GC_800,MDL_MMU,ZERO,W(1,9))
C     Amplitude(s) for diagram number 11
      CALL FFV1_0(W(1,9),W(1,5),W(1,8),GC_4,AMP(11))
      CALL FFS2_2(W(1,4),W(1,3),GC_801,MDL_MMU,ZERO,W(1,10))
C     Amplitude(s) for diagram number 12
      CALL FFV1_0(W(1,10),W(1,5),W(1,8),GC_4,AMP(12))
      CALL FFS2_2(W(1,4),W(1,3),GC_802,MDL_MMU,ZERO,W(1,11))
C     Amplitude(s) for diagram number 13
      CALL FFV1_0(W(1,11),W(1,5),W(1,8),GC_4,AMP(13))
      CALL FFS2_2(W(1,4),W(1,3),GC_803,MDL_MMU,ZERO,W(1,12))
C     Amplitude(s) for diagram number 14
      CALL FFV1_0(W(1,12),W(1,5),W(1,8),GC_4,AMP(14))
      CALL FFS2_2(W(1,4),W(1,3),GC_804,MDL_MMU,ZERO,W(1,13))
C     Amplitude(s) for diagram number 15
      CALL FFV1_0(W(1,13),W(1,5),W(1,8),GC_4,AMP(15))
      CALL FFS2_2(W(1,4),W(1,3),GC_805,MDL_MMU,ZERO,W(1,14))
C     Amplitude(s) for diagram number 16
      CALL FFV1_0(W(1,14),W(1,5),W(1,8),GC_4,AMP(16))
      CALL FFV9P0_3(W(1,1),W(1,2),GC_620,ZERO,ZERO,W(1,15))
C     Amplitude(s) for diagram number 17
      CALL FFV1_0(W(1,7),W(1,5),W(1,15),GC_4,AMP(17))
      CALL FFV2P0_3(W(1,1),W(1,2),GC_635,ZERO,ZERO,W(1,16))
C     Amplitude(s) for diagram number 18
      CALL FFV1_0(W(1,7),W(1,5),W(1,16),GC_4,AMP(18))
      CALL FFV1P0_3(W(1,1),W(1,2),GC_331,ZERO,ZERO,W(1,17))
C     Amplitude(s) for diagram number 19
      CALL FFV1_0(W(1,7),W(1,5),W(1,17),GC_4,AMP(19))
      CALL FFV9P0_3(W(1,1),W(1,2),GC_636,ZERO,ZERO,W(1,18))
C     Amplitude(s) for diagram number 20
      CALL FFV1_0(W(1,7),W(1,5),W(1,18),GC_4,AMP(20))
      CALL FFV1P0_3(W(1,1),W(1,2),GC_341,ZERO,ZERO,W(1,19))
C     Amplitude(s) for diagram number 21
      CALL FFV1_0(W(1,7),W(1,5),W(1,19),GC_4,AMP(21))
      CALL FFV1P0_3(W(1,1),W(1,2),GC_352,ZERO,ZERO,W(1,20))
C     Amplitude(s) for diagram number 22
      CALL FFV1_0(W(1,7),W(1,5),W(1,20),GC_4,AMP(22))
      CALL FFV1P0_3(W(1,1),W(1,2),GC_415,ZERO,ZERO,W(1,21))
C     Amplitude(s) for diagram number 23
      CALL FFV1_0(W(1,7),W(1,5),W(1,21),GC_4,AMP(23))
      CALL FFV2_3(W(1,1),W(1,2),GC_621,MDL_MZ,MDL_WZ,W(1,22))
C     Amplitude(s) for diagram number 24
      CALL FFV1_3_0(W(1,7),W(1,5),W(1,22),GC_197,GC_136,AMP(24))
      CALL FFV1_3_3(W(1,1),W(1,2),GC_195,GC_136,MDL_MZ,MDL_WZ,W(1,23))
C     Amplitude(s) for diagram number 25
      CALL FFV2_0(W(1,7),W(1,5),W(1,23),GC_786,AMP(25))
C     Amplitude(s) for diagram number 26
      CALL FFV1_3_0(W(1,7),W(1,5),W(1,23),GC_197,GC_136,AMP(26))
C     Amplitude(s) for diagram number 27
      CALL FFV9_0(W(1,7),W(1,5),W(1,23),GC_787,AMP(27))
C     Amplitude(s) for diagram number 28
      CALL FFV6_0(W(1,7),W(1,5),W(1,23),GC_402,AMP(28))
C     Amplitude(s) for diagram number 29
      CALL FFV5_0(W(1,7),W(1,5),W(1,23),GC_403,AMP(29))
C     Amplitude(s) for diagram number 30
      CALL FFV2_0(W(1,7),W(1,5),W(1,23),GC_796,AMP(30))
C     Amplitude(s) for diagram number 31
      CALL FFV9_0(W(1,7),W(1,5),W(1,23),GC_797,AMP(31))
C     Amplitude(s) for diagram number 32
      CALL FFV1_0(W(1,7),W(1,5),W(1,23),GC_338,AMP(32))
C     Amplitude(s) for diagram number 33
      CALL FFV3_0(W(1,7),W(1,5),W(1,23),GC_404,AMP(33))
C     Amplitude(s) for diagram number 34
      CALL FFV3_0(W(1,7),W(1,5),W(1,23),GC_412,AMP(34))
C     Amplitude(s) for diagram number 35
      CALL FFV1_0(W(1,7),W(1,5),W(1,23),GC_427,AMP(35))
C     Amplitude(s) for diagram number 36
      CALL FFV1_0(W(1,7),W(1,5),W(1,23),GC_430,AMP(36))
C     Amplitude(s) for diagram number 37
      CALL FFV1_0(W(1,7),W(1,5),W(1,23),GC_433,AMP(37))
C     Amplitude(s) for diagram number 38
      CALL FFV1_3_0(W(1,9),W(1,5),W(1,23),GC_197,GC_136,AMP(38))
C     Amplitude(s) for diagram number 39
      CALL FFV1_3_0(W(1,10),W(1,5),W(1,23),GC_197,GC_136,AMP(39))
C     Amplitude(s) for diagram number 40
      CALL FFV1_3_0(W(1,11),W(1,5),W(1,23),GC_197,GC_136,AMP(40))
C     Amplitude(s) for diagram number 41
      CALL FFV1_3_0(W(1,12),W(1,5),W(1,23),GC_197,GC_136,AMP(41))
C     Amplitude(s) for diagram number 42
      CALL FFV1_3_0(W(1,13),W(1,5),W(1,23),GC_197,GC_136,AMP(42))
C     Amplitude(s) for diagram number 43
      CALL FFV1_3_0(W(1,14),W(1,5),W(1,23),GC_197,GC_136,AMP(43))
      CALL FFV9_3(W(1,1),W(1,2),GC_622,MDL_MZ,MDL_WZ,W(1,24))
C     Amplitude(s) for diagram number 44
      CALL FFV1_3_0(W(1,7),W(1,5),W(1,24),GC_197,GC_136,AMP(44))
      CALL FFV8_3(W(1,1),W(1,2),GC_399,MDL_MZ,MDL_WZ,W(1,25))
C     Amplitude(s) for diagram number 45
      CALL FFV1_3_0(W(1,7),W(1,5),W(1,25),GC_197,GC_136,AMP(45))
      CALL FFV5_3(W(1,1),W(1,2),GC_398,MDL_MZ,MDL_WZ,W(1,26))
C     Amplitude(s) for diagram number 46
      CALL FFV1_3_0(W(1,7),W(1,5),W(1,26),GC_197,GC_136,AMP(46))
      CALL FFV2_3(W(1,1),W(1,2),GC_633,MDL_MZ,MDL_WZ,W(1,27))
C     Amplitude(s) for diagram number 47
      CALL FFV1_3_0(W(1,7),W(1,5),W(1,27),GC_197,GC_136,AMP(47))
      CALL FFV9_3(W(1,1),W(1,2),GC_634,MDL_MZ,MDL_WZ,W(1,28))
C     Amplitude(s) for diagram number 48
      CALL FFV1_3_0(W(1,7),W(1,5),W(1,28),GC_197,GC_136,AMP(48))
      CALL FFV1_3(W(1,1),W(1,2),GC_335,MDL_MZ,MDL_WZ,W(1,29))
C     Amplitude(s) for diagram number 49
      CALL FFV1_3_0(W(1,7),W(1,5),W(1,29),GC_197,GC_136,AMP(49))
      CALL FFV3_3(W(1,1),W(1,2),GC_405,MDL_MZ,MDL_WZ,W(1,30))
C     Amplitude(s) for diagram number 50
      CALL FFV1_3_0(W(1,7),W(1,5),W(1,30),GC_197,GC_136,AMP(50))
      CALL FFV3_3(W(1,1),W(1,2),GC_407,MDL_MZ,MDL_WZ,W(1,31))
C     Amplitude(s) for diagram number 51
      CALL FFV1_3_0(W(1,7),W(1,5),W(1,31),GC_197,GC_136,AMP(51))
      CALL FFV1_3(W(1,1),W(1,2),GC_425,MDL_MZ,MDL_WZ,W(1,32))
C     Amplitude(s) for diagram number 52
      CALL FFV1_3_0(W(1,7),W(1,5),W(1,32),GC_197,GC_136,AMP(52))
      CALL FFV3_3(W(1,1),W(1,2),GC_409,MDL_MZ,MDL_WZ,W(1,33))
C     Amplitude(s) for diagram number 53
      CALL FFV1_3_0(W(1,7),W(1,5),W(1,33),GC_197,GC_136,AMP(53))
      CALL FFV1_3(W(1,1),W(1,2),GC_428,MDL_MZ,MDL_WZ,W(1,34))
C     Amplitude(s) for diagram number 54
      CALL FFV1_3_0(W(1,7),W(1,5),W(1,34),GC_197,GC_136,AMP(54))
      CALL FFV1_3_3(W(1,1),W(1,2),GC_431,GC_412,MDL_MZ,MDL_WZ,W(1,35))
C     Amplitude(s) for diagram number 55
      CALL FFV1_3_0(W(1,7),W(1,5),W(1,35),GC_197,GC_136,AMP(55))
      CALL FFV1_3PZ1_3(W(1,1),W(1,2),GC_212,GC_183,MDL_MZ1,MDL_WZ1,W(1
     $ ,36))
C     Amplitude(s) for diagram number 56
      CALL FFV1_3_0(W(1,7),W(1,5),W(1,36),GC_214,GC_183,AMP(56))
C     Amplitude(s) for diagram number 57
      CALL FFV1_3_0(W(1,9),W(1,5),W(1,36),GC_214,GC_183,AMP(57))
C     Amplitude(s) for diagram number 58
      CALL FFV1_3_0(W(1,10),W(1,5),W(1,36),GC_214,GC_183,AMP(58))
C     Amplitude(s) for diagram number 59
      CALL FFV1_3_0(W(1,11),W(1,5),W(1,36),GC_214,GC_183,AMP(59))
C     Amplitude(s) for diagram number 60
      CALL FFV1_3_0(W(1,12),W(1,5),W(1,36),GC_214,GC_183,AMP(60))
C     Amplitude(s) for diagram number 61
      CALL FFV1_3_0(W(1,13),W(1,5),W(1,36),GC_214,GC_183,AMP(61))
C     Amplitude(s) for diagram number 62
      CALL FFV1_3_0(W(1,14),W(1,5),W(1,36),GC_214,GC_183,AMP(62))
      CALL FFS2_3(W(1,1),W(1,2),GC_585,MDL_MH,MDL_WH,W(1,37))
C     Amplitude(s) for diagram number 63
      CALL FFS2_0(W(1,7),W(1,5),W(1,37),GC_756,AMP(63))
C     Amplitude(s) for diagram number 64
      CALL FFS1_0(W(1,7),W(1,5),W(1,37),GC_800,AMP(64))
C     Amplitude(s) for diagram number 65
      CALL FFS2_0(W(1,7),W(1,5),W(1,37),GC_801,AMP(65))
C     Amplitude(s) for diagram number 66
      CALL FFS2_0(W(1,7),W(1,5),W(1,37),GC_802,AMP(66))
C     Amplitude(s) for diagram number 67
      CALL FFS2_0(W(1,7),W(1,5),W(1,37),GC_803,AMP(67))
C     Amplitude(s) for diagram number 68
      CALL FFS2_0(W(1,7),W(1,5),W(1,37),GC_804,AMP(68))
C     Amplitude(s) for diagram number 69
      CALL FFS2_0(W(1,7),W(1,5),W(1,37),GC_805,AMP(69))
C     Amplitude(s) for diagram number 70
      CALL FFS2_0(W(1,9),W(1,5),W(1,37),GC_756,AMP(70))
C     Amplitude(s) for diagram number 71
      CALL FFS2_0(W(1,10),W(1,5),W(1,37),GC_756,AMP(71))
C     Amplitude(s) for diagram number 72
      CALL FFS2_0(W(1,11),W(1,5),W(1,37),GC_756,AMP(72))
C     Amplitude(s) for diagram number 73
      CALL FFS2_0(W(1,12),W(1,5),W(1,37),GC_756,AMP(73))
C     Amplitude(s) for diagram number 74
      CALL FFS2_0(W(1,13),W(1,5),W(1,37),GC_756,AMP(74))
C     Amplitude(s) for diagram number 75
      CALL FFS2_0(W(1,14),W(1,5),W(1,37),GC_756,AMP(75))
      CALL FFS1_3(W(1,1),W(1,2),GC_637,MDL_MH,MDL_WH,W(1,38))
C     Amplitude(s) for diagram number 76
      CALL FFS2_0(W(1,7),W(1,5),W(1,38),GC_756,AMP(76))
      CALL FFS2_3(W(1,1),W(1,2),GC_638,MDL_MH,MDL_WH,W(1,39))
C     Amplitude(s) for diagram number 77
      CALL FFS2_0(W(1,7),W(1,5),W(1,39),GC_756,AMP(77))
      CALL FFS2_3(W(1,1),W(1,2),GC_639,MDL_MH,MDL_WH,W(1,40))
C     Amplitude(s) for diagram number 78
      CALL FFS2_0(W(1,7),W(1,5),W(1,40),GC_756,AMP(78))
      CALL FFS2_3(W(1,1),W(1,2),GC_640,MDL_MH,MDL_WH,W(1,41))
C     Amplitude(s) for diagram number 79
      CALL FFS2_0(W(1,7),W(1,5),W(1,41),GC_756,AMP(79))
      CALL FFS2_3(W(1,1),W(1,2),GC_641,MDL_MH,MDL_WH,W(1,42))
C     Amplitude(s) for diagram number 80
      CALL FFS2_0(W(1,7),W(1,5),W(1,42),GC_756,AMP(80))
      CALL FFS2_3(W(1,1),W(1,2),GC_642,MDL_MH,MDL_WH,W(1,43))
C     Amplitude(s) for diagram number 81
      CALL FFS2_0(W(1,7),W(1,5),W(1,43),GC_756,AMP(81))
      CALL FFS2PH1_3(W(1,1),W(1,2),GC_602,MDL_MH1,MDL_WH1,W(1,44))
C     Amplitude(s) for diagram number 82
      CALL FFS2_0(W(1,7),W(1,5),W(1,44),GC_769,AMP(82))
C     Amplitude(s) for diagram number 83
      CALL FFS2_0(W(1,9),W(1,5),W(1,44),GC_769,AMP(83))
C     Amplitude(s) for diagram number 84
      CALL FFS2_0(W(1,10),W(1,5),W(1,44),GC_769,AMP(84))
C     Amplitude(s) for diagram number 85
      CALL FFS2_0(W(1,11),W(1,5),W(1,44),GC_769,AMP(85))
C     Amplitude(s) for diagram number 86
      CALL FFS2_0(W(1,12),W(1,5),W(1,44),GC_769,AMP(86))
C     Amplitude(s) for diagram number 87
      CALL FFS2_0(W(1,13),W(1,5),W(1,44),GC_769,AMP(87))
C     Amplitude(s) for diagram number 88
      CALL FFS2_0(W(1,14),W(1,5),W(1,44),GC_769,AMP(88))
      CALL FFS2_1(W(1,5),W(1,3),GC_756,MDL_MMU,ZERO,W(1,14))
C     Amplitude(s) for diagram number 89
      CALL FFV1_0(W(1,4),W(1,14),W(1,6),GC_4,AMP(89))
C     Amplitude(s) for diagram number 90
      CALL FFV2_0(W(1,4),W(1,14),W(1,8),GC_784,AMP(90))
C     Amplitude(s) for diagram number 91
      CALL FFV1_0(W(1,4),W(1,14),W(1,8),GC_4,AMP(91))
C     Amplitude(s) for diagram number 92
      CALL FFV9_0(W(1,4),W(1,14),W(1,8),GC_785,AMP(92))
C     Amplitude(s) for diagram number 93
      CALL FFV2_0(W(1,4),W(1,14),W(1,8),GC_798,AMP(93))
C     Amplitude(s) for diagram number 94
      CALL FFV1_0(W(1,4),W(1,14),W(1,8),GC_333,AMP(94))
C     Amplitude(s) for diagram number 95
      CALL FFV9_0(W(1,4),W(1,14),W(1,8),GC_799,AMP(95))
C     Amplitude(s) for diagram number 96
      CALL FFV1_0(W(1,4),W(1,14),W(1,8),GC_344,AMP(96))
C     Amplitude(s) for diagram number 97
      CALL FFV1_0(W(1,4),W(1,14),W(1,8),GC_354,AMP(97))
C     Amplitude(s) for diagram number 98
      CALL FFV1_0(W(1,4),W(1,14),W(1,8),GC_417,AMP(98))
      CALL FFS1_1(W(1,5),W(1,3),GC_800,MDL_MMU,ZERO,W(1,13))
C     Amplitude(s) for diagram number 99
      CALL FFV1_0(W(1,4),W(1,13),W(1,8),GC_4,AMP(99))
      CALL FFS2_1(W(1,5),W(1,3),GC_801,MDL_MMU,ZERO,W(1,12))
C     Amplitude(s) for diagram number 100
      CALL FFV1_0(W(1,4),W(1,12),W(1,8),GC_4,AMP(100))
      CALL FFS2_1(W(1,5),W(1,3),GC_802,MDL_MMU,ZERO,W(1,11))
C     Amplitude(s) for diagram number 101
      CALL FFV1_0(W(1,4),W(1,11),W(1,8),GC_4,AMP(101))
      CALL FFS2_1(W(1,5),W(1,3),GC_803,MDL_MMU,ZERO,W(1,10))
C     Amplitude(s) for diagram number 102
      CALL FFV1_0(W(1,4),W(1,10),W(1,8),GC_4,AMP(102))
      CALL FFS2_1(W(1,5),W(1,3),GC_804,MDL_MMU,ZERO,W(1,9))
C     Amplitude(s) for diagram number 103
      CALL FFV1_0(W(1,4),W(1,9),W(1,8),GC_4,AMP(103))
      CALL FFS2_1(W(1,5),W(1,3),GC_805,MDL_MMU,ZERO,W(1,7))
C     Amplitude(s) for diagram number 104
      CALL FFV1_0(W(1,4),W(1,7),W(1,8),GC_4,AMP(104))
C     Amplitude(s) for diagram number 105
      CALL FFV1_0(W(1,4),W(1,14),W(1,15),GC_4,AMP(105))
C     Amplitude(s) for diagram number 106
      CALL FFV1_0(W(1,4),W(1,14),W(1,16),GC_4,AMP(106))
C     Amplitude(s) for diagram number 107
      CALL FFV1_0(W(1,4),W(1,14),W(1,17),GC_4,AMP(107))
C     Amplitude(s) for diagram number 108
      CALL FFV1_0(W(1,4),W(1,14),W(1,18),GC_4,AMP(108))
C     Amplitude(s) for diagram number 109
      CALL FFV1_0(W(1,4),W(1,14),W(1,19),GC_4,AMP(109))
C     Amplitude(s) for diagram number 110
      CALL FFV1_0(W(1,4),W(1,14),W(1,20),GC_4,AMP(110))
C     Amplitude(s) for diagram number 111
      CALL FFV1_0(W(1,4),W(1,14),W(1,21),GC_4,AMP(111))
C     Amplitude(s) for diagram number 112
      CALL FFV1_3_0(W(1,4),W(1,14),W(1,22),GC_197,GC_136,AMP(112))
C     Amplitude(s) for diagram number 113
      CALL FFV2_0(W(1,4),W(1,14),W(1,23),GC_786,AMP(113))
C     Amplitude(s) for diagram number 114
      CALL FFV1_3_0(W(1,4),W(1,14),W(1,23),GC_197,GC_136,AMP(114))
C     Amplitude(s) for diagram number 115
      CALL FFV9_0(W(1,4),W(1,14),W(1,23),GC_787,AMP(115))
C     Amplitude(s) for diagram number 116
      CALL FFV6_0(W(1,4),W(1,14),W(1,23),GC_402,AMP(116))
C     Amplitude(s) for diagram number 117
      CALL FFV5_0(W(1,4),W(1,14),W(1,23),GC_403,AMP(117))
C     Amplitude(s) for diagram number 118
      CALL FFV2_0(W(1,4),W(1,14),W(1,23),GC_796,AMP(118))
C     Amplitude(s) for diagram number 119
      CALL FFV9_0(W(1,4),W(1,14),W(1,23),GC_797,AMP(119))
C     Amplitude(s) for diagram number 120
      CALL FFV1_0(W(1,4),W(1,14),W(1,23),GC_338,AMP(120))
C     Amplitude(s) for diagram number 121
      CALL FFV3_0(W(1,4),W(1,14),W(1,23),GC_404,AMP(121))
C     Amplitude(s) for diagram number 122
      CALL FFV3_0(W(1,4),W(1,14),W(1,23),GC_412,AMP(122))
C     Amplitude(s) for diagram number 123
      CALL FFV1_0(W(1,4),W(1,14),W(1,23),GC_427,AMP(123))
C     Amplitude(s) for diagram number 124
      CALL FFV1_0(W(1,4),W(1,14),W(1,23),GC_430,AMP(124))
C     Amplitude(s) for diagram number 125
      CALL FFV1_0(W(1,4),W(1,14),W(1,23),GC_433,AMP(125))
C     Amplitude(s) for diagram number 126
      CALL FFV1_3_0(W(1,4),W(1,13),W(1,23),GC_197,GC_136,AMP(126))
C     Amplitude(s) for diagram number 127
      CALL FFV1_3_0(W(1,4),W(1,12),W(1,23),GC_197,GC_136,AMP(127))
C     Amplitude(s) for diagram number 128
      CALL FFV1_3_0(W(1,4),W(1,11),W(1,23),GC_197,GC_136,AMP(128))
C     Amplitude(s) for diagram number 129
      CALL FFV1_3_0(W(1,4),W(1,10),W(1,23),GC_197,GC_136,AMP(129))
C     Amplitude(s) for diagram number 130
      CALL FFV1_3_0(W(1,4),W(1,9),W(1,23),GC_197,GC_136,AMP(130))
C     Amplitude(s) for diagram number 131
      CALL FFV1_3_0(W(1,4),W(1,7),W(1,23),GC_197,GC_136,AMP(131))
C     Amplitude(s) for diagram number 132
      CALL FFV1_3_0(W(1,4),W(1,14),W(1,24),GC_197,GC_136,AMP(132))
C     Amplitude(s) for diagram number 133
      CALL FFV1_3_0(W(1,4),W(1,14),W(1,25),GC_197,GC_136,AMP(133))
C     Amplitude(s) for diagram number 134
      CALL FFV1_3_0(W(1,4),W(1,14),W(1,26),GC_197,GC_136,AMP(134))
C     Amplitude(s) for diagram number 135
      CALL FFV1_3_0(W(1,4),W(1,14),W(1,27),GC_197,GC_136,AMP(135))
C     Amplitude(s) for diagram number 136
      CALL FFV1_3_0(W(1,4),W(1,14),W(1,28),GC_197,GC_136,AMP(136))
C     Amplitude(s) for diagram number 137
      CALL FFV1_3_0(W(1,4),W(1,14),W(1,29),GC_197,GC_136,AMP(137))
C     Amplitude(s) for diagram number 138
      CALL FFV1_3_0(W(1,4),W(1,14),W(1,30),GC_197,GC_136,AMP(138))
C     Amplitude(s) for diagram number 139
      CALL FFV1_3_0(W(1,4),W(1,14),W(1,31),GC_197,GC_136,AMP(139))
C     Amplitude(s) for diagram number 140
      CALL FFV1_3_0(W(1,4),W(1,14),W(1,32),GC_197,GC_136,AMP(140))
C     Amplitude(s) for diagram number 141
      CALL FFV1_3_0(W(1,4),W(1,14),W(1,33),GC_197,GC_136,AMP(141))
C     Amplitude(s) for diagram number 142
      CALL FFV1_3_0(W(1,4),W(1,14),W(1,34),GC_197,GC_136,AMP(142))
C     Amplitude(s) for diagram number 143
      CALL FFV1_3_0(W(1,4),W(1,14),W(1,35),GC_197,GC_136,AMP(143))
C     Amplitude(s) for diagram number 144
      CALL FFV1_3_0(W(1,4),W(1,14),W(1,36),GC_214,GC_183,AMP(144))
C     Amplitude(s) for diagram number 145
      CALL FFV1_3_0(W(1,4),W(1,13),W(1,36),GC_214,GC_183,AMP(145))
C     Amplitude(s) for diagram number 146
      CALL FFV1_3_0(W(1,4),W(1,12),W(1,36),GC_214,GC_183,AMP(146))
C     Amplitude(s) for diagram number 147
      CALL FFV1_3_0(W(1,4),W(1,11),W(1,36),GC_214,GC_183,AMP(147))
C     Amplitude(s) for diagram number 148
      CALL FFV1_3_0(W(1,4),W(1,10),W(1,36),GC_214,GC_183,AMP(148))
C     Amplitude(s) for diagram number 149
      CALL FFV1_3_0(W(1,4),W(1,9),W(1,36),GC_214,GC_183,AMP(149))
C     Amplitude(s) for diagram number 150
      CALL FFV1_3_0(W(1,4),W(1,7),W(1,36),GC_214,GC_183,AMP(150))
C     Amplitude(s) for diagram number 151
      CALL FFS2_0(W(1,4),W(1,14),W(1,37),GC_756,AMP(151))
C     Amplitude(s) for diagram number 152
      CALL FFS1_0(W(1,4),W(1,14),W(1,37),GC_800,AMP(152))
C     Amplitude(s) for diagram number 153
      CALL FFS2_0(W(1,4),W(1,14),W(1,37),GC_801,AMP(153))
C     Amplitude(s) for diagram number 154
      CALL FFS2_0(W(1,4),W(1,14),W(1,37),GC_802,AMP(154))
C     Amplitude(s) for diagram number 155
      CALL FFS2_0(W(1,4),W(1,14),W(1,37),GC_803,AMP(155))
C     Amplitude(s) for diagram number 156
      CALL FFS2_0(W(1,4),W(1,14),W(1,37),GC_804,AMP(156))
C     Amplitude(s) for diagram number 157
      CALL FFS2_0(W(1,4),W(1,14),W(1,37),GC_805,AMP(157))
C     Amplitude(s) for diagram number 158
      CALL FFS2_0(W(1,4),W(1,13),W(1,37),GC_756,AMP(158))
C     Amplitude(s) for diagram number 159
      CALL FFS2_0(W(1,4),W(1,12),W(1,37),GC_756,AMP(159))
C     Amplitude(s) for diagram number 160
      CALL FFS2_0(W(1,4),W(1,11),W(1,37),GC_756,AMP(160))
C     Amplitude(s) for diagram number 161
      CALL FFS2_0(W(1,4),W(1,10),W(1,37),GC_756,AMP(161))
C     Amplitude(s) for diagram number 162
      CALL FFS2_0(W(1,4),W(1,9),W(1,37),GC_756,AMP(162))
C     Amplitude(s) for diagram number 163
      CALL FFS2_0(W(1,4),W(1,7),W(1,37),GC_756,AMP(163))
C     Amplitude(s) for diagram number 164
      CALL FFS2_0(W(1,4),W(1,14),W(1,38),GC_756,AMP(164))
C     Amplitude(s) for diagram number 165
      CALL FFS2_0(W(1,4),W(1,14),W(1,39),GC_756,AMP(165))
C     Amplitude(s) for diagram number 166
      CALL FFS2_0(W(1,4),W(1,14),W(1,40),GC_756,AMP(166))
C     Amplitude(s) for diagram number 167
      CALL FFS2_0(W(1,4),W(1,14),W(1,41),GC_756,AMP(167))
C     Amplitude(s) for diagram number 168
      CALL FFS2_0(W(1,4),W(1,14),W(1,42),GC_756,AMP(168))
C     Amplitude(s) for diagram number 169
      CALL FFS2_0(W(1,4),W(1,14),W(1,43),GC_756,AMP(169))
C     Amplitude(s) for diagram number 170
      CALL FFS2_0(W(1,4),W(1,14),W(1,44),GC_769,AMP(170))
C     Amplitude(s) for diagram number 171
      CALL FFS2_0(W(1,4),W(1,13),W(1,44),GC_769,AMP(171))
C     Amplitude(s) for diagram number 172
      CALL FFS2_0(W(1,4),W(1,12),W(1,44),GC_769,AMP(172))
C     Amplitude(s) for diagram number 173
      CALL FFS2_0(W(1,4),W(1,11),W(1,44),GC_769,AMP(173))
C     Amplitude(s) for diagram number 174
      CALL FFS2_0(W(1,4),W(1,10),W(1,44),GC_769,AMP(174))
C     Amplitude(s) for diagram number 175
      CALL FFS2_0(W(1,4),W(1,9),W(1,44),GC_769,AMP(175))
C     Amplitude(s) for diagram number 176
      CALL FFS2_0(W(1,4),W(1,7),W(1,44),GC_769,AMP(176))
      CALL FFV1P0_3(W(1,4),W(1,5),GC_4,ZERO,ZERO,W(1,7))
C     Amplitude(s) for diagram number 177
      CALL VVS4_0(W(1,6),W(1,7),W(1,3),GC_223,AMP(177))
      CALL FFV1_3_3(W(1,4),W(1,5),GC_197,GC_136,MDL_MZ,MDL_WZ,W(1,9))
C     Amplitude(s) for diagram number 178
      CALL VVS4_0(W(1,6),W(1,9),W(1,3),GC_227,AMP(178))
      CALL FFV1_3PZ1_3(W(1,4),W(1,5),GC_214,GC_183,MDL_MZ1,MDL_WZ1,W(1
     $ ,10))
C     Amplitude(s) for diagram number 179
      CALL VVS4_0(W(1,6),W(1,10),W(1,3),GC_245,AMP(179))
      CALL FFV2P0_3(W(1,4),W(1,5),GC_784,ZERO,ZERO,W(1,6))
C     Amplitude(s) for diagram number 180
      CALL VVS4_0(W(1,8),W(1,6),W(1,3),GC_223,AMP(180))
C     Amplitude(s) for diagram number 181
      CALL VVS4_0(W(1,8),W(1,7),W(1,3),GC_223,AMP(181))
C     Amplitude(s) for diagram number 182
      CALL VVS2_0(W(1,8),W(1,7),W(1,3),GC_269,AMP(182))
C     Amplitude(s) for diagram number 183
      CALL VVS4_0(W(1,8),W(1,7),W(1,3),GC_268,AMP(183))
C     Amplitude(s) for diagram number 184
      CALL VVS2_0(W(1,8),W(1,7),W(1,3),GC_324,AMP(184))
C     Amplitude(s) for diagram number 185
      CALL VVS4_0(W(1,8),W(1,7),W(1,3),GC_321,AMP(185))
C     Amplitude(s) for diagram number 186
      CALL VVS2_0(W(1,8),W(1,7),W(1,3),GC_329,AMP(186))
C     Amplitude(s) for diagram number 187
      CALL VVS4_0(W(1,8),W(1,7),W(1,3),GC_328,AMP(187))
      CALL FFV9P0_3(W(1,4),W(1,5),GC_785,ZERO,ZERO,W(1,11))
C     Amplitude(s) for diagram number 188
      CALL VVS4_0(W(1,8),W(1,11),W(1,3),GC_223,AMP(188))
      CALL FFV2P0_3(W(1,4),W(1,5),GC_798,ZERO,ZERO,W(1,12))
C     Amplitude(s) for diagram number 189
      CALL VVS4_0(W(1,8),W(1,12),W(1,3),GC_223,AMP(189))
      CALL FFV1P0_3(W(1,4),W(1,5),GC_333,ZERO,ZERO,W(1,13))
C     Amplitude(s) for diagram number 190
      CALL VVS4_0(W(1,8),W(1,13),W(1,3),GC_223,AMP(190))
      CALL FFV9P0_3(W(1,4),W(1,5),GC_799,ZERO,ZERO,W(1,14))
C     Amplitude(s) for diagram number 191
      CALL VVS4_0(W(1,8),W(1,14),W(1,3),GC_223,AMP(191))
      CALL FFV1P0_3(W(1,4),W(1,5),GC_344,ZERO,ZERO,W(1,45))
C     Amplitude(s) for diagram number 192
      CALL VVS4_0(W(1,8),W(1,45),W(1,3),GC_223,AMP(192))
      CALL FFV1P0_3(W(1,4),W(1,5),GC_354,ZERO,ZERO,W(1,46))
C     Amplitude(s) for diagram number 193
      CALL VVS4_0(W(1,8),W(1,46),W(1,3),GC_223,AMP(193))
      CALL FFV1P0_3(W(1,4),W(1,5),GC_417,ZERO,ZERO,W(1,47))
C     Amplitude(s) for diagram number 194
      CALL VVS4_0(W(1,8),W(1,47),W(1,3),GC_223,AMP(194))
      CALL FFV2_3(W(1,4),W(1,5),GC_786,MDL_MZ,MDL_WZ,W(1,48))
C     Amplitude(s) for diagram number 195
      CALL VVS4_0(W(1,8),W(1,48),W(1,3),GC_227,AMP(195))
C     Amplitude(s) for diagram number 196
      CALL VVS4_0(W(1,8),W(1,9),W(1,3),GC_227,AMP(196))
C     Amplitude(s) for diagram number 197
      CALL VVS1_0(W(1,8),W(1,9),W(1,3),GC_448,AMP(197))
C     Amplitude(s) for diagram number 198
      CALL VVS4_0(W(1,8),W(1,9),W(1,3),GC_447,AMP(198))
C     Amplitude(s) for diagram number 199
      CALL VVS1_0(W(1,8),W(1,9),W(1,3),GC_319,AMP(199))
C     Amplitude(s) for diagram number 200
      CALL VVS4_0(W(1,8),W(1,9),W(1,3),GC_318,AMP(200))
C     Amplitude(s) for diagram number 201
      CALL VVS1_0(W(1,8),W(1,9),W(1,3),GC_325,AMP(201))
C     Amplitude(s) for diagram number 202
      CALL VVS4_0(W(1,8),W(1,9),W(1,3),GC_320,AMP(202))
      CALL FFV9_3(W(1,4),W(1,5),GC_787,MDL_MZ,MDL_WZ,W(1,49))
C     Amplitude(s) for diagram number 203
      CALL VVS4_0(W(1,8),W(1,49),W(1,3),GC_227,AMP(203))
      CALL FFV6_3(W(1,4),W(1,5),GC_402,MDL_MZ,MDL_WZ,W(1,50))
C     Amplitude(s) for diagram number 204
      CALL VVS4_0(W(1,8),W(1,50),W(1,3),GC_227,AMP(204))
      CALL FFV5_3(W(1,4),W(1,5),GC_403,MDL_MZ,MDL_WZ,W(1,51))
C     Amplitude(s) for diagram number 205
      CALL VVS4_0(W(1,8),W(1,51),W(1,3),GC_227,AMP(205))
      CALL FFV2_3(W(1,4),W(1,5),GC_796,MDL_MZ,MDL_WZ,W(1,52))
C     Amplitude(s) for diagram number 206
      CALL VVS4_0(W(1,8),W(1,52),W(1,3),GC_227,AMP(206))
      CALL FFV9_3(W(1,4),W(1,5),GC_797,MDL_MZ,MDL_WZ,W(1,53))
C     Amplitude(s) for diagram number 207
      CALL VVS4_0(W(1,8),W(1,53),W(1,3),GC_227,AMP(207))
      CALL FFV1_3(W(1,4),W(1,5),GC_338,MDL_MZ,MDL_WZ,W(1,54))
C     Amplitude(s) for diagram number 208
      CALL VVS4_0(W(1,8),W(1,54),W(1,3),GC_227,AMP(208))
      CALL FFV3_3(W(1,4),W(1,5),GC_404,MDL_MZ,MDL_WZ,W(1,55))
C     Amplitude(s) for diagram number 209
      CALL VVS4_0(W(1,8),W(1,55),W(1,3),GC_227,AMP(209))
      CALL FFV3_3(W(1,4),W(1,5),GC_412,MDL_MZ,MDL_WZ,W(1,56))
C     Amplitude(s) for diagram number 210
      CALL VVS4_0(W(1,8),W(1,56),W(1,3),GC_227,AMP(210))
      CALL FFV1_3(W(1,4),W(1,5),GC_427,MDL_MZ,MDL_WZ,W(1,57))
C     Amplitude(s) for diagram number 211
      CALL VVS4_0(W(1,8),W(1,57),W(1,3),GC_227,AMP(211))
      CALL FFV1_3(W(1,4),W(1,5),GC_430,MDL_MZ,MDL_WZ,W(1,58))
C     Amplitude(s) for diagram number 212
      CALL VVS4_0(W(1,8),W(1,58),W(1,3),GC_227,AMP(212))
      CALL FFV1_3(W(1,4),W(1,5),GC_433,MDL_MZ,MDL_WZ,W(1,59))
C     Amplitude(s) for diagram number 213
      CALL VVS4_0(W(1,8),W(1,59),W(1,3),GC_227,AMP(213))
C     Amplitude(s) for diagram number 214
      CALL VVS4_0(W(1,8),W(1,10),W(1,3),GC_245,AMP(214))
C     Amplitude(s) for diagram number 215
      CALL VVS4_0(W(1,15),W(1,7),W(1,3),GC_223,AMP(215))
C     Amplitude(s) for diagram number 216
      CALL VVS4_0(W(1,15),W(1,9),W(1,3),GC_227,AMP(216))
C     Amplitude(s) for diagram number 217
      CALL VVS4_0(W(1,15),W(1,10),W(1,3),GC_245,AMP(217))
C     Amplitude(s) for diagram number 218
      CALL VVS4_0(W(1,16),W(1,7),W(1,3),GC_223,AMP(218))
C     Amplitude(s) for diagram number 219
      CALL VVS4_0(W(1,16),W(1,9),W(1,3),GC_227,AMP(219))
C     Amplitude(s) for diagram number 220
      CALL VVS4_0(W(1,16),W(1,10),W(1,3),GC_245,AMP(220))
C     Amplitude(s) for diagram number 221
      CALL VVS4_0(W(1,17),W(1,7),W(1,3),GC_223,AMP(221))
C     Amplitude(s) for diagram number 222
      CALL VVS4_0(W(1,17),W(1,9),W(1,3),GC_227,AMP(222))
C     Amplitude(s) for diagram number 223
      CALL VVS4_0(W(1,17),W(1,10),W(1,3),GC_245,AMP(223))
C     Amplitude(s) for diagram number 224
      CALL VVS4_0(W(1,18),W(1,7),W(1,3),GC_223,AMP(224))
C     Amplitude(s) for diagram number 225
      CALL VVS4_0(W(1,18),W(1,9),W(1,3),GC_227,AMP(225))
C     Amplitude(s) for diagram number 226
      CALL VVS4_0(W(1,18),W(1,10),W(1,3),GC_245,AMP(226))
C     Amplitude(s) for diagram number 227
      CALL VVS4_0(W(1,19),W(1,7),W(1,3),GC_223,AMP(227))
C     Amplitude(s) for diagram number 228
      CALL VVS4_0(W(1,19),W(1,9),W(1,3),GC_227,AMP(228))
C     Amplitude(s) for diagram number 229
      CALL VVS4_0(W(1,19),W(1,10),W(1,3),GC_245,AMP(229))
C     Amplitude(s) for diagram number 230
      CALL VVS4_0(W(1,20),W(1,7),W(1,3),GC_223,AMP(230))
C     Amplitude(s) for diagram number 231
      CALL VVS4_0(W(1,20),W(1,9),W(1,3),GC_227,AMP(231))
C     Amplitude(s) for diagram number 232
      CALL VVS4_0(W(1,20),W(1,10),W(1,3),GC_245,AMP(232))
C     Amplitude(s) for diagram number 233
      CALL VVS4_0(W(1,21),W(1,7),W(1,3),GC_223,AMP(233))
C     Amplitude(s) for diagram number 234
      CALL VVS4_0(W(1,21),W(1,9),W(1,3),GC_227,AMP(234))
C     Amplitude(s) for diagram number 235
      CALL VVS4_0(W(1,21),W(1,10),W(1,3),GC_245,AMP(235))
C     Amplitude(s) for diagram number 236
      CALL VVS4_0(W(1,7),W(1,22),W(1,3),GC_227,AMP(236))
C     Amplitude(s) for diagram number 237
      CALL VVS3_0(W(1,22),W(1,9),W(1,3),GC_284,AMP(237))
C     Amplitude(s) for diagram number 238
      CALL VVS3_0(W(1,22),W(1,10),W(1,3),GC_289,AMP(238))
C     Amplitude(s) for diagram number 239
      CALL VVS4_0(W(1,6),W(1,23),W(1,3),GC_227,AMP(239))
C     Amplitude(s) for diagram number 240
      CALL VVS4_0(W(1,7),W(1,23),W(1,3),GC_227,AMP(240))
C     Amplitude(s) for diagram number 241
      CALL VVS1_0(W(1,7),W(1,23),W(1,3),GC_448,AMP(241))
C     Amplitude(s) for diagram number 242
      CALL VVS4_0(W(1,7),W(1,23),W(1,3),GC_447,AMP(242))
C     Amplitude(s) for diagram number 243
      CALL VVS1_0(W(1,7),W(1,23),W(1,3),GC_319,AMP(243))
C     Amplitude(s) for diagram number 244
      CALL VVS4_0(W(1,7),W(1,23),W(1,3),GC_318,AMP(244))
C     Amplitude(s) for diagram number 245
      CALL VVS1_0(W(1,7),W(1,23),W(1,3),GC_325,AMP(245))
C     Amplitude(s) for diagram number 246
      CALL VVS4_0(W(1,7),W(1,23),W(1,3),GC_320,AMP(246))
C     Amplitude(s) for diagram number 247
      CALL VVS4_0(W(1,11),W(1,23),W(1,3),GC_227,AMP(247))
C     Amplitude(s) for diagram number 248
      CALL VVS4_0(W(1,12),W(1,23),W(1,3),GC_227,AMP(248))
C     Amplitude(s) for diagram number 249
      CALL VVS4_0(W(1,13),W(1,23),W(1,3),GC_227,AMP(249))
C     Amplitude(s) for diagram number 250
      CALL VVS4_0(W(1,14),W(1,23),W(1,3),GC_227,AMP(250))
C     Amplitude(s) for diagram number 251
      CALL VVS4_0(W(1,45),W(1,23),W(1,3),GC_227,AMP(251))
C     Amplitude(s) for diagram number 252
      CALL VVS4_0(W(1,46),W(1,23),W(1,3),GC_227,AMP(252))
C     Amplitude(s) for diagram number 253
      CALL VVS4_0(W(1,47),W(1,23),W(1,3),GC_227,AMP(253))
C     Amplitude(s) for diagram number 254
      CALL VVS3_0(W(1,23),W(1,48),W(1,3),GC_284,AMP(254))
C     Amplitude(s) for diagram number 255
      CALL VVS3_0(W(1,23),W(1,9),W(1,3),GC_284,AMP(255))
C     Amplitude(s) for diagram number 256
      CALL VVS2_0(W(1,23),W(1,9),W(1,3),GC_271,AMP(256))
C     Amplitude(s) for diagram number 257
      CALL VVS4_0(W(1,23),W(1,9),W(1,3),GC_270,AMP(257))
C     Amplitude(s) for diagram number 258
      CALL VVS3_0(W(1,23),W(1,9),W(1,3),GC_443,AMP(258))
C     Amplitude(s) for diagram number 259
      CALL VVS2_0(W(1,23),W(1,9),W(1,3),GC_323,AMP(259))
C     Amplitude(s) for diagram number 260
      CALL VVS4_0(W(1,23),W(1,9),W(1,3),GC_322,AMP(260))
C     Amplitude(s) for diagram number 261
      CALL VVS3_0(W(1,23),W(1,9),W(1,3),GC_444,AMP(261))
C     Amplitude(s) for diagram number 262
      CALL VVS2_0(W(1,23),W(1,9),W(1,3),GC_327,AMP(262))
C     Amplitude(s) for diagram number 263
      CALL VVS4_0(W(1,23),W(1,9),W(1,3),GC_326,AMP(263))
C     Amplitude(s) for diagram number 264
      CALL VVS3_0(W(1,23),W(1,9),W(1,3),GC_445,AMP(264))
C     Amplitude(s) for diagram number 265
      CALL VVS3_0(W(1,23),W(1,9),W(1,3),GC_446,AMP(265))
C     Amplitude(s) for diagram number 266
      CALL VVS3_0(W(1,23),W(1,49),W(1,3),GC_284,AMP(266))
C     Amplitude(s) for diagram number 267
      CALL VVS3_0(W(1,23),W(1,50),W(1,3),GC_284,AMP(267))
C     Amplitude(s) for diagram number 268
      CALL VVS3_0(W(1,23),W(1,51),W(1,3),GC_284,AMP(268))
C     Amplitude(s) for diagram number 269
      CALL VVS3_0(W(1,23),W(1,52),W(1,3),GC_284,AMP(269))
C     Amplitude(s) for diagram number 270
      CALL VVS3_0(W(1,23),W(1,53),W(1,3),GC_284,AMP(270))
C     Amplitude(s) for diagram number 271
      CALL VVS3_0(W(1,23),W(1,54),W(1,3),GC_284,AMP(271))
C     Amplitude(s) for diagram number 272
      CALL VVS3_0(W(1,23),W(1,55),W(1,3),GC_284,AMP(272))
C     Amplitude(s) for diagram number 273
      CALL VVS3_0(W(1,23),W(1,56),W(1,3),GC_284,AMP(273))
C     Amplitude(s) for diagram number 274
      CALL VVS3_0(W(1,23),W(1,57),W(1,3),GC_284,AMP(274))
C     Amplitude(s) for diagram number 275
      CALL VVS3_0(W(1,23),W(1,58),W(1,3),GC_284,AMP(275))
C     Amplitude(s) for diagram number 276
      CALL VVS3_0(W(1,23),W(1,59),W(1,3),GC_284,AMP(276))
C     Amplitude(s) for diagram number 277
      CALL VVS3_0(W(1,23),W(1,10),W(1,3),GC_289,AMP(277))
C     Amplitude(s) for diagram number 278
      CALL VVS4_0(W(1,7),W(1,24),W(1,3),GC_227,AMP(278))
C     Amplitude(s) for diagram number 279
      CALL VVS3_0(W(1,24),W(1,9),W(1,3),GC_284,AMP(279))
C     Amplitude(s) for diagram number 280
      CALL VVS3_0(W(1,24),W(1,10),W(1,3),GC_289,AMP(280))
C     Amplitude(s) for diagram number 281
      CALL VVS4_0(W(1,7),W(1,25),W(1,3),GC_227,AMP(281))
C     Amplitude(s) for diagram number 282
      CALL VVS3_0(W(1,25),W(1,9),W(1,3),GC_284,AMP(282))
C     Amplitude(s) for diagram number 283
      CALL VVS3_0(W(1,25),W(1,10),W(1,3),GC_289,AMP(283))
C     Amplitude(s) for diagram number 284
      CALL VVS4_0(W(1,7),W(1,26),W(1,3),GC_227,AMP(284))
C     Amplitude(s) for diagram number 285
      CALL VVS3_0(W(1,26),W(1,9),W(1,3),GC_284,AMP(285))
C     Amplitude(s) for diagram number 286
      CALL VVS3_0(W(1,26),W(1,10),W(1,3),GC_289,AMP(286))
C     Amplitude(s) for diagram number 287
      CALL VVS4_0(W(1,7),W(1,27),W(1,3),GC_227,AMP(287))
C     Amplitude(s) for diagram number 288
      CALL VVS3_0(W(1,27),W(1,9),W(1,3),GC_284,AMP(288))
C     Amplitude(s) for diagram number 289
      CALL VVS3_0(W(1,27),W(1,10),W(1,3),GC_289,AMP(289))
C     Amplitude(s) for diagram number 290
      CALL VVS4_0(W(1,7),W(1,28),W(1,3),GC_227,AMP(290))
C     Amplitude(s) for diagram number 291
      CALL VVS3_0(W(1,28),W(1,9),W(1,3),GC_284,AMP(291))
C     Amplitude(s) for diagram number 292
      CALL VVS3_0(W(1,28),W(1,10),W(1,3),GC_289,AMP(292))
C     Amplitude(s) for diagram number 293
      CALL VVS4_0(W(1,7),W(1,29),W(1,3),GC_227,AMP(293))
C     Amplitude(s) for diagram number 294
      CALL VVS3_0(W(1,29),W(1,9),W(1,3),GC_284,AMP(294))
C     Amplitude(s) for diagram number 295
      CALL VVS3_0(W(1,29),W(1,10),W(1,3),GC_289,AMP(295))
C     Amplitude(s) for diagram number 296
      CALL VVS4_0(W(1,7),W(1,30),W(1,3),GC_227,AMP(296))
C     Amplitude(s) for diagram number 297
      CALL VVS3_0(W(1,30),W(1,9),W(1,3),GC_284,AMP(297))
C     Amplitude(s) for diagram number 298
      CALL VVS3_0(W(1,30),W(1,10),W(1,3),GC_289,AMP(298))
C     Amplitude(s) for diagram number 299
      CALL VVS4_0(W(1,7),W(1,31),W(1,3),GC_227,AMP(299))
C     Amplitude(s) for diagram number 300
      CALL VVS3_0(W(1,31),W(1,9),W(1,3),GC_284,AMP(300))
C     Amplitude(s) for diagram number 301
      CALL VVS3_0(W(1,31),W(1,10),W(1,3),GC_289,AMP(301))
C     Amplitude(s) for diagram number 302
      CALL VVS4_0(W(1,7),W(1,32),W(1,3),GC_227,AMP(302))
C     Amplitude(s) for diagram number 303
      CALL VVS3_0(W(1,32),W(1,9),W(1,3),GC_284,AMP(303))
C     Amplitude(s) for diagram number 304
      CALL VVS3_0(W(1,32),W(1,10),W(1,3),GC_289,AMP(304))
C     Amplitude(s) for diagram number 305
      CALL VVS4_0(W(1,7),W(1,33),W(1,3),GC_227,AMP(305))
C     Amplitude(s) for diagram number 306
      CALL VVS3_0(W(1,33),W(1,9),W(1,3),GC_284,AMP(306))
C     Amplitude(s) for diagram number 307
      CALL VVS3_0(W(1,33),W(1,10),W(1,3),GC_289,AMP(307))
C     Amplitude(s) for diagram number 308
      CALL VVS4_0(W(1,7),W(1,34),W(1,3),GC_227,AMP(308))
C     Amplitude(s) for diagram number 309
      CALL VVS3_0(W(1,34),W(1,9),W(1,3),GC_284,AMP(309))
C     Amplitude(s) for diagram number 310
      CALL VVS3_0(W(1,34),W(1,10),W(1,3),GC_289,AMP(310))
C     Amplitude(s) for diagram number 311
      CALL VVS4_0(W(1,7),W(1,35),W(1,3),GC_227,AMP(311))
C     Amplitude(s) for diagram number 312
      CALL VVS3_0(W(1,35),W(1,9),W(1,3),GC_284,AMP(312))
C     Amplitude(s) for diagram number 313
      CALL VVS3_0(W(1,35),W(1,10),W(1,3),GC_289,AMP(313))
C     Amplitude(s) for diagram number 314
      CALL VVS4_0(W(1,6),W(1,36),W(1,3),GC_245,AMP(314))
C     Amplitude(s) for diagram number 315
      CALL VVS4_0(W(1,7),W(1,36),W(1,3),GC_245,AMP(315))
C     Amplitude(s) for diagram number 316
      CALL VVS4_0(W(1,11),W(1,36),W(1,3),GC_245,AMP(316))
C     Amplitude(s) for diagram number 317
      CALL VVS4_0(W(1,12),W(1,36),W(1,3),GC_245,AMP(317))
C     Amplitude(s) for diagram number 318
      CALL VVS4_0(W(1,13),W(1,36),W(1,3),GC_245,AMP(318))
C     Amplitude(s) for diagram number 319
      CALL VVS4_0(W(1,14),W(1,36),W(1,3),GC_245,AMP(319))
C     Amplitude(s) for diagram number 320
      CALL VVS4_0(W(1,45),W(1,36),W(1,3),GC_245,AMP(320))
C     Amplitude(s) for diagram number 321
      CALL VVS4_0(W(1,46),W(1,36),W(1,3),GC_245,AMP(321))
C     Amplitude(s) for diagram number 322
      CALL VVS4_0(W(1,47),W(1,36),W(1,3),GC_245,AMP(322))
C     Amplitude(s) for diagram number 323
      CALL VVS3_0(W(1,48),W(1,36),W(1,3),GC_289,AMP(323))
C     Amplitude(s) for diagram number 324
      CALL VVS3_0(W(1,9),W(1,36),W(1,3),GC_289,AMP(324))
C     Amplitude(s) for diagram number 325
      CALL VVS3_0(W(1,49),W(1,36),W(1,3),GC_289,AMP(325))
C     Amplitude(s) for diagram number 326
      CALL VVS3_0(W(1,50),W(1,36),W(1,3),GC_289,AMP(326))
C     Amplitude(s) for diagram number 327
      CALL VVS3_0(W(1,51),W(1,36),W(1,3),GC_289,AMP(327))
C     Amplitude(s) for diagram number 328
      CALL VVS3_0(W(1,52),W(1,36),W(1,3),GC_289,AMP(328))
C     Amplitude(s) for diagram number 329
      CALL VVS3_0(W(1,53),W(1,36),W(1,3),GC_289,AMP(329))
C     Amplitude(s) for diagram number 330
      CALL VVS3_0(W(1,54),W(1,36),W(1,3),GC_289,AMP(330))
C     Amplitude(s) for diagram number 331
      CALL VVS3_0(W(1,55),W(1,36),W(1,3),GC_289,AMP(331))
C     Amplitude(s) for diagram number 332
      CALL VVS3_0(W(1,56),W(1,36),W(1,3),GC_289,AMP(332))
C     Amplitude(s) for diagram number 333
      CALL VVS3_0(W(1,57),W(1,36),W(1,3),GC_289,AMP(333))
C     Amplitude(s) for diagram number 334
      CALL VVS3_0(W(1,58),W(1,36),W(1,3),GC_289,AMP(334))
C     Amplitude(s) for diagram number 335
      CALL VVS3_0(W(1,59),W(1,36),W(1,3),GC_289,AMP(335))
C     Amplitude(s) for diagram number 336
      CALL VVS3_0(W(1,36),W(1,10),W(1,3),GC_291,AMP(336))
      CALL FFS2_3(W(1,4),W(1,5),GC_756,MDL_MH,MDL_WH,W(1,36))
C     Amplitude(s) for diagram number 337
      CALL SSS2_0(W(1,37),W(1,3),W(1,36),GC_263,AMP(337))
C     Amplitude(s) for diagram number 338
      CALL SSS1_0(W(1,37),W(1,3),W(1,36),GC_260,AMP(338))
C     Amplitude(s) for diagram number 339
      CALL SSS3_0(W(1,37),W(1,3),W(1,36),GC_262,AMP(339))
C     Amplitude(s) for diagram number 340
      CALL SSS1_0(W(1,37),W(1,3),W(1,36),GC_434,AMP(340))
C     Amplitude(s) for diagram number 341
      CALL SSS1_0(W(1,37),W(1,3),W(1,36),GC_435,AMP(341))
C     Amplitude(s) for diagram number 342
      CALL SSS1_0(W(1,37),W(1,3),W(1,36),GC_436,AMP(342))
C     Amplitude(s) for diagram number 343
      CALL SSS1_0(W(1,37),W(1,3),W(1,36),GC_437,AMP(343))
C     Amplitude(s) for diagram number 344
      CALL SSS1_0(W(1,37),W(1,3),W(1,36),GC_438,AMP(344))
      CALL FFS1_3(W(1,4),W(1,5),GC_800,MDL_MH,MDL_WH,W(1,35))
C     Amplitude(s) for diagram number 345
      CALL SSS1_0(W(1,37),W(1,3),W(1,35),GC_260,AMP(345))
      CALL FFS2_3(W(1,4),W(1,5),GC_801,MDL_MH,MDL_WH,W(1,34))
C     Amplitude(s) for diagram number 346
      CALL SSS1_0(W(1,37),W(1,3),W(1,34),GC_260,AMP(346))
      CALL FFS2_3(W(1,4),W(1,5),GC_802,MDL_MH,MDL_WH,W(1,33))
C     Amplitude(s) for diagram number 347
      CALL SSS1_0(W(1,37),W(1,3),W(1,33),GC_260,AMP(347))
      CALL FFS2_3(W(1,4),W(1,5),GC_803,MDL_MH,MDL_WH,W(1,32))
C     Amplitude(s) for diagram number 348
      CALL SSS1_0(W(1,37),W(1,3),W(1,32),GC_260,AMP(348))
      CALL FFS2_3(W(1,4),W(1,5),GC_804,MDL_MH,MDL_WH,W(1,31))
C     Amplitude(s) for diagram number 349
      CALL SSS1_0(W(1,37),W(1,3),W(1,31),GC_260,AMP(349))
      CALL FFS2_3(W(1,4),W(1,5),GC_805,MDL_MH,MDL_WH,W(1,30))
C     Amplitude(s) for diagram number 350
      CALL SSS1_0(W(1,37),W(1,3),W(1,30),GC_260,AMP(350))
      CALL FFS2PH1_3(W(1,4),W(1,5),GC_769,MDL_MH1,MDL_WH1,W(1,29))
C     Amplitude(s) for diagram number 351
      CALL SSS1_0(W(1,37),W(1,3),W(1,29),GC_280,AMP(351))
C     Amplitude(s) for diagram number 352
      CALL SSS1_0(W(1,38),W(1,3),W(1,36),GC_260,AMP(352))
C     Amplitude(s) for diagram number 353
      CALL SSS1_0(W(1,38),W(1,3),W(1,29),GC_280,AMP(353))
C     Amplitude(s) for diagram number 354
      CALL SSS1_0(W(1,39),W(1,3),W(1,36),GC_260,AMP(354))
C     Amplitude(s) for diagram number 355
      CALL SSS1_0(W(1,39),W(1,3),W(1,29),GC_280,AMP(355))
C     Amplitude(s) for diagram number 356
      CALL SSS1_0(W(1,40),W(1,3),W(1,36),GC_260,AMP(356))
C     Amplitude(s) for diagram number 357
      CALL SSS1_0(W(1,40),W(1,3),W(1,29),GC_280,AMP(357))
C     Amplitude(s) for diagram number 358
      CALL SSS1_0(W(1,41),W(1,3),W(1,36),GC_260,AMP(358))
C     Amplitude(s) for diagram number 359
      CALL SSS1_0(W(1,41),W(1,3),W(1,29),GC_280,AMP(359))
C     Amplitude(s) for diagram number 360
      CALL SSS1_0(W(1,42),W(1,3),W(1,36),GC_260,AMP(360))
C     Amplitude(s) for diagram number 361
      CALL SSS1_0(W(1,42),W(1,3),W(1,29),GC_280,AMP(361))
C     Amplitude(s) for diagram number 362
      CALL SSS1_0(W(1,43),W(1,3),W(1,36),GC_260,AMP(362))
C     Amplitude(s) for diagram number 363
      CALL SSS1_0(W(1,43),W(1,3),W(1,29),GC_280,AMP(363))
C     Amplitude(s) for diagram number 364
      CALL SSS1_0(W(1,3),W(1,36),W(1,44),GC_280,AMP(364))
C     Amplitude(s) for diagram number 365
      CALL SSS1_0(W(1,3),W(1,35),W(1,44),GC_280,AMP(365))
C     Amplitude(s) for diagram number 366
      CALL SSS1_0(W(1,3),W(1,34),W(1,44),GC_280,AMP(366))
C     Amplitude(s) for diagram number 367
      CALL SSS1_0(W(1,3),W(1,33),W(1,44),GC_280,AMP(367))
C     Amplitude(s) for diagram number 368
      CALL SSS1_0(W(1,3),W(1,32),W(1,44),GC_280,AMP(368))
C     Amplitude(s) for diagram number 369
      CALL SSS1_0(W(1,3),W(1,31),W(1,44),GC_280,AMP(369))
C     Amplitude(s) for diagram number 370
      CALL SSS1_0(W(1,3),W(1,30),W(1,44),GC_280,AMP(370))
C     Amplitude(s) for diagram number 371
      CALL SSS1_0(W(1,3),W(1,44),W(1,29),GC_281,AMP(371))
C     Amplitude(s) for diagram number 372
      CALL FFVS5_0(W(1,4),W(1,5),W(1,8),W(1,3),GC_763,AMP(372))
C     Amplitude(s) for diagram number 373
      CALL FFVS1_0(W(1,4),W(1,5),W(1,8),W(1,3),GC_762,AMP(373))
C     Amplitude(s) for diagram number 374
      CALL FFVS5_0(W(1,4),W(1,5),W(1,8),W(1,3),GC_778,AMP(374))
C     Amplitude(s) for diagram number 375
      CALL FFVS1_0(W(1,4),W(1,5),W(1,8),W(1,3),GC_777,AMP(375))
C     Amplitude(s) for diagram number 376
      CALL FFVS2_0(W(1,4),W(1,5),W(1,23),W(1,3),GC_306,AMP(376))
C     Amplitude(s) for diagram number 377
      CALL FFVS5_0(W(1,4),W(1,5),W(1,23),W(1,3),GC_765,AMP(377))
C     Amplitude(s) for diagram number 378
      CALL FFVS1_0(W(1,4),W(1,5),W(1,23),W(1,3),GC_764,AMP(378))
C     Amplitude(s) for diagram number 379
      CALL FFVS4_0(W(1,4),W(1,5),W(1,23),W(1,3),GC_305,AMP(379))
C     Amplitude(s) for diagram number 380
      CALL FFVS2_0(W(1,4),W(1,5),W(1,23),W(1,3),GC_308,AMP(380))
C     Amplitude(s) for diagram number 381
      CALL FFVS1_0(W(1,4),W(1,5),W(1,23),W(1,3),GC_775,AMP(381))
C     Amplitude(s) for diagram number 382
      CALL FFVS5_0(W(1,4),W(1,5),W(1,23),W(1,3),GC_776,AMP(382))
C     Amplitude(s) for diagram number 383
      CALL FFSS2_0(W(1,4),W(1,5),W(1,3),W(1,37),GC_780,AMP(383))
C     Amplitude(s) for diagram number 384
      CALL FFSS1_0(W(1,4),W(1,5),W(1,3),W(1,37),GC_779,AMP(384))
      CALL FFS2_2(W(1,1),W(1,3),GC_585,MDL_MD,ZERO,W(1,37))
C     Amplitude(s) for diagram number 385
      CALL FFV1_0(W(1,37),W(1,2),W(1,6),GC_1,AMP(385))
C     Amplitude(s) for diagram number 386
      CALL FFV2_0(W(1,37),W(1,2),W(1,7),GC_619,AMP(386))
C     Amplitude(s) for diagram number 387
      CALL FFV1_0(W(1,37),W(1,2),W(1,7),GC_1,AMP(387))
C     Amplitude(s) for diagram number 388
      CALL FFV9_0(W(1,37),W(1,2),W(1,7),GC_620,AMP(388))
C     Amplitude(s) for diagram number 389
      CALL FFV2_0(W(1,37),W(1,2),W(1,7),GC_635,AMP(389))
C     Amplitude(s) for diagram number 390
      CALL FFV1_0(W(1,37),W(1,2),W(1,7),GC_331,AMP(390))
C     Amplitude(s) for diagram number 391
      CALL FFV9_0(W(1,37),W(1,2),W(1,7),GC_636,AMP(391))
C     Amplitude(s) for diagram number 392
      CALL FFV1_0(W(1,37),W(1,2),W(1,7),GC_341,AMP(392))
C     Amplitude(s) for diagram number 393
      CALL FFV1_0(W(1,37),W(1,2),W(1,7),GC_352,AMP(393))
C     Amplitude(s) for diagram number 394
      CALL FFV1_0(W(1,37),W(1,2),W(1,7),GC_415,AMP(394))
C     Amplitude(s) for diagram number 395
      CALL FFV1_0(W(1,37),W(1,2),W(1,11),GC_1,AMP(395))
C     Amplitude(s) for diagram number 396
      CALL FFV1_0(W(1,37),W(1,2),W(1,12),GC_1,AMP(396))
C     Amplitude(s) for diagram number 397
      CALL FFV1_0(W(1,37),W(1,2),W(1,13),GC_1,AMP(397))
C     Amplitude(s) for diagram number 398
      CALL FFV1_0(W(1,37),W(1,2),W(1,14),GC_1,AMP(398))
C     Amplitude(s) for diagram number 399
      CALL FFV1_0(W(1,37),W(1,2),W(1,45),GC_1,AMP(399))
C     Amplitude(s) for diagram number 400
      CALL FFV1_0(W(1,37),W(1,2),W(1,46),GC_1,AMP(400))
C     Amplitude(s) for diagram number 401
      CALL FFV1_0(W(1,37),W(1,2),W(1,47),GC_1,AMP(401))
C     Amplitude(s) for diagram number 402
      CALL FFV1_3_0(W(1,37),W(1,2),W(1,48),GC_195,GC_136,AMP(402))
C     Amplitude(s) for diagram number 403
      CALL FFV2_0(W(1,37),W(1,2),W(1,9),GC_621,AMP(403))
C     Amplitude(s) for diagram number 404
      CALL FFV1_3_0(W(1,37),W(1,2),W(1,9),GC_195,GC_136,AMP(404))
C     Amplitude(s) for diagram number 405
      CALL FFV9_0(W(1,37),W(1,2),W(1,9),GC_622,AMP(405))
C     Amplitude(s) for diagram number 406
      CALL FFV8_0(W(1,37),W(1,2),W(1,9),GC_399,AMP(406))
C     Amplitude(s) for diagram number 407
      CALL FFV5_0(W(1,37),W(1,2),W(1,9),GC_398,AMP(407))
C     Amplitude(s) for diagram number 408
      CALL FFV2_0(W(1,37),W(1,2),W(1,9),GC_633,AMP(408))
C     Amplitude(s) for diagram number 409
      CALL FFV9_0(W(1,37),W(1,2),W(1,9),GC_634,AMP(409))
C     Amplitude(s) for diagram number 410
      CALL FFV1_0(W(1,37),W(1,2),W(1,9),GC_335,AMP(410))
C     Amplitude(s) for diagram number 411
      CALL FFV3_0(W(1,37),W(1,2),W(1,9),GC_405,AMP(411))
C     Amplitude(s) for diagram number 412
      CALL FFV3_0(W(1,37),W(1,2),W(1,9),GC_407,AMP(412))
C     Amplitude(s) for diagram number 413
      CALL FFV1_0(W(1,37),W(1,2),W(1,9),GC_425,AMP(413))
C     Amplitude(s) for diagram number 414
      CALL FFV3_0(W(1,37),W(1,2),W(1,9),GC_409,AMP(414))
C     Amplitude(s) for diagram number 415
      CALL FFV1_0(W(1,37),W(1,2),W(1,9),GC_428,AMP(415))
C     Amplitude(s) for diagram number 416
      CALL FFV1_3_0(W(1,37),W(1,2),W(1,9),GC_431,GC_412,AMP(416))
C     Amplitude(s) for diagram number 417
      CALL FFV1_3_0(W(1,37),W(1,2),W(1,49),GC_195,GC_136,AMP(417))
C     Amplitude(s) for diagram number 418
      CALL FFV1_3_0(W(1,37),W(1,2),W(1,50),GC_195,GC_136,AMP(418))
C     Amplitude(s) for diagram number 419
      CALL FFV1_3_0(W(1,37),W(1,2),W(1,51),GC_195,GC_136,AMP(419))
C     Amplitude(s) for diagram number 420
      CALL FFV1_3_0(W(1,37),W(1,2),W(1,52),GC_195,GC_136,AMP(420))
C     Amplitude(s) for diagram number 421
      CALL FFV1_3_0(W(1,37),W(1,2),W(1,53),GC_195,GC_136,AMP(421))
C     Amplitude(s) for diagram number 422
      CALL FFV1_3_0(W(1,37),W(1,2),W(1,54),GC_195,GC_136,AMP(422))
C     Amplitude(s) for diagram number 423
      CALL FFV1_3_0(W(1,37),W(1,2),W(1,55),GC_195,GC_136,AMP(423))
C     Amplitude(s) for diagram number 424
      CALL FFV1_3_0(W(1,37),W(1,2),W(1,56),GC_195,GC_136,AMP(424))
C     Amplitude(s) for diagram number 425
      CALL FFV1_3_0(W(1,37),W(1,2),W(1,57),GC_195,GC_136,AMP(425))
C     Amplitude(s) for diagram number 426
      CALL FFV1_3_0(W(1,37),W(1,2),W(1,58),GC_195,GC_136,AMP(426))
C     Amplitude(s) for diagram number 427
      CALL FFV1_3_0(W(1,37),W(1,2),W(1,59),GC_195,GC_136,AMP(427))
C     Amplitude(s) for diagram number 428
      CALL FFV1_3_0(W(1,37),W(1,2),W(1,10),GC_212,GC_183,AMP(428))
C     Amplitude(s) for diagram number 429
      CALL FFS2_0(W(1,37),W(1,2),W(1,36),GC_585,AMP(429))
C     Amplitude(s) for diagram number 430
      CALL FFS1_0(W(1,37),W(1,2),W(1,36),GC_637,AMP(430))
C     Amplitude(s) for diagram number 431
      CALL FFS2_0(W(1,37),W(1,2),W(1,36),GC_638,AMP(431))
C     Amplitude(s) for diagram number 432
      CALL FFS2_0(W(1,37),W(1,2),W(1,36),GC_639,AMP(432))
C     Amplitude(s) for diagram number 433
      CALL FFS2_0(W(1,37),W(1,2),W(1,36),GC_640,AMP(433))
C     Amplitude(s) for diagram number 434
      CALL FFS2_0(W(1,37),W(1,2),W(1,36),GC_641,AMP(434))
C     Amplitude(s) for diagram number 435
      CALL FFS2_0(W(1,37),W(1,2),W(1,36),GC_642,AMP(435))
C     Amplitude(s) for diagram number 436
      CALL FFS2_0(W(1,37),W(1,2),W(1,35),GC_585,AMP(436))
C     Amplitude(s) for diagram number 437
      CALL FFS2_0(W(1,37),W(1,2),W(1,34),GC_585,AMP(437))
C     Amplitude(s) for diagram number 438
      CALL FFS2_0(W(1,37),W(1,2),W(1,33),GC_585,AMP(438))
C     Amplitude(s) for diagram number 439
      CALL FFS2_0(W(1,37),W(1,2),W(1,32),GC_585,AMP(439))
C     Amplitude(s) for diagram number 440
      CALL FFS2_0(W(1,37),W(1,2),W(1,31),GC_585,AMP(440))
C     Amplitude(s) for diagram number 441
      CALL FFS2_0(W(1,37),W(1,2),W(1,30),GC_585,AMP(441))
C     Amplitude(s) for diagram number 442
      CALL FFS2_0(W(1,37),W(1,2),W(1,29),GC_602,AMP(442))
      CALL FFS1_2(W(1,1),W(1,3),GC_637,MDL_MD,ZERO,W(1,23))
C     Amplitude(s) for diagram number 443
      CALL FFV1_0(W(1,23),W(1,2),W(1,7),GC_1,AMP(443))
C     Amplitude(s) for diagram number 444
      CALL FFV1_3_0(W(1,23),W(1,2),W(1,9),GC_195,GC_136,AMP(444))
C     Amplitude(s) for diagram number 445
      CALL FFV1_3_0(W(1,23),W(1,2),W(1,10),GC_212,GC_183,AMP(445))
C     Amplitude(s) for diagram number 446
      CALL FFS2_0(W(1,23),W(1,2),W(1,36),GC_585,AMP(446))
C     Amplitude(s) for diagram number 447
      CALL FFS2_0(W(1,23),W(1,2),W(1,29),GC_602,AMP(447))
      CALL FFS2_2(W(1,1),W(1,3),GC_638,MDL_MD,ZERO,W(1,23))
C     Amplitude(s) for diagram number 448
      CALL FFV1_0(W(1,23),W(1,2),W(1,7),GC_1,AMP(448))
C     Amplitude(s) for diagram number 449
      CALL FFV1_3_0(W(1,23),W(1,2),W(1,9),GC_195,GC_136,AMP(449))
C     Amplitude(s) for diagram number 450
      CALL FFV1_3_0(W(1,23),W(1,2),W(1,10),GC_212,GC_183,AMP(450))
C     Amplitude(s) for diagram number 451
      CALL FFS2_0(W(1,23),W(1,2),W(1,36),GC_585,AMP(451))
C     Amplitude(s) for diagram number 452
      CALL FFS2_0(W(1,23),W(1,2),W(1,29),GC_602,AMP(452))
      CALL FFS2_2(W(1,1),W(1,3),GC_639,MDL_MD,ZERO,W(1,23))
C     Amplitude(s) for diagram number 453
      CALL FFV1_0(W(1,23),W(1,2),W(1,7),GC_1,AMP(453))
C     Amplitude(s) for diagram number 454
      CALL FFV1_3_0(W(1,23),W(1,2),W(1,9),GC_195,GC_136,AMP(454))
C     Amplitude(s) for diagram number 455
      CALL FFV1_3_0(W(1,23),W(1,2),W(1,10),GC_212,GC_183,AMP(455))
C     Amplitude(s) for diagram number 456
      CALL FFS2_0(W(1,23),W(1,2),W(1,36),GC_585,AMP(456))
C     Amplitude(s) for diagram number 457
      CALL FFS2_0(W(1,23),W(1,2),W(1,29),GC_602,AMP(457))
      CALL FFS2_2(W(1,1),W(1,3),GC_640,MDL_MD,ZERO,W(1,23))
C     Amplitude(s) for diagram number 458
      CALL FFV1_0(W(1,23),W(1,2),W(1,7),GC_1,AMP(458))
C     Amplitude(s) for diagram number 459
      CALL FFV1_3_0(W(1,23),W(1,2),W(1,9),GC_195,GC_136,AMP(459))
C     Amplitude(s) for diagram number 460
      CALL FFV1_3_0(W(1,23),W(1,2),W(1,10),GC_212,GC_183,AMP(460))
C     Amplitude(s) for diagram number 461
      CALL FFS2_0(W(1,23),W(1,2),W(1,36),GC_585,AMP(461))
C     Amplitude(s) for diagram number 462
      CALL FFS2_0(W(1,23),W(1,2),W(1,29),GC_602,AMP(462))
      CALL FFS2_2(W(1,1),W(1,3),GC_641,MDL_MD,ZERO,W(1,23))
C     Amplitude(s) for diagram number 463
      CALL FFV1_0(W(1,23),W(1,2),W(1,7),GC_1,AMP(463))
C     Amplitude(s) for diagram number 464
      CALL FFV1_3_0(W(1,23),W(1,2),W(1,9),GC_195,GC_136,AMP(464))
C     Amplitude(s) for diagram number 465
      CALL FFV1_3_0(W(1,23),W(1,2),W(1,10),GC_212,GC_183,AMP(465))
C     Amplitude(s) for diagram number 466
      CALL FFS2_0(W(1,23),W(1,2),W(1,36),GC_585,AMP(466))
C     Amplitude(s) for diagram number 467
      CALL FFS2_0(W(1,23),W(1,2),W(1,29),GC_602,AMP(467))
      CALL FFS2_2(W(1,1),W(1,3),GC_642,MDL_MD,ZERO,W(1,23))
C     Amplitude(s) for diagram number 468
      CALL FFV1_0(W(1,23),W(1,2),W(1,7),GC_1,AMP(468))
C     Amplitude(s) for diagram number 469
      CALL FFV1_3_0(W(1,23),W(1,2),W(1,9),GC_195,GC_136,AMP(469))
C     Amplitude(s) for diagram number 470
      CALL FFV1_3_0(W(1,23),W(1,2),W(1,10),GC_212,GC_183,AMP(470))
C     Amplitude(s) for diagram number 471
      CALL FFS2_0(W(1,23),W(1,2),W(1,36),GC_585,AMP(471))
C     Amplitude(s) for diagram number 472
      CALL FFS2_0(W(1,23),W(1,2),W(1,29),GC_602,AMP(472))
C     Amplitude(s) for diagram number 473
      CALL FFFF13_0(W(1,4),W(1,5),W(1,37),W(1,2),GC_43,AMP(473))
C     Amplitude(s) for diagram number 474
      CALL FFFF11_9_0(W(1,4),W(1,5),W(1,37),W(1,2),GC_843,GC_842
     $ ,AMP(474))
C     Amplitude(s) for diagram number 475
      CALL FFFF4_0(W(1,4),W(1,5),W(1,37),W(1,2),GC_28,AMP(475))
C     Amplitude(s) for diagram number 476
      CALL FFFF18_0(W(1,4),W(1,5),W(1,37),W(1,2),GC_12,AMP(476))
C     Amplitude(s) for diagram number 477
      CALL FFFF17_0(W(1,4),W(1,5),W(1,37),W(1,2),GC_24,AMP(477))
C     Amplitude(s) for diagram number 478
      CALL FFFF4_0(W(1,4),W(1,5),W(1,37),W(1,2),GC_30,AMP(478))
C     Amplitude(s) for diagram number 479
      CALL FFFF22_0(W(1,4),W(1,5),W(1,37),W(1,2),GC_847,AMP(479))
      CALL FFS2_1(W(1,2),W(1,3),GC_585,MDL_MD,ZERO,W(1,37))
C     Amplitude(s) for diagram number 480
      CALL FFV1_0(W(1,1),W(1,37),W(1,6),GC_1,AMP(480))
C     Amplitude(s) for diagram number 481
      CALL FFV2_0(W(1,1),W(1,37),W(1,7),GC_619,AMP(481))
C     Amplitude(s) for diagram number 482
      CALL FFV1_0(W(1,1),W(1,37),W(1,7),GC_1,AMP(482))
C     Amplitude(s) for diagram number 483
      CALL FFV9_0(W(1,1),W(1,37),W(1,7),GC_620,AMP(483))
C     Amplitude(s) for diagram number 484
      CALL FFV2_0(W(1,1),W(1,37),W(1,7),GC_635,AMP(484))
C     Amplitude(s) for diagram number 485
      CALL FFV1_0(W(1,1),W(1,37),W(1,7),GC_331,AMP(485))
C     Amplitude(s) for diagram number 486
      CALL FFV9_0(W(1,1),W(1,37),W(1,7),GC_636,AMP(486))
C     Amplitude(s) for diagram number 487
      CALL FFV1_0(W(1,1),W(1,37),W(1,7),GC_341,AMP(487))
C     Amplitude(s) for diagram number 488
      CALL FFV1_0(W(1,1),W(1,37),W(1,7),GC_352,AMP(488))
C     Amplitude(s) for diagram number 489
      CALL FFV1_0(W(1,1),W(1,37),W(1,7),GC_415,AMP(489))
C     Amplitude(s) for diagram number 490
      CALL FFV1_0(W(1,1),W(1,37),W(1,11),GC_1,AMP(490))
C     Amplitude(s) for diagram number 491
      CALL FFV1_0(W(1,1),W(1,37),W(1,12),GC_1,AMP(491))
C     Amplitude(s) for diagram number 492
      CALL FFV1_0(W(1,1),W(1,37),W(1,13),GC_1,AMP(492))
C     Amplitude(s) for diagram number 493
      CALL FFV1_0(W(1,1),W(1,37),W(1,14),GC_1,AMP(493))
C     Amplitude(s) for diagram number 494
      CALL FFV1_0(W(1,1),W(1,37),W(1,45),GC_1,AMP(494))
C     Amplitude(s) for diagram number 495
      CALL FFV1_0(W(1,1),W(1,37),W(1,46),GC_1,AMP(495))
C     Amplitude(s) for diagram number 496
      CALL FFV1_0(W(1,1),W(1,37),W(1,47),GC_1,AMP(496))
C     Amplitude(s) for diagram number 497
      CALL FFV1_3_0(W(1,1),W(1,37),W(1,48),GC_195,GC_136,AMP(497))
C     Amplitude(s) for diagram number 498
      CALL FFV2_0(W(1,1),W(1,37),W(1,9),GC_621,AMP(498))
C     Amplitude(s) for diagram number 499
      CALL FFV1_3_0(W(1,1),W(1,37),W(1,9),GC_195,GC_136,AMP(499))
C     Amplitude(s) for diagram number 500
      CALL FFV9_0(W(1,1),W(1,37),W(1,9),GC_622,AMP(500))
C     Amplitude(s) for diagram number 501
      CALL FFV8_0(W(1,1),W(1,37),W(1,9),GC_399,AMP(501))
C     Amplitude(s) for diagram number 502
      CALL FFV5_0(W(1,1),W(1,37),W(1,9),GC_398,AMP(502))
C     Amplitude(s) for diagram number 503
      CALL FFV2_0(W(1,1),W(1,37),W(1,9),GC_633,AMP(503))
C     Amplitude(s) for diagram number 504
      CALL FFV9_0(W(1,1),W(1,37),W(1,9),GC_634,AMP(504))
C     Amplitude(s) for diagram number 505
      CALL FFV1_0(W(1,1),W(1,37),W(1,9),GC_335,AMP(505))
C     Amplitude(s) for diagram number 506
      CALL FFV3_0(W(1,1),W(1,37),W(1,9),GC_405,AMP(506))
C     Amplitude(s) for diagram number 507
      CALL FFV3_0(W(1,1),W(1,37),W(1,9),GC_407,AMP(507))
C     Amplitude(s) for diagram number 508
      CALL FFV1_0(W(1,1),W(1,37),W(1,9),GC_425,AMP(508))
C     Amplitude(s) for diagram number 509
      CALL FFV3_0(W(1,1),W(1,37),W(1,9),GC_409,AMP(509))
C     Amplitude(s) for diagram number 510
      CALL FFV1_0(W(1,1),W(1,37),W(1,9),GC_428,AMP(510))
C     Amplitude(s) for diagram number 511
      CALL FFV1_3_0(W(1,1),W(1,37),W(1,9),GC_431,GC_412,AMP(511))
C     Amplitude(s) for diagram number 512
      CALL FFV1_3_0(W(1,1),W(1,37),W(1,49),GC_195,GC_136,AMP(512))
C     Amplitude(s) for diagram number 513
      CALL FFV1_3_0(W(1,1),W(1,37),W(1,50),GC_195,GC_136,AMP(513))
C     Amplitude(s) for diagram number 514
      CALL FFV1_3_0(W(1,1),W(1,37),W(1,51),GC_195,GC_136,AMP(514))
C     Amplitude(s) for diagram number 515
      CALL FFV1_3_0(W(1,1),W(1,37),W(1,52),GC_195,GC_136,AMP(515))
C     Amplitude(s) for diagram number 516
      CALL FFV1_3_0(W(1,1),W(1,37),W(1,53),GC_195,GC_136,AMP(516))
C     Amplitude(s) for diagram number 517
      CALL FFV1_3_0(W(1,1),W(1,37),W(1,54),GC_195,GC_136,AMP(517))
C     Amplitude(s) for diagram number 518
      CALL FFV1_3_0(W(1,1),W(1,37),W(1,55),GC_195,GC_136,AMP(518))
C     Amplitude(s) for diagram number 519
      CALL FFV1_3_0(W(1,1),W(1,37),W(1,56),GC_195,GC_136,AMP(519))
C     Amplitude(s) for diagram number 520
      CALL FFV1_3_0(W(1,1),W(1,37),W(1,57),GC_195,GC_136,AMP(520))
C     Amplitude(s) for diagram number 521
      CALL FFV1_3_0(W(1,1),W(1,37),W(1,58),GC_195,GC_136,AMP(521))
C     Amplitude(s) for diagram number 522
      CALL FFV1_3_0(W(1,1),W(1,37),W(1,59),GC_195,GC_136,AMP(522))
C     Amplitude(s) for diagram number 523
      CALL FFV1_3_0(W(1,1),W(1,37),W(1,10),GC_212,GC_183,AMP(523))
C     Amplitude(s) for diagram number 524
      CALL FFS2_0(W(1,1),W(1,37),W(1,36),GC_585,AMP(524))
C     Amplitude(s) for diagram number 525
      CALL FFS1_0(W(1,1),W(1,37),W(1,36),GC_637,AMP(525))
C     Amplitude(s) for diagram number 526
      CALL FFS2_0(W(1,1),W(1,37),W(1,36),GC_638,AMP(526))
C     Amplitude(s) for diagram number 527
      CALL FFS2_0(W(1,1),W(1,37),W(1,36),GC_639,AMP(527))
C     Amplitude(s) for diagram number 528
      CALL FFS2_0(W(1,1),W(1,37),W(1,36),GC_640,AMP(528))
C     Amplitude(s) for diagram number 529
      CALL FFS2_0(W(1,1),W(1,37),W(1,36),GC_641,AMP(529))
C     Amplitude(s) for diagram number 530
      CALL FFS2_0(W(1,1),W(1,37),W(1,36),GC_642,AMP(530))
C     Amplitude(s) for diagram number 531
      CALL FFS2_0(W(1,1),W(1,37),W(1,35),GC_585,AMP(531))
C     Amplitude(s) for diagram number 532
      CALL FFS2_0(W(1,1),W(1,37),W(1,34),GC_585,AMP(532))
C     Amplitude(s) for diagram number 533
      CALL FFS2_0(W(1,1),W(1,37),W(1,33),GC_585,AMP(533))
C     Amplitude(s) for diagram number 534
      CALL FFS2_0(W(1,1),W(1,37),W(1,32),GC_585,AMP(534))
C     Amplitude(s) for diagram number 535
      CALL FFS2_0(W(1,1),W(1,37),W(1,31),GC_585,AMP(535))
C     Amplitude(s) for diagram number 536
      CALL FFS2_0(W(1,1),W(1,37),W(1,30),GC_585,AMP(536))
C     Amplitude(s) for diagram number 537
      CALL FFS2_0(W(1,1),W(1,37),W(1,29),GC_602,AMP(537))
      CALL FFS1_1(W(1,2),W(1,3),GC_637,MDL_MD,ZERO,W(1,37))
C     Amplitude(s) for diagram number 538
      CALL FFV1_0(W(1,1),W(1,37),W(1,7),GC_1,AMP(538))
C     Amplitude(s) for diagram number 539
      CALL FFV1_3_0(W(1,1),W(1,37),W(1,9),GC_195,GC_136,AMP(539))
C     Amplitude(s) for diagram number 540
      CALL FFV1_3_0(W(1,1),W(1,37),W(1,10),GC_212,GC_183,AMP(540))
C     Amplitude(s) for diagram number 541
      CALL FFS2_0(W(1,1),W(1,37),W(1,36),GC_585,AMP(541))
C     Amplitude(s) for diagram number 542
      CALL FFS2_0(W(1,1),W(1,37),W(1,29),GC_602,AMP(542))
      CALL FFS2_1(W(1,2),W(1,3),GC_638,MDL_MD,ZERO,W(1,37))
C     Amplitude(s) for diagram number 543
      CALL FFV1_0(W(1,1),W(1,37),W(1,7),GC_1,AMP(543))
C     Amplitude(s) for diagram number 544
      CALL FFV1_3_0(W(1,1),W(1,37),W(1,9),GC_195,GC_136,AMP(544))
C     Amplitude(s) for diagram number 545
      CALL FFV1_3_0(W(1,1),W(1,37),W(1,10),GC_212,GC_183,AMP(545))
C     Amplitude(s) for diagram number 546
      CALL FFS2_0(W(1,1),W(1,37),W(1,36),GC_585,AMP(546))
C     Amplitude(s) for diagram number 547
      CALL FFS2_0(W(1,1),W(1,37),W(1,29),GC_602,AMP(547))
      CALL FFS2_1(W(1,2),W(1,3),GC_639,MDL_MD,ZERO,W(1,37))
C     Amplitude(s) for diagram number 548
      CALL FFV1_0(W(1,1),W(1,37),W(1,7),GC_1,AMP(548))
C     Amplitude(s) for diagram number 549
      CALL FFV1_3_0(W(1,1),W(1,37),W(1,9),GC_195,GC_136,AMP(549))
C     Amplitude(s) for diagram number 550
      CALL FFV1_3_0(W(1,1),W(1,37),W(1,10),GC_212,GC_183,AMP(550))
C     Amplitude(s) for diagram number 551
      CALL FFS2_0(W(1,1),W(1,37),W(1,36),GC_585,AMP(551))
C     Amplitude(s) for diagram number 552
      CALL FFS2_0(W(1,1),W(1,37),W(1,29),GC_602,AMP(552))
      CALL FFS2_1(W(1,2),W(1,3),GC_640,MDL_MD,ZERO,W(1,37))
C     Amplitude(s) for diagram number 553
      CALL FFV1_0(W(1,1),W(1,37),W(1,7),GC_1,AMP(553))
C     Amplitude(s) for diagram number 554
      CALL FFV1_3_0(W(1,1),W(1,37),W(1,9),GC_195,GC_136,AMP(554))
C     Amplitude(s) for diagram number 555
      CALL FFV1_3_0(W(1,1),W(1,37),W(1,10),GC_212,GC_183,AMP(555))
C     Amplitude(s) for diagram number 556
      CALL FFS2_0(W(1,1),W(1,37),W(1,36),GC_585,AMP(556))
C     Amplitude(s) for diagram number 557
      CALL FFS2_0(W(1,1),W(1,37),W(1,29),GC_602,AMP(557))
      CALL FFS2_1(W(1,2),W(1,3),GC_641,MDL_MD,ZERO,W(1,37))
C     Amplitude(s) for diagram number 558
      CALL FFV1_0(W(1,1),W(1,37),W(1,7),GC_1,AMP(558))
C     Amplitude(s) for diagram number 559
      CALL FFV1_3_0(W(1,1),W(1,37),W(1,9),GC_195,GC_136,AMP(559))
C     Amplitude(s) for diagram number 560
      CALL FFV1_3_0(W(1,1),W(1,37),W(1,10),GC_212,GC_183,AMP(560))
C     Amplitude(s) for diagram number 561
      CALL FFS2_0(W(1,1),W(1,37),W(1,36),GC_585,AMP(561))
C     Amplitude(s) for diagram number 562
      CALL FFS2_0(W(1,1),W(1,37),W(1,29),GC_602,AMP(562))
      CALL FFS2_1(W(1,2),W(1,3),GC_642,MDL_MD,ZERO,W(1,37))
C     Amplitude(s) for diagram number 563
      CALL FFV1_0(W(1,1),W(1,37),W(1,7),GC_1,AMP(563))
C     Amplitude(s) for diagram number 564
      CALL FFV1_3_0(W(1,1),W(1,37),W(1,9),GC_195,GC_136,AMP(564))
C     Amplitude(s) for diagram number 565
      CALL FFV1_3_0(W(1,1),W(1,37),W(1,10),GC_212,GC_183,AMP(565))
C     Amplitude(s) for diagram number 566
      CALL FFS2_0(W(1,1),W(1,37),W(1,36),GC_585,AMP(566))
C     Amplitude(s) for diagram number 567
      CALL FFS2_0(W(1,1),W(1,37),W(1,29),GC_602,AMP(567))
      CALL FFVS2_3(W(1,1),W(1,2),W(1,3),GC_309,MDL_MZ,MDL_WZ,W(1,37))
C     Amplitude(s) for diagram number 568
      CALL FFV1_3_0(W(1,4),W(1,5),W(1,37),GC_197,GC_136,AMP(568))
      CALL FFVS5_3(W(1,1),W(1,2),W(1,3),GC_596,MDL_MZ,MDL_WZ,W(1,37))
C     Amplitude(s) for diagram number 569
      CALL FFV1_3_0(W(1,4),W(1,5),W(1,37),GC_197,GC_136,AMP(569))
      CALL FFVS1_3(W(1,1),W(1,2),W(1,3),GC_595,MDL_MZ,MDL_WZ,W(1,37))
C     Amplitude(s) for diagram number 570
      CALL FFV1_3_0(W(1,4),W(1,5),W(1,37),GC_197,GC_136,AMP(570))
      CALL FFVS4_3(W(1,1),W(1,2),W(1,3),GC_304,MDL_MZ,MDL_WZ,W(1,37))
C     Amplitude(s) for diagram number 571
      CALL FFV1_3_0(W(1,4),W(1,5),W(1,37),GC_197,GC_136,AMP(571))
      CALL FFVS2_3(W(1,1),W(1,2),W(1,3),GC_311,MDL_MZ,MDL_WZ,W(1,37))
C     Amplitude(s) for diagram number 572
      CALL FFV1_3_0(W(1,4),W(1,5),W(1,37),GC_197,GC_136,AMP(572))
      CALL FFVS1_3(W(1,1),W(1,2),W(1,3),GC_608,MDL_MZ,MDL_WZ,W(1,37))
C     Amplitude(s) for diagram number 573
      CALL FFV1_3_0(W(1,4),W(1,5),W(1,37),GC_197,GC_136,AMP(573))
      CALL FFVS5_3(W(1,1),W(1,2),W(1,3),GC_609,MDL_MZ,MDL_WZ,W(1,37))
C     Amplitude(s) for diagram number 574
      CALL FFV1_3_0(W(1,4),W(1,5),W(1,37),GC_197,GC_136,AMP(574))
      CALL FFSS2_3(W(1,1),W(1,2),W(1,3),GC_615,MDL_MH,MDL_WH,W(1,37))
C     Amplitude(s) for diagram number 575
      CALL FFS2_0(W(1,4),W(1,5),W(1,37),GC_756,AMP(575))
      CALL FFSS1_3(W(1,1),W(1,2),W(1,3),GC_614,MDL_MH,MDL_WH,W(1,37))
C     Amplitude(s) for diagram number 576
      CALL FFS2_0(W(1,4),W(1,5),W(1,37),GC_756,AMP(576))
      CALL FFVS5P0_3(W(1,1),W(1,2),W(1,3),GC_594,ZERO,ZERO,W(1,37))
C     Amplitude(s) for diagram number 577
      CALL FFV1_0(W(1,4),W(1,5),W(1,37),GC_4,AMP(577))
      CALL FFVS1P0_3(W(1,1),W(1,2),W(1,3),GC_593,ZERO,ZERO,W(1,37))
C     Amplitude(s) for diagram number 578
      CALL FFV1_0(W(1,4),W(1,5),W(1,37),GC_4,AMP(578))
      CALL FFVS5P0_3(W(1,1),W(1,2),W(1,3),GC_611,ZERO,ZERO,W(1,37))
C     Amplitude(s) for diagram number 579
      CALL FFV1_0(W(1,4),W(1,5),W(1,37),GC_4,AMP(579))
      CALL FFVS1P0_3(W(1,1),W(1,2),W(1,3),GC_610,ZERO,ZERO,W(1,37))
C     Amplitude(s) for diagram number 580
      CALL FFV1_0(W(1,4),W(1,5),W(1,37),GC_4,AMP(580))
      CALL FFFF13_2(W(1,4),W(1,1),W(1,2),GC_43,MDL_MMU,ZERO,W(1,37))
C     Amplitude(s) for diagram number 581
      CALL FFS2_0(W(1,37),W(1,5),W(1,3),GC_756,AMP(581))
      CALL FFFF11_9_2(W(1,4),W(1,1),W(1,2),GC_843,GC_842,MDL_MMU,ZERO
     $ ,W(1,37))
C     Amplitude(s) for diagram number 582
      CALL FFS2_0(W(1,37),W(1,5),W(1,3),GC_756,AMP(582))
      CALL FFFF4_2(W(1,4),W(1,1),W(1,2),GC_28,MDL_MMU,ZERO,W(1,37))
C     Amplitude(s) for diagram number 583
      CALL FFS2_0(W(1,37),W(1,5),W(1,3),GC_756,AMP(583))
      CALL FFFF18_2(W(1,4),W(1,1),W(1,2),GC_12,MDL_MMU,ZERO,W(1,37))
C     Amplitude(s) for diagram number 584
      CALL FFS2_0(W(1,37),W(1,5),W(1,3),GC_756,AMP(584))
      CALL FFFF17_2(W(1,4),W(1,1),W(1,2),GC_24,MDL_MMU,ZERO,W(1,37))
C     Amplitude(s) for diagram number 585
      CALL FFS2_0(W(1,37),W(1,5),W(1,3),GC_756,AMP(585))
      CALL FFFF4_2(W(1,4),W(1,1),W(1,2),GC_30,MDL_MMU,ZERO,W(1,37))
C     Amplitude(s) for diagram number 586
      CALL FFS2_0(W(1,37),W(1,5),W(1,3),GC_756,AMP(586))
      CALL FFFF22_2(W(1,4),W(1,1),W(1,2),GC_847,MDL_MMU,ZERO,W(1,37))
C     Amplitude(s) for diagram number 587
      CALL FFS2_0(W(1,37),W(1,5),W(1,3),GC_756,AMP(587))
      CALL FFFF13_1(W(1,5),W(1,1),W(1,2),GC_43,MDL_MMU,ZERO,W(1,37))
C     Amplitude(s) for diagram number 588
      CALL FFS2_0(W(1,4),W(1,37),W(1,3),GC_756,AMP(588))
      CALL FFFF11_9_1(W(1,5),W(1,1),W(1,2),GC_843,GC_842,MDL_MMU,ZERO
     $ ,W(1,37))
C     Amplitude(s) for diagram number 589
      CALL FFS2_0(W(1,4),W(1,37),W(1,3),GC_756,AMP(589))
      CALL FFFF4_1(W(1,5),W(1,1),W(1,2),GC_28,MDL_MMU,ZERO,W(1,37))
C     Amplitude(s) for diagram number 590
      CALL FFS2_0(W(1,4),W(1,37),W(1,3),GC_756,AMP(590))
      CALL FFFF18_1(W(1,5),W(1,1),W(1,2),GC_12,MDL_MMU,ZERO,W(1,37))
C     Amplitude(s) for diagram number 591
      CALL FFS2_0(W(1,4),W(1,37),W(1,3),GC_756,AMP(591))
      CALL FFFF17_1(W(1,5),W(1,1),W(1,2),GC_24,MDL_MMU,ZERO,W(1,37))
C     Amplitude(s) for diagram number 592
      CALL FFS2_0(W(1,4),W(1,37),W(1,3),GC_756,AMP(592))
      CALL FFFF4_1(W(1,5),W(1,1),W(1,2),GC_30,MDL_MMU,ZERO,W(1,37))
C     Amplitude(s) for diagram number 593
      CALL FFS2_0(W(1,4),W(1,37),W(1,3),GC_756,AMP(593))
      CALL FFFF22_1(W(1,5),W(1,1),W(1,2),GC_847,MDL_MMU,ZERO,W(1,37))
C     Amplitude(s) for diagram number 594
      CALL FFS2_0(W(1,4),W(1,37),W(1,3),GC_756,AMP(594))
      CALL FFFF13_4(W(1,4),W(1,5),W(1,1),GC_43,MDL_MD,ZERO,W(1,37))
C     Amplitude(s) for diagram number 595
      CALL FFS2_0(W(1,37),W(1,2),W(1,3),GC_585,AMP(595))
      CALL FFFF11_9_4(W(1,4),W(1,5),W(1,1),GC_843,GC_842,MDL_MD,ZERO
     $ ,W(1,37))
C     Amplitude(s) for diagram number 596
      CALL FFS2_0(W(1,37),W(1,2),W(1,3),GC_585,AMP(596))
      CALL FFFF4_4(W(1,4),W(1,5),W(1,1),GC_28,MDL_MD,ZERO,W(1,37))
C     Amplitude(s) for diagram number 597
      CALL FFS2_0(W(1,37),W(1,2),W(1,3),GC_585,AMP(597))
      CALL FFFF18_4(W(1,4),W(1,5),W(1,1),GC_12,MDL_MD,ZERO,W(1,37))
C     Amplitude(s) for diagram number 598
      CALL FFS2_0(W(1,37),W(1,2),W(1,3),GC_585,AMP(598))
      CALL FFFF17_4(W(1,4),W(1,5),W(1,1),GC_24,MDL_MD,ZERO,W(1,37))
C     Amplitude(s) for diagram number 599
      CALL FFS2_0(W(1,37),W(1,2),W(1,3),GC_585,AMP(599))
      CALL FFFF4_4(W(1,4),W(1,5),W(1,1),GC_30,MDL_MD,ZERO,W(1,37))
C     Amplitude(s) for diagram number 600
      CALL FFS2_0(W(1,37),W(1,2),W(1,3),GC_585,AMP(600))
      CALL FFFF22_4(W(1,4),W(1,5),W(1,1),GC_847,MDL_MD,ZERO,W(1,37))
C     Amplitude(s) for diagram number 601
      CALL FFS2_0(W(1,37),W(1,2),W(1,3),GC_585,AMP(601))
      JAMP(1)=+AMP(1)+AMP(2)+AMP(3)+AMP(4)+AMP(5)+AMP(6)+AMP(7)+AMP(8)
     $ +AMP(9)+AMP(10)+AMP(11)+AMP(12)+AMP(13)+AMP(14)+AMP(15)+AMP(16)
     $ +AMP(17)+AMP(18)+AMP(19)+AMP(20)+AMP(21)+AMP(22)+AMP(23)+AMP(24)
     $ +AMP(25)+AMP(26)+AMP(27)+AMP(28)+AMP(29)+AMP(30)+AMP(31)+AMP(32)
     $ +AMP(33)+AMP(34)+AMP(35)+AMP(36)+AMP(37)+AMP(38)+AMP(39)+AMP(40)
     $ +AMP(41)+AMP(42)+AMP(43)+AMP(44)+AMP(45)+AMP(46)+AMP(47)+AMP(48)
     $ +AMP(49)+AMP(50)+AMP(51)+AMP(52)+AMP(53)+AMP(54)+AMP(55)+AMP(56)
     $ +AMP(57)+AMP(58)+AMP(59)+AMP(60)+AMP(61)+AMP(62)+AMP(63)+AMP(64)
     $ +AMP(65)+AMP(66)+AMP(67)+AMP(68)+AMP(69)+AMP(70)+AMP(71)+AMP(72)
     $ +AMP(73)+AMP(74)+AMP(75)+AMP(76)+AMP(77)+AMP(78)+AMP(79)+AMP(80)
     $ +AMP(81)+AMP(82)+AMP(83)+AMP(84)+AMP(85)+AMP(86)+AMP(87)+AMP(88)
     $ +AMP(89)+AMP(90)+AMP(91)+AMP(92)+AMP(93)+AMP(94)+AMP(95)+AMP(96)
     $ +AMP(97)+AMP(98)+AMP(99)+AMP(100)+AMP(101)+AMP(102)+AMP(103)
     $ +AMP(104)+AMP(105)+AMP(106)+AMP(107)+AMP(108)+AMP(109)+AMP(110)
     $ +AMP(111)+AMP(112)+AMP(113)+AMP(114)+AMP(115)+AMP(116)+AMP(117)
     $ +AMP(118)+AMP(119)+AMP(120)+AMP(121)+AMP(122)+AMP(123)+AMP(124)
     $ +AMP(125)+AMP(126)+AMP(127)+AMP(128)+AMP(129)+AMP(130)+AMP(131)
     $ +AMP(132)+AMP(133)+AMP(134)+AMP(135)+AMP(136)+AMP(137)+AMP(138)
     $ +AMP(139)+AMP(140)+AMP(141)+AMP(142)+AMP(143)+AMP(144)+AMP(145)
     $ +AMP(146)+AMP(147)+AMP(148)+AMP(149)+AMP(150)+AMP(151)+AMP(152)
     $ +AMP(153)+AMP(154)+AMP(155)+AMP(156)+AMP(157)+AMP(158)+AMP(159)
     $ +AMP(160)+AMP(161)+AMP(162)+AMP(163)+AMP(164)+AMP(165)+AMP(166)
     $ +AMP(167)+AMP(168)+AMP(169)+AMP(170)+AMP(171)+AMP(172)+AMP(173)
     $ +AMP(174)+AMP(175)+AMP(176)+AMP(177)+AMP(178)+AMP(179)+AMP(180)
     $ +AMP(181)+AMP(182)+AMP(183)+AMP(184)+AMP(185)+AMP(186)+AMP(187)
     $ +AMP(188)+AMP(189)+AMP(190)+AMP(191)+AMP(192)+AMP(193)+AMP(194)
     $ +AMP(195)+AMP(196)+AMP(197)+AMP(198)+AMP(199)+AMP(200)+AMP(201)
     $ +AMP(202)+AMP(203)+AMP(204)+AMP(205)+AMP(206)+AMP(207)+AMP(208)
     $ +AMP(209)+AMP(210)+AMP(211)+AMP(212)+AMP(213)+AMP(214)+AMP(215)
     $ +AMP(216)+AMP(217)+AMP(218)+AMP(219)+AMP(220)+AMP(221)+AMP(222)
     $ +AMP(223)+AMP(224)+AMP(225)+AMP(226)+AMP(227)+AMP(228)+AMP(229)
     $ +AMP(230)+AMP(231)+AMP(232)+AMP(233)+AMP(234)+AMP(235)+AMP(236)
     $ +AMP(237)+AMP(238)+AMP(239)+AMP(240)+AMP(241)+AMP(242)+AMP(243)
     $ +AMP(244)+AMP(245)+AMP(246)+AMP(247)+AMP(248)+AMP(249)+AMP(250)
     $ +AMP(251)+AMP(252)+AMP(253)+AMP(254)+AMP(255)+AMP(256)+AMP(257)
     $ +AMP(258)+AMP(259)+AMP(260)+AMP(261)+AMP(262)+AMP(263)+AMP(264)
     $ +AMP(265)+AMP(266)+AMP(267)+AMP(268)+AMP(269)+AMP(270)+AMP(271)
     $ +AMP(272)+AMP(273)+AMP(274)+AMP(275)+AMP(276)+AMP(277)+AMP(278)
     $ +AMP(279)+AMP(280)+AMP(281)+AMP(282)+AMP(283)+AMP(284)+AMP(285)
     $ +AMP(286)+AMP(287)+AMP(288)+AMP(289)+AMP(290)+AMP(291)+AMP(292)
     $ +AMP(293)+AMP(294)+AMP(295)+AMP(296)+AMP(297)+AMP(298)+AMP(299)
     $ +AMP(300)+AMP(301)+AMP(302)+AMP(303)+AMP(304)+AMP(305)+AMP(306)
     $ +AMP(307)+AMP(308)+AMP(309)+AMP(310)+AMP(311)+AMP(312)+AMP(313)
     $ +AMP(314)+AMP(315)+AMP(316)+AMP(317)+AMP(318)+AMP(319)+AMP(320)
     $ +AMP(321)+AMP(322)+AMP(323)+AMP(324)+AMP(325)+AMP(326)+AMP(327)
     $ +AMP(328)+AMP(329)+AMP(330)+AMP(331)+AMP(332)+AMP(333)+AMP(334)
     $ +AMP(335)+AMP(336)+AMP(337)+AMP(338)+AMP(339)+AMP(340)+AMP(341)
     $ +AMP(342)+AMP(343)+AMP(344)+AMP(345)+AMP(346)+AMP(347)+AMP(348)
     $ +AMP(349)+AMP(350)+AMP(351)+AMP(352)+AMP(353)+AMP(354)+AMP(355)
     $ +AMP(356)+AMP(357)+AMP(358)+AMP(359)+AMP(360)+AMP(361)+AMP(362)
     $ +AMP(363)+AMP(364)+AMP(365)+AMP(366)+AMP(367)+AMP(368)+AMP(369)
     $ +AMP(370)+AMP(371)+AMP(372)+AMP(373)+AMP(374)+AMP(375)+AMP(376)
     $ +AMP(377)+AMP(378)+AMP(379)+AMP(380)+AMP(381)+AMP(382)+AMP(383)
     $ +AMP(384)+AMP(385)+AMP(386)+AMP(387)+AMP(388)+AMP(389)+AMP(390)
     $ +AMP(391)+AMP(392)+AMP(393)+AMP(394)+AMP(395)+AMP(396)+AMP(397)
     $ +AMP(398)+AMP(399)+AMP(400)+AMP(401)+AMP(402)+AMP(403)+AMP(404)
     $ +AMP(405)+AMP(406)+AMP(407)+AMP(408)+AMP(409)+AMP(410)+AMP(411)
     $ +AMP(412)+AMP(413)+AMP(414)+AMP(415)+AMP(416)+AMP(417)+AMP(418)
     $ +AMP(419)+AMP(420)+AMP(421)+AMP(422)+AMP(423)+AMP(424)+AMP(425)
     $ +AMP(426)+AMP(427)+AMP(428)+AMP(429)+AMP(430)+AMP(431)+AMP(432)
     $ +AMP(433)+AMP(434)+AMP(435)+AMP(436)+AMP(437)+AMP(438)+AMP(439)
     $ +AMP(440)+AMP(441)+AMP(442)+AMP(443)+AMP(444)+AMP(445)+AMP(446)
     $ +AMP(447)+AMP(448)+AMP(449)+AMP(450)+AMP(451)+AMP(452)+AMP(453)
     $ +AMP(454)+AMP(455)+AMP(456)+AMP(457)+AMP(458)+AMP(459)+AMP(460)
     $ +AMP(461)+AMP(462)+AMP(463)+AMP(464)+AMP(465)+AMP(466)+AMP(467)
     $ +AMP(468)+AMP(469)+AMP(470)+AMP(471)+AMP(472)+AMP(473)+AMP(474)
     $ +AMP(475)+AMP(476)+AMP(477)+AMP(478)+AMP(479)+AMP(480)+AMP(481)
     $ +AMP(482)+AMP(483)+AMP(484)+AMP(485)+AMP(486)+AMP(487)+AMP(488)
     $ +AMP(489)+AMP(490)+AMP(491)+AMP(492)+AMP(493)+AMP(494)+AMP(495)
     $ +AMP(496)+AMP(497)+AMP(498)+AMP(499)+AMP(500)+AMP(501)+AMP(502)
     $ +AMP(503)+AMP(504)+AMP(505)+AMP(506)+AMP(507)+AMP(508)+AMP(509)
     $ +AMP(510)+AMP(511)+AMP(512)+AMP(513)+AMP(514)+AMP(515)+AMP(516)
     $ +AMP(517)+AMP(518)+AMP(519)+AMP(520)+AMP(521)+AMP(522)+AMP(523)
     $ +AMP(524)+AMP(525)+AMP(526)+AMP(527)+AMP(528)+AMP(529)+AMP(530)
     $ +AMP(531)+AMP(532)+AMP(533)+AMP(534)+AMP(535)+AMP(536)+AMP(537)
     $ +AMP(538)+AMP(539)+AMP(540)+AMP(541)+AMP(542)+AMP(543)+AMP(544)
     $ +AMP(545)+AMP(546)+AMP(547)+AMP(548)+AMP(549)+AMP(550)+AMP(551)
     $ +AMP(552)+AMP(553)+AMP(554)+AMP(555)+AMP(556)+AMP(557)+AMP(558)
     $ +AMP(559)+AMP(560)+AMP(561)+AMP(562)+AMP(563)+AMP(564)+AMP(565)
     $ +AMP(566)+AMP(567)+AMP(568)+AMP(569)+AMP(570)+AMP(571)+AMP(572)
     $ +AMP(573)+AMP(574)+AMP(575)+AMP(576)+AMP(577)+AMP(578)+AMP(579)
     $ +AMP(580)+AMP(581)+AMP(582)+AMP(583)+AMP(584)+AMP(585)+AMP(586)
     $ +AMP(587)+AMP(588)+AMP(589)+AMP(590)+AMP(591)+AMP(592)+AMP(593)
     $ +AMP(594)+AMP(595)+AMP(596)+AMP(597)+AMP(598)+AMP(599)+AMP(600)
     $ +AMP(601)

      M46_MATRIX = 0.D0
      DO I = 1, NCOLOR
        ZTEMP = (0.D0,0.D0)
        DO J = 1, NCOLOR
          ZTEMP = ZTEMP + CF(J,I)*JAMP(J)
        ENDDO
        M46_MATRIX = M46_MATRIX+ZTEMP*DCONJG(JAMP(I))/DENOM(I)
      ENDDO

      END

      SUBROUTINE M46_GET_VALUE(P, ALPHAS, NHEL ,ANS)
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=5)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
      INTEGER NHEL
      DOUBLE PRECISION ALPHAS
      REAL*8 PI
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: NHEL
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
CF2PY INTENT(IN) :: ALPHAS
C     ROUTINE FOR F2PY to read the benchmark point.    
C     the include file with the values of the parameters and masses 
      INCLUDE 'coupl.inc'

      PI = 3.141592653589793D0
      G = 2* DSQRT(ALPHAS*PI)
      CALL UPDATE_AS_PARAM()
      IF (NHEL.NE.0) THEN
        CALL M46_SMATRIXHEL(P, NHEL, ANS)
      ELSE
        CALL M46_SMATRIX(P, ANS)
      ENDIF
      RETURN
      END

      SUBROUTINE M46_INITIALISEMODEL(PATH)
C     ROUTINE FOR F2PY to read the benchmark point.    
      IMPLICIT NONE
      CHARACTER*512 PATH
CF2PY INTENT(IN) :: PATH
      CALL SETPARA(PATH)  !first call to setup the paramaters    
      RETURN
      END

      LOGICAL FUNCTION M46_IS_BORN_HEL_SELECTED(HELID)
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=5)
      INTEGER    NCOMB
      PARAMETER (NCOMB=16)
C     
C     ARGUMENTS
C     
      INTEGER HELID
C     
C     LOCALS
C     
      INTEGER I,J
      LOGICAL FOUNDIT
C     
C     GLOBALS
C     
      INTEGER HELC(NEXTERNAL,NCOMB)
      COMMON/M46_PROCESS_NHEL/HELC

      INTEGER POLARIZATIONS(0:NEXTERNAL,0:5)
      COMMON/M46_BORN_BEAM_POL/POLARIZATIONS
C     ----------
C     BEGIN CODE
C     ----------

      M46_IS_BORN_HEL_SELECTED = .TRUE.
      IF (POLARIZATIONS(0,0).EQ.-1) THEN
        RETURN
      ENDIF

      DO I=1,NEXTERNAL
        IF (POLARIZATIONS(I,0).EQ.-1) THEN
          CYCLE
        ENDIF
        FOUNDIT = .FALSE.
        DO J=1,POLARIZATIONS(I,0)
          IF (HELC(I,HELID).EQ.POLARIZATIONS(I,J)) THEN
            FOUNDIT = .TRUE.
            EXIT
          ENDIF
        ENDDO
        IF(.NOT.FOUNDIT) THEN
          M46_IS_BORN_HEL_SELECTED = .FALSE.
          RETURN
        ENDIF
      ENDDO

      RETURN
      END

