ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      SUBROUTINE COUP11()

      IMPLICIT NONE
      INCLUDE 'model_functions.inc'

      DOUBLE PRECISION PI, ZERO
      PARAMETER  (PI=3.141592653589793D0)
      PARAMETER  (ZERO=0D0)
      INCLUDE 'input.inc'
      INCLUDE 'coupl.inc'
      GC_859 = -((MDL_CDBIM*MDL_CTH*MDL_YS)/(MDL_LAMBDASMEFT__EXP__2
     $ *MDL_SQRT__2))
      GC_860 = (MDL_CDBRE*MDL_CTH*MDL_COMPLEXI*MDL_YS)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_861 = (MDL_CDWIM*MDL_CTH*MDL_YS)/(MDL_LAMBDASMEFT__EXP__2
     $ *MDL_SQRT__2)
      GC_862 = -((MDL_CDWRE*MDL_CTH*MDL_COMPLEXI*MDL_YS)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_868 = -((MDL_COMPLEXI*MDL_PROPCORR*MDL_YS)/MDL_SQRT__2)
      GC_874 = (MDL_CDBIM*MDL_STH*MDL_YS)/(MDL_LAMBDASMEFT__EXP__2
     $ *MDL_SQRT__2)
      GC_875 = -((MDL_CDBRE*MDL_COMPLEXI*MDL_STH*MDL_YS)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_876 = (MDL_CDWIM*MDL_STH*MDL_YS)/(MDL_LAMBDASMEFT__EXP__2
     $ *MDL_SQRT__2)
      GC_877 = -((MDL_CDWRE*MDL_COMPLEXI*MDL_STH*MDL_YS)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_878 = -((MDL_CDGIM*MDL_VEVHAT*MDL_YS)/(MDL_LAMBDASMEFT__EXP__2
     $ *MDL_SQRT__2))
      GC_879 = (MDL_CDGRE*MDL_COMPLEXI*MDL_VEVHAT*MDL_YS)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_880 = (-3.000000D+00*MDL_CDHIM*MDL_VEVHAT*MDL_YS)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_881 = (3.000000D+00*MDL_CDHRE*MDL_COMPLEXI*MDL_VEVHAT*MDL_YS)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_885 = -((MDL_CDBIM*MDL_CTH*MDL_VEVHAT*MDL_YS)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_886 = (MDL_CDBRE*MDL_CTH*MDL_COMPLEXI*MDL_VEVHAT*MDL_YS)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_887 = (MDL_CDWIM*MDL_CTH*MDL_VEVHAT*MDL_YS)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_888 = -((MDL_CDWRE*MDL_CTH*MDL_COMPLEXI*MDL_VEVHAT*MDL_YS)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_899 = (MDL_CDBIM*MDL_STH*MDL_VEVHAT*MDL_YS)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_900 = -((MDL_CDBRE*MDL_COMPLEXI*MDL_STH*MDL_VEVHAT*MDL_YS)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_901 = (MDL_CDWIM*MDL_STH*MDL_VEVHAT*MDL_YS)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_902 = -((MDL_CDWRE*MDL_COMPLEXI*MDL_STH*MDL_VEVHAT*MDL_YS)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_903 = -((MDL_CDHIM*MDL_VEVHAT__EXP__2*MDL_YS)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_904 = (MDL_CDHRE*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YS)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_905 = -((MDL_CHBOX*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YS)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_906 = (MDL_CHDD*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YS)
     $ /(4.000000D+00*MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      END
