ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      SUBROUTINE COUP6()

      IMPLICIT NONE
      INCLUDE 'model_functions.inc'

      DOUBLE PRECISION PI, ZERO
      PARAMETER  (PI=3.141592653589793D0)
      PARAMETER  (ZERO=0D0)
      INCLUDE 'input.inc'
      INCLUDE 'coupl.inc'
      GC_538 = -((MDL_CUGIM*MDL_VEVHAT*MDL_YC)/(MDL_LAMBDASMEFT__EXP__2
     $ *MDL_SQRT__2))
      GC_539 = (MDL_CUGRE*MDL_COMPLEXI*MDL_VEVHAT*MDL_YC)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_540 = (-3.000000D+00*MDL_CUHIM*MDL_VEVHAT*MDL_YC)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_541 = (3.000000D+00*MDL_CUHRE*MDL_COMPLEXI*MDL_VEVHAT*MDL_YC)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_544 = -((MDL_CTH*MDL_CUWIM*MDL_VEVHAT*MDL_YC)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_546 = (MDL_CTH*MDL_CUWRE*MDL_COMPLEXI*MDL_VEVHAT*MDL_YC)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_557 = (MDL_CUBIM*MDL_STH*MDL_VEVHAT*MDL_YC)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_558 = -((MDL_CUBRE*MDL_COMPLEXI*MDL_STH*MDL_VEVHAT*MDL_YC)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_559 = -((MDL_CUWIM*MDL_STH*MDL_VEVHAT*MDL_YC)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_560 = (MDL_CUWRE*MDL_COMPLEXI*MDL_STH*MDL_VEVHAT*MDL_YC)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_561 = -((MDL_CHBOX*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YC)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_562 = (MDL_CHDD*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YC)
     $ /(4.000000D+00*MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_563 = (MDL_CHL3*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YC)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_564 = -(MDL_CLL1*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YC)
     $ /(2.000000D+00*MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_565 = -((MDL_CUHIM*MDL_VEVHAT__EXP__2*MDL_YC)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_566 = (MDL_CUHRE*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YC)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_585 = -((MDL_COMPLEXI*MDL_YDO)/MDL_SQRT__2)
      GC_586 = -((MDL_CDGIM*MDL_YDO)/(MDL_LAMBDASMEFT__EXP__2
     $ *MDL_SQRT__2))
      GC_587 = (MDL_CDGRE*MDL_COMPLEXI*MDL_YDO)/(MDL_LAMBDASMEFT__EXP__
     $2*MDL_SQRT__2)
      GC_593 = -((MDL_CDBIM*MDL_CTH*MDL_YDO)/(MDL_LAMBDASMEFT__EXP__2
     $ *MDL_SQRT__2))
      GC_594 = (MDL_CDBRE*MDL_CTH*MDL_COMPLEXI*MDL_YDO)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_595 = (MDL_CDWIM*MDL_CTH*MDL_YDO)/(MDL_LAMBDASMEFT__EXP__2
     $ *MDL_SQRT__2)
      GC_596 = -((MDL_CDWRE*MDL_CTH*MDL_COMPLEXI*MDL_YDO)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_602 = -((MDL_COMPLEXI*MDL_PROPCORR*MDL_YDO)/MDL_SQRT__2)
      GC_608 = (MDL_CDBIM*MDL_STH*MDL_YDO)/(MDL_LAMBDASMEFT__EXP__2
     $ *MDL_SQRT__2)
      END
