ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      SUBROUTINE COUP8()

      IMPLICIT NONE
      INCLUDE 'model_functions.inc'

      DOUBLE PRECISION PI, ZERO
      PARAMETER  (PI=3.141592653589793D0)
      PARAMETER  (ZERO=0D0)
      INCLUDE 'input.inc'
      INCLUDE 'coupl.inc'
      GC_670 = -((MDL_CEWRE*MDL_CTH*MDL_COMPLEXI*MDL_YE)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_674 = -((MDL_COMPLEXI*MDL_PROPCORR*MDL_YE)/MDL_SQRT__2)
      GC_680 = (MDL_CEBIM*MDL_STH*MDL_YE)/(MDL_LAMBDASMEFT__EXP__2
     $ *MDL_SQRT__2)
      GC_681 = -((MDL_CEBRE*MDL_COMPLEXI*MDL_STH*MDL_YE)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_682 = (MDL_CEWIM*MDL_STH*MDL_YE)/(MDL_LAMBDASMEFT__EXP__2
     $ *MDL_SQRT__2)
      GC_683 = -((MDL_CEWRE*MDL_COMPLEXI*MDL_STH*MDL_YE)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_684 = (-3.000000D+00*MDL_CEHIM*MDL_VEVHAT*MDL_YE)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_685 = (3.000000D+00*MDL_CEHRE*MDL_COMPLEXI*MDL_VEVHAT*MDL_YE)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_689 = -((MDL_CEBIM*MDL_CTH*MDL_VEVHAT*MDL_YE)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_690 = (MDL_CEBRE*MDL_CTH*MDL_COMPLEXI*MDL_VEVHAT*MDL_YE)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_691 = (MDL_CEWIM*MDL_CTH*MDL_VEVHAT*MDL_YE)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_692 = -((MDL_CEWRE*MDL_CTH*MDL_COMPLEXI*MDL_VEVHAT*MDL_YE)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_701 = (MDL_CEBIM*MDL_STH*MDL_VEVHAT*MDL_YE)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_702 = -((MDL_CEBRE*MDL_COMPLEXI*MDL_STH*MDL_VEVHAT*MDL_YE)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_703 = (MDL_CEWIM*MDL_STH*MDL_VEVHAT*MDL_YE)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_704 = -((MDL_CEWRE*MDL_COMPLEXI*MDL_STH*MDL_VEVHAT*MDL_YE)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_705 = -((MDL_CEHIM*MDL_VEVHAT__EXP__2*MDL_YE)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_706 = (MDL_CEHRE*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YE)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_707 = -((MDL_CHBOX*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YE)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_708 = (MDL_CHDD*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YE)
     $ /(4.000000D+00*MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_709 = (MDL_CHL3*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YE)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_710 = -(MDL_CLL1*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YE)
     $ /(2.000000D+00*MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_720 = -((MDL_CLEQU1IM*MDL_YC*MDL_YE)/MDL_LAMBDASMEFT__EXP__2)
      GC_721 = (MDL_CLEQU1IM*MDL_YC*MDL_YE)/MDL_LAMBDASMEFT__EXP__2
      GC_725 = -((MDL_CLEQU1RE*MDL_COMPLEXI*MDL_YC*MDL_YE)
     $ /MDL_LAMBDASMEFT__EXP__2)
      END
