ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      SUBROUTINE COUP14()

      IMPLICIT NONE
      INCLUDE 'model_functions.inc'

      DOUBLE PRECISION PI, ZERO
      PARAMETER  (PI=3.141592653589793D0)
      PARAMETER  (ZERO=0D0)
      INCLUDE 'input.inc'
      INCLUDE 'coupl.inc'
      GC_1245 = -((MDL_CTH*MDL_CUBIM*MDL_YUP)/(MDL_LAMBDASMEFT__EXP__2
     $ *MDL_SQRT__2))
      GC_1246 = (MDL_CTH*MDL_CUBRE*MDL_COMPLEXI*MDL_YUP)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_1247 = -((MDL_CUGIM*MDL_YUP)/(MDL_LAMBDASMEFT__EXP__2
     $ *MDL_SQRT__2))
      GC_1248 = (MDL_CUGRE*MDL_COMPLEXI*MDL_YUP)/(MDL_LAMBDASMEFT__EXP_
     $_2*MDL_SQRT__2)
      GC_1253 = -((MDL_CTH*MDL_CUWIM*MDL_YUP)/(MDL_LAMBDASMEFT__EXP__2
     $ *MDL_SQRT__2))
      GC_1255 = (MDL_CTH*MDL_CUWRE*MDL_COMPLEXI*MDL_YUP)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_1261 = -((MDL_COMPLEXI*MDL_PROPCORR*MDL_YUP)/MDL_SQRT__2)
      GC_1267 = (MDL_CUBIM*MDL_STH*MDL_YUP)/(MDL_LAMBDASMEFT__EXP__2
     $ *MDL_SQRT__2)
      GC_1268 = -((MDL_CUBRE*MDL_COMPLEXI*MDL_STH*MDL_YUP)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_1269 = -((MDL_CUWIM*MDL_STH*MDL_YUP)/(MDL_LAMBDASMEFT__EXP__2
     $ *MDL_SQRT__2))
      GC_1270 = (MDL_CUWRE*MDL_COMPLEXI*MDL_STH*MDL_YUP)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_1271 = -((MDL_CTH*MDL_CUBIM*MDL_VEVHAT*MDL_YUP)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_1272 = (MDL_CTH*MDL_CUBRE*MDL_COMPLEXI*MDL_VEVHAT*MDL_YUP)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_1273 = -((MDL_CUGIM*MDL_VEVHAT*MDL_YUP)/(MDL_LAMBDASMEFT__EXP_
     $_2*MDL_SQRT__2))
      GC_1274 = (MDL_CUGRE*MDL_COMPLEXI*MDL_VEVHAT*MDL_YUP)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_1275 = (-3.000000D+00*MDL_CUHIM*MDL_VEVHAT*MDL_YUP)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_1276 = (3.000000D+00*MDL_CUHRE*MDL_COMPLEXI*MDL_VEVHAT
     $ *MDL_YUP)/(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_1279 = -((MDL_CTH*MDL_CUWIM*MDL_VEVHAT*MDL_YUP)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_1281 = (MDL_CTH*MDL_CUWRE*MDL_COMPLEXI*MDL_VEVHAT*MDL_YUP)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_1292 = (MDL_CUBIM*MDL_STH*MDL_VEVHAT*MDL_YUP)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_1293 = -((MDL_CUBRE*MDL_COMPLEXI*MDL_STH*MDL_VEVHAT*MDL_YUP)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_1294 = -((MDL_CUWIM*MDL_STH*MDL_VEVHAT*MDL_YUP)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_1295 = (MDL_CUWRE*MDL_COMPLEXI*MDL_STH*MDL_VEVHAT*MDL_YUP)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_1296 = -((MDL_CHBOX*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YUP)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_1297 = (MDL_CHDD*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YUP)
     $ /(4.000000D+00*MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      END
