ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      SUBROUTINE COUP9()

      IMPLICIT NONE
      INCLUDE 'model_functions.inc'

      DOUBLE PRECISION PI, ZERO
      PARAMETER  (PI=3.141592653589793D0)
      PARAMETER  (ZERO=0D0)
      INCLUDE 'input.inc'
      INCLUDE 'coupl.inc'
      GC_729 = -(MDL_CLEQU3IM*MDL_YC*MDL_YE)/(2.000000D+00
     $ *MDL_LAMBDASMEFT__EXP__2)
      GC_730 = -(MDL_CLEQU3IM*MDL_YC*MDL_YE)/(4.000000D+00
     $ *MDL_LAMBDASMEFT__EXP__2)
      GC_731 = (MDL_CLEQU3IM*MDL_YC*MDL_YE)/(4.000000D+00
     $ *MDL_LAMBDASMEFT__EXP__2)
      GC_732 = (MDL_CLEQU3IM*MDL_YC*MDL_YE)/(2.000000D+00
     $ *MDL_LAMBDASMEFT__EXP__2)
      GC_739 = -(MDL_CLEQU3RE*MDL_COMPLEXI*MDL_YC*MDL_YE)/(4.000000D
     $ +00*MDL_LAMBDASMEFT__EXP__2)
      GC_740 = (MDL_CLEQU3RE*MDL_COMPLEXI*MDL_YC*MDL_YE)/(2.000000D+00
     $ *MDL_LAMBDASMEFT__EXP__2)
      GC_747 = -((MDL_CLEDQIM*MDL_YDO*MDL_YE)/MDL_LAMBDASMEFT__EXP__2)
      GC_748 = (MDL_CLEDQIM*MDL_YDO*MDL_YE)/MDL_LAMBDASMEFT__EXP__2
      GC_752 = (MDL_CLEDQRE*MDL_COMPLEXI*MDL_YDO*MDL_YE)
     $ /MDL_LAMBDASMEFT__EXP__2
      GC_756 = -((MDL_COMPLEXI*MDL_YM)/MDL_SQRT__2)
      GC_762 = -((MDL_CEBIM*MDL_CTH*MDL_YM)/(MDL_LAMBDASMEFT__EXP__2
     $ *MDL_SQRT__2))
      GC_763 = (MDL_CEBRE*MDL_CTH*MDL_COMPLEXI*MDL_YM)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_764 = (MDL_CEWIM*MDL_CTH*MDL_YM)/(MDL_LAMBDASMEFT__EXP__2
     $ *MDL_SQRT__2)
      GC_765 = -((MDL_CEWRE*MDL_CTH*MDL_COMPLEXI*MDL_YM)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_769 = -((MDL_COMPLEXI*MDL_PROPCORR*MDL_YM)/MDL_SQRT__2)
      GC_775 = (MDL_CEBIM*MDL_STH*MDL_YM)/(MDL_LAMBDASMEFT__EXP__2
     $ *MDL_SQRT__2)
      GC_776 = -((MDL_CEBRE*MDL_COMPLEXI*MDL_STH*MDL_YM)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_777 = (MDL_CEWIM*MDL_STH*MDL_YM)/(MDL_LAMBDASMEFT__EXP__2
     $ *MDL_SQRT__2)
      GC_778 = -((MDL_CEWRE*MDL_COMPLEXI*MDL_STH*MDL_YM)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_779 = (-3.000000D+00*MDL_CEHIM*MDL_VEVHAT*MDL_YM)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_780 = (3.000000D+00*MDL_CEHRE*MDL_COMPLEXI*MDL_VEVHAT*MDL_YM)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_784 = -((MDL_CEBIM*MDL_CTH*MDL_VEVHAT*MDL_YM)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_785 = (MDL_CEBRE*MDL_CTH*MDL_COMPLEXI*MDL_VEVHAT*MDL_YM)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_786 = (MDL_CEWIM*MDL_CTH*MDL_VEVHAT*MDL_YM)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_787 = -((MDL_CEWRE*MDL_CTH*MDL_COMPLEXI*MDL_VEVHAT*MDL_YM)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      END
