ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      SUBROUTINE COUP10()

      IMPLICIT NONE
      INCLUDE 'model_functions.inc'

      DOUBLE PRECISION PI, ZERO
      PARAMETER  (PI=3.141592653589793D0)
      PARAMETER  (ZERO=0D0)
      INCLUDE 'input.inc'
      INCLUDE 'coupl.inc'
      GC_796 = (MDL_CEBIM*MDL_STH*MDL_VEVHAT*MDL_YM)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_797 = -((MDL_CEBRE*MDL_COMPLEXI*MDL_STH*MDL_VEVHAT*MDL_YM)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_798 = (MDL_CEWIM*MDL_STH*MDL_VEVHAT*MDL_YM)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_799 = -((MDL_CEWRE*MDL_COMPLEXI*MDL_STH*MDL_VEVHAT*MDL_YM)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_800 = -((MDL_CEHIM*MDL_VEVHAT__EXP__2*MDL_YM)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_801 = (MDL_CEHRE*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YM)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_802 = -((MDL_CHBOX*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YM)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_803 = (MDL_CHDD*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YM)
     $ /(4.000000D+00*MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_804 = (MDL_CHL3*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YM)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_805 = -(MDL_CLL1*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YM)
     $ /(2.000000D+00*MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_815 = -((MDL_CLEQU1IM*MDL_YC*MDL_YM)/MDL_LAMBDASMEFT__EXP__2)
      GC_816 = (MDL_CLEQU1IM*MDL_YC*MDL_YM)/MDL_LAMBDASMEFT__EXP__2
      GC_820 = -((MDL_CLEQU1RE*MDL_COMPLEXI*MDL_YC*MDL_YM)
     $ /MDL_LAMBDASMEFT__EXP__2)
      GC_824 = -(MDL_CLEQU3IM*MDL_YC*MDL_YM)/(2.000000D+00
     $ *MDL_LAMBDASMEFT__EXP__2)
      GC_825 = -(MDL_CLEQU3IM*MDL_YC*MDL_YM)/(4.000000D+00
     $ *MDL_LAMBDASMEFT__EXP__2)
      GC_826 = (MDL_CLEQU3IM*MDL_YC*MDL_YM)/(4.000000D+00
     $ *MDL_LAMBDASMEFT__EXP__2)
      GC_827 = (MDL_CLEQU3IM*MDL_YC*MDL_YM)/(2.000000D+00
     $ *MDL_LAMBDASMEFT__EXP__2)
      GC_834 = -(MDL_CLEQU3RE*MDL_COMPLEXI*MDL_YC*MDL_YM)/(4.000000D
     $ +00*MDL_LAMBDASMEFT__EXP__2)
      GC_835 = (MDL_CLEQU3RE*MDL_COMPLEXI*MDL_YC*MDL_YM)/(2.000000D+00
     $ *MDL_LAMBDASMEFT__EXP__2)
      GC_842 = -((MDL_CLEDQIM*MDL_YDO*MDL_YM)/MDL_LAMBDASMEFT__EXP__2)
      GC_843 = (MDL_CLEDQIM*MDL_YDO*MDL_YM)/MDL_LAMBDASMEFT__EXP__2
      GC_847 = (MDL_CLEDQRE*MDL_COMPLEXI*MDL_YDO*MDL_YM)
     $ /MDL_LAMBDASMEFT__EXP__2
      GC_851 = -((MDL_COMPLEXI*MDL_YS)/MDL_SQRT__2)
      GC_852 = -((MDL_CDGIM*MDL_YS)/(MDL_LAMBDASMEFT__EXP__2
     $ *MDL_SQRT__2))
      GC_853 = (MDL_CDGRE*MDL_COMPLEXI*MDL_YS)/(MDL_LAMBDASMEFT__EXP__2
     $ *MDL_SQRT__2)
      END
