ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      SUBROUTINE COUP13()

      IMPLICIT NONE
      INCLUDE 'model_functions.inc'

      DOUBLE PRECISION PI, ZERO
      PARAMETER  (PI=3.141592653589793D0)
      PARAMETER  (ZERO=0D0)
      INCLUDE 'input.inc'
      INCLUDE 'coupl.inc'
      GC_1154 = -((MDL_CEBRE*MDL_COMPLEXI*MDL_STH*MDL_VEVHAT*MDL_YTAU)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_1155 = (MDL_CEWIM*MDL_STH*MDL_VEVHAT*MDL_YTAU)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_1156 = -((MDL_CEWRE*MDL_COMPLEXI*MDL_STH*MDL_VEVHAT*MDL_YTAU)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_1157 = -((MDL_CEHIM*MDL_VEVHAT__EXP__2*MDL_YTAU)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_1158 = (MDL_CEHRE*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YTAU)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_1159 = -((MDL_CHBOX*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YTAU)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_1160 = (MDL_CHDD*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YTAU)
     $ /(4.000000D+00*MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_1161 = (MDL_CHL3*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YTAU)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_1162 = -(MDL_CLL1*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YTAU)
     $ /(2.000000D+00*MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_1172 = -((MDL_CLEQU1IM*MDL_YC*MDL_YTAU)/MDL_LAMBDASMEFT__EXP__
     $2)
      GC_1173 = (MDL_CLEQU1IM*MDL_YC*MDL_YTAU)/MDL_LAMBDASMEFT__EXP__2
      GC_1177 = -((MDL_CLEQU1RE*MDL_COMPLEXI*MDL_YC*MDL_YTAU)
     $ /MDL_LAMBDASMEFT__EXP__2)
      GC_1181 = -(MDL_CLEQU3IM*MDL_YC*MDL_YTAU)/(2.000000D+00
     $ *MDL_LAMBDASMEFT__EXP__2)
      GC_1182 = -(MDL_CLEQU3IM*MDL_YC*MDL_YTAU)/(4.000000D+00
     $ *MDL_LAMBDASMEFT__EXP__2)
      GC_1183 = (MDL_CLEQU3IM*MDL_YC*MDL_YTAU)/(4.000000D+00
     $ *MDL_LAMBDASMEFT__EXP__2)
      GC_1184 = (MDL_CLEQU3IM*MDL_YC*MDL_YTAU)/(2.000000D+00
     $ *MDL_LAMBDASMEFT__EXP__2)
      GC_1191 = -(MDL_CLEQU3RE*MDL_COMPLEXI*MDL_YC*MDL_YTAU)
     $ /(4.000000D+00*MDL_LAMBDASMEFT__EXP__2)
      GC_1192 = (MDL_CLEQU3RE*MDL_COMPLEXI*MDL_YC*MDL_YTAU)/(2.000000D
     $ +00*MDL_LAMBDASMEFT__EXP__2)
      GC_1199 = -((MDL_CLEDQIM*MDL_YDO*MDL_YTAU)/MDL_LAMBDASMEFT__EXP__
     $2)
      GC_1200 = (MDL_CLEDQIM*MDL_YDO*MDL_YTAU)/MDL_LAMBDASMEFT__EXP__2
      GC_1204 = (MDL_CLEDQRE*MDL_COMPLEXI*MDL_YDO*MDL_YTAU)
     $ /MDL_LAMBDASMEFT__EXP__2
      GC_1208 = -((MDL_CLEDQIM*MDL_YS*MDL_YTAU)/MDL_LAMBDASMEFT__EXP__2)
     $ 
      GC_1209 = (MDL_CLEDQIM*MDL_YS*MDL_YTAU)/MDL_LAMBDASMEFT__EXP__2
      GC_1213 = (MDL_CLEDQRE*MDL_COMPLEXI*MDL_YS*MDL_YTAU)
     $ /MDL_LAMBDASMEFT__EXP__2
      GC_1244 = -((MDL_COMPLEXI*MDL_YUP)/MDL_SQRT__2)
      END
