      SUBROUTINE M51_SMATRIXHEL(P,HEL,ANS)
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=5)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=16)
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: HEL
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)

C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
      INTEGER HEL
C     
C     GLOBAL VARIABLES
C     
      INTEGER USERHEL
      COMMON/M51_HELUSERCHOICE/USERHEL
C     ----------
C     BEGIN CODE
C     ----------
      USERHEL=HEL
      CALL M51_SMATRIX(P,ANS)
      USERHEL=-1

      END

      SUBROUTINE M51_SMATRIX(P,ANS)
C     
C     Generated by MadGraph5_aMC@NLO v. 2.6.7, 2019-10-16
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     MadGraph5_aMC@NLO StandAlone Version
C     
C     Returns amplitude squared summed/avg over colors
C     and helicities
C     for the point in phase space P(0:3,NEXTERNAL)
C     
C     Process: g g > h e+ e- NP<=1 @1
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=5)
      INTEGER    NINITIAL
      PARAMETER (NINITIAL=2)
      INTEGER NPOLENTRIES
      PARAMETER (NPOLENTRIES=(NEXTERNAL+1)*6)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=16)
      INTEGER HELAVGFACTOR
      PARAMETER (HELAVGFACTOR=4)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
C     
C     LOCAL VARIABLES 
C     
      INTEGER NHEL(NEXTERNAL,NCOMB),NTRY
C     put in common block to expose this variable to python interface
      COMMON/M51_PROCESS_NHEL/NHEL
      REAL*8 T
      REAL*8 M51_MATRIX
      INTEGER IHEL,IDEN, I, J
C     For a 1>N process, them BEAMTWO_HELAVGFACTOR would be set to 1.
      INTEGER BEAMS_HELAVGFACTOR(2)
      DATA (BEAMS_HELAVGFACTOR(I),I=1,2)/2,2/
      INTEGER JC(NEXTERNAL)
      LOGICAL GOODHEL(NCOMB)
      DATA NTRY/0/
      DATA GOODHEL/NCOMB*.FALSE./

C     
C     GLOBAL VARIABLES
C     
      INTEGER USERHEL
      COMMON/M51_HELUSERCHOICE/USERHEL
      DATA USERHEL/-1/

      DATA (NHEL(I,   1),I=1,5) /-1,-1, 0, 1,-1/
      DATA (NHEL(I,   2),I=1,5) /-1,-1, 0, 1, 1/
      DATA (NHEL(I,   3),I=1,5) /-1,-1, 0,-1,-1/
      DATA (NHEL(I,   4),I=1,5) /-1,-1, 0,-1, 1/
      DATA (NHEL(I,   5),I=1,5) /-1, 1, 0, 1,-1/
      DATA (NHEL(I,   6),I=1,5) /-1, 1, 0, 1, 1/
      DATA (NHEL(I,   7),I=1,5) /-1, 1, 0,-1,-1/
      DATA (NHEL(I,   8),I=1,5) /-1, 1, 0,-1, 1/
      DATA (NHEL(I,   9),I=1,5) / 1,-1, 0, 1,-1/
      DATA (NHEL(I,  10),I=1,5) / 1,-1, 0, 1, 1/
      DATA (NHEL(I,  11),I=1,5) / 1,-1, 0,-1,-1/
      DATA (NHEL(I,  12),I=1,5) / 1,-1, 0,-1, 1/
      DATA (NHEL(I,  13),I=1,5) / 1, 1, 0, 1,-1/
      DATA (NHEL(I,  14),I=1,5) / 1, 1, 0, 1, 1/
      DATA (NHEL(I,  15),I=1,5) / 1, 1, 0,-1,-1/
      DATA (NHEL(I,  16),I=1,5) / 1, 1, 0,-1, 1/
      DATA IDEN/256/

      INTEGER POLARIZATIONS(0:NEXTERNAL,0:5)
      COMMON/M51_BORN_BEAM_POL/POLARIZATIONS
      DATA ((POLARIZATIONS(I,J),I=0,NEXTERNAL),J=0,5)/NPOLENTRIES*-1/

C     
C     FUNCTIONS
C     
      LOGICAL M51_IS_BORN_HEL_SELECTED

C     ----------
C     BEGIN CODE
C     ----------
      IF(USERHEL.EQ.-1) NTRY=NTRY+1
      DO IHEL=1,NEXTERNAL
        JC(IHEL) = +1
      ENDDO
C     When spin-2 particles are involved, the Helicity filtering is
C      dangerous for the 2->1 topology.
C     This is because depending on the MC setup the initial PS points
C      have back-to-back initial states
C     for which some of the spin-2 helicity configurations are zero.
C      But they are no longer zero
C     if the point is boosted on the z-axis. Remember that HELAS
C      helicity amplitudes are no longer
C     lorentz invariant with expternal spin-2 particles (only the
C      helicity sum is).
C     For this reason, we simply remove the filterin when there is
C      only three external particles.
      IF (NEXTERNAL.LE.3) THEN
        DO IHEL=1,NCOMB
          GOODHEL(IHEL)=.TRUE.
        ENDDO
      ENDIF
      ANS = 0D0
      DO IHEL=1,NCOMB
        IF (USERHEL.EQ.-1.OR.USERHEL.EQ.IHEL) THEN
          IF (GOODHEL(IHEL) .OR. NTRY .LT. 20.OR.USERHEL.NE.-1) THEN
            IF(NTRY.GE.2.AND.POLARIZATIONS(0,0).NE.
     $       -1.AND.(.NOT.M51_IS_BORN_HEL_SELECTED(IHEL))) THEN
              CYCLE
            ENDIF
            T=M51_MATRIX(P ,NHEL(1,IHEL),JC(1))
            IF(POLARIZATIONS(0,0).EQ.-1.OR.M51_IS_BORN_HEL_SELECTED(IHE
     $L)) THEN
              ANS=ANS+T
            ENDIF
            IF (T .NE. 0D0 .AND. .NOT.    GOODHEL(IHEL)) THEN
              GOODHEL(IHEL)=.TRUE.
            ENDIF
          ENDIF
        ENDIF
      ENDDO
      ANS=ANS/DBLE(IDEN)
      IF(USERHEL.NE.-1) THEN
        ANS=ANS*HELAVGFACTOR
      ELSE
        DO J=1,NINITIAL
          IF (POLARIZATIONS(J,0).NE.-1) THEN
            ANS=ANS*BEAMS_HELAVGFACTOR(J)
            ANS=ANS/POLARIZATIONS(J,0)
          ENDIF
        ENDDO
      ENDIF
      END


      REAL*8 FUNCTION M51_MATRIX(P,NHEL,IC)
C     
C     Generated by MadGraph5_aMC@NLO v. 2.6.7, 2019-10-16
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Returns amplitude squared summed/avg over colors
C     for the point with external lines W(0:6,NEXTERNAL)
C     
C     Process: g g > h e+ e- NP<=1 @1
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=103)
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=5)
      INTEGER    NWAVEFUNCS, NCOLOR
      PARAMETER (NWAVEFUNCS=17, NCOLOR=1)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
      COMPLEX*16 IMAG1
      PARAMETER (IMAG1=(0D0,1D0))
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL), IC(NEXTERNAL)
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,J
      COMPLEX*16 ZTEMP
      REAL*8 DENOM(NCOLOR), CF(NCOLOR,NCOLOR)
      COMPLEX*16 AMP(NGRAPHS), JAMP(NCOLOR)
      COMPLEX*16 W(20,NWAVEFUNCS)
      COMPLEX*16 DUM0,DUM1
      DATA DUM0, DUM1/(0D0, 0D0), (1D0, 0D0)/
C     
C     GLOBAL VARIABLES
C     
      INCLUDE 'coupl.inc'

C     
C     COLOR DATA
C     
      DATA DENOM(1)/1/
      DATA (CF(I,  1),I=  1,  1) /    2/
C     1 Tr(1,2)
C     ----------
C     BEGIN CODE
C     ----------
      CALL VXXXXX(P(0,1),ZERO,NHEL(1),-1*IC(1),W(1,1))
      CALL VXXXXX(P(0,2),ZERO,NHEL(2),-1*IC(2),W(1,2))
      CALL SXXXXX(P(0,3),+1*IC(3),W(1,3))
      CALL IXXXXX(P(0,4),MDL_ME,NHEL(4),-1*IC(4),W(1,4))
      CALL OXXXXX(P(0,5),MDL_ME,NHEL(5),+1*IC(5),W(1,5))
      CALL VVS4_5_6_7_3(W(1,1),W(1,2),GC_224,GC_233,GC_237,GC_228
     $ ,MDL_MH,MDL_WH,W(1,6))
      CALL FFS2_2(W(1,4),W(1,3),GC_661,MDL_ME,ZERO,W(1,7))
C     Amplitude(s) for diagram number 1
      CALL FFS2_0(W(1,7),W(1,5),W(1,6),GC_661,AMP(1))
C     Amplitude(s) for diagram number 2
      CALL FFS1_0(W(1,7),W(1,5),W(1,6),GC_705,AMP(2))
C     Amplitude(s) for diagram number 3
      CALL FFS2_0(W(1,7),W(1,5),W(1,6),GC_706,AMP(3))
C     Amplitude(s) for diagram number 4
      CALL FFS2_0(W(1,7),W(1,5),W(1,6),GC_707,AMP(4))
C     Amplitude(s) for diagram number 5
      CALL FFS2_0(W(1,7),W(1,5),W(1,6),GC_708,AMP(5))
C     Amplitude(s) for diagram number 6
      CALL FFS2_0(W(1,7),W(1,5),W(1,6),GC_709,AMP(6))
C     Amplitude(s) for diagram number 7
      CALL FFS2_0(W(1,7),W(1,5),W(1,6),GC_710,AMP(7))
      CALL FFS1_2(W(1,4),W(1,3),GC_705,MDL_ME,ZERO,W(1,8))
C     Amplitude(s) for diagram number 8
      CALL FFS2_0(W(1,8),W(1,5),W(1,6),GC_661,AMP(8))
      CALL FFS2_2(W(1,4),W(1,3),GC_706,MDL_ME,ZERO,W(1,9))
C     Amplitude(s) for diagram number 9
      CALL FFS2_0(W(1,9),W(1,5),W(1,6),GC_661,AMP(9))
      CALL FFS2_2(W(1,4),W(1,3),GC_707,MDL_ME,ZERO,W(1,10))
C     Amplitude(s) for diagram number 10
      CALL FFS2_0(W(1,10),W(1,5),W(1,6),GC_661,AMP(10))
      CALL FFS2_2(W(1,4),W(1,3),GC_708,MDL_ME,ZERO,W(1,11))
C     Amplitude(s) for diagram number 11
      CALL FFS2_0(W(1,11),W(1,5),W(1,6),GC_661,AMP(11))
      CALL FFS2_2(W(1,4),W(1,3),GC_709,MDL_ME,ZERO,W(1,12))
C     Amplitude(s) for diagram number 12
      CALL FFS2_0(W(1,12),W(1,5),W(1,6),GC_661,AMP(12))
      CALL FFS2_2(W(1,4),W(1,3),GC_710,MDL_ME,ZERO,W(1,13))
C     Amplitude(s) for diagram number 13
      CALL FFS2_0(W(1,13),W(1,5),W(1,6),GC_661,AMP(13))
      CALL VVS2_3(W(1,1),W(1,2),GC_265,MDL_MH,MDL_WH,W(1,14))
C     Amplitude(s) for diagram number 14
      CALL FFS2_0(W(1,7),W(1,5),W(1,14),GC_661,AMP(14))
      CALL VVS4_3(W(1,1),W(1,2),GC_264,MDL_MH,MDL_WH,W(1,15))
C     Amplitude(s) for diagram number 15
      CALL FFS2_0(W(1,7),W(1,5),W(1,15),GC_661,AMP(15))
      CALL VVS4_5_6_7PH1_3(W(1,1),W(1,2),GC_242,GC_251,GC_255,GC_246
     $ ,MDL_MH1,MDL_WH1,W(1,16))
C     Amplitude(s) for diagram number 16
      CALL FFS2_0(W(1,7),W(1,5),W(1,16),GC_674,AMP(16))
C     Amplitude(s) for diagram number 17
      CALL FFS2_0(W(1,8),W(1,5),W(1,16),GC_674,AMP(17))
C     Amplitude(s) for diagram number 18
      CALL FFS2_0(W(1,9),W(1,5),W(1,16),GC_674,AMP(18))
C     Amplitude(s) for diagram number 19
      CALL FFS2_0(W(1,10),W(1,5),W(1,16),GC_674,AMP(19))
C     Amplitude(s) for diagram number 20
      CALL FFS2_0(W(1,11),W(1,5),W(1,16),GC_674,AMP(20))
C     Amplitude(s) for diagram number 21
      CALL FFS2_0(W(1,12),W(1,5),W(1,16),GC_674,AMP(21))
C     Amplitude(s) for diagram number 22
      CALL FFS2_0(W(1,13),W(1,5),W(1,16),GC_674,AMP(22))
      CALL FFS2_1(W(1,5),W(1,3),GC_661,MDL_ME,ZERO,W(1,13))
C     Amplitude(s) for diagram number 23
      CALL FFS2_0(W(1,4),W(1,13),W(1,6),GC_661,AMP(23))
C     Amplitude(s) for diagram number 24
      CALL FFS1_0(W(1,4),W(1,13),W(1,6),GC_705,AMP(24))
C     Amplitude(s) for diagram number 25
      CALL FFS2_0(W(1,4),W(1,13),W(1,6),GC_706,AMP(25))
C     Amplitude(s) for diagram number 26
      CALL FFS2_0(W(1,4),W(1,13),W(1,6),GC_707,AMP(26))
C     Amplitude(s) for diagram number 27
      CALL FFS2_0(W(1,4),W(1,13),W(1,6),GC_708,AMP(27))
C     Amplitude(s) for diagram number 28
      CALL FFS2_0(W(1,4),W(1,13),W(1,6),GC_709,AMP(28))
C     Amplitude(s) for diagram number 29
      CALL FFS2_0(W(1,4),W(1,13),W(1,6),GC_710,AMP(29))
      CALL FFS1_1(W(1,5),W(1,3),GC_705,MDL_ME,ZERO,W(1,12))
C     Amplitude(s) for diagram number 30
      CALL FFS2_0(W(1,4),W(1,12),W(1,6),GC_661,AMP(30))
      CALL FFS2_1(W(1,5),W(1,3),GC_706,MDL_ME,ZERO,W(1,11))
C     Amplitude(s) for diagram number 31
      CALL FFS2_0(W(1,4),W(1,11),W(1,6),GC_661,AMP(31))
      CALL FFS2_1(W(1,5),W(1,3),GC_707,MDL_ME,ZERO,W(1,10))
C     Amplitude(s) for diagram number 32
      CALL FFS2_0(W(1,4),W(1,10),W(1,6),GC_661,AMP(32))
      CALL FFS2_1(W(1,5),W(1,3),GC_708,MDL_ME,ZERO,W(1,9))
C     Amplitude(s) for diagram number 33
      CALL FFS2_0(W(1,4),W(1,9),W(1,6),GC_661,AMP(33))
      CALL FFS2_1(W(1,5),W(1,3),GC_709,MDL_ME,ZERO,W(1,8))
C     Amplitude(s) for diagram number 34
      CALL FFS2_0(W(1,4),W(1,8),W(1,6),GC_661,AMP(34))
      CALL FFS2_1(W(1,5),W(1,3),GC_710,MDL_ME,ZERO,W(1,7))
C     Amplitude(s) for diagram number 35
      CALL FFS2_0(W(1,4),W(1,7),W(1,6),GC_661,AMP(35))
C     Amplitude(s) for diagram number 36
      CALL FFS2_0(W(1,4),W(1,13),W(1,14),GC_661,AMP(36))
C     Amplitude(s) for diagram number 37
      CALL FFS2_0(W(1,4),W(1,13),W(1,15),GC_661,AMP(37))
C     Amplitude(s) for diagram number 38
      CALL FFS2_0(W(1,4),W(1,13),W(1,16),GC_674,AMP(38))
C     Amplitude(s) for diagram number 39
      CALL FFS2_0(W(1,4),W(1,12),W(1,16),GC_674,AMP(39))
C     Amplitude(s) for diagram number 40
      CALL FFS2_0(W(1,4),W(1,11),W(1,16),GC_674,AMP(40))
C     Amplitude(s) for diagram number 41
      CALL FFS2_0(W(1,4),W(1,10),W(1,16),GC_674,AMP(41))
C     Amplitude(s) for diagram number 42
      CALL FFS2_0(W(1,4),W(1,9),W(1,16),GC_674,AMP(42))
C     Amplitude(s) for diagram number 43
      CALL FFS2_0(W(1,4),W(1,8),W(1,16),GC_674,AMP(43))
C     Amplitude(s) for diagram number 44
      CALL FFS2_0(W(1,4),W(1,7),W(1,16),GC_674,AMP(44))
      CALL FFS2_3(W(1,4),W(1,5),GC_661,MDL_MH,MDL_WH,W(1,7))
C     Amplitude(s) for diagram number 45
      CALL SSS2_0(W(1,6),W(1,3),W(1,7),GC_263,AMP(45))
C     Amplitude(s) for diagram number 46
      CALL SSS1_0(W(1,6),W(1,3),W(1,7),GC_260,AMP(46))
C     Amplitude(s) for diagram number 47
      CALL SSS3_0(W(1,6),W(1,3),W(1,7),GC_262,AMP(47))
C     Amplitude(s) for diagram number 48
      CALL SSS1_0(W(1,6),W(1,3),W(1,7),GC_434,AMP(48))
C     Amplitude(s) for diagram number 49
      CALL SSS1_0(W(1,6),W(1,3),W(1,7),GC_435,AMP(49))
C     Amplitude(s) for diagram number 50
      CALL SSS1_0(W(1,6),W(1,3),W(1,7),GC_436,AMP(50))
C     Amplitude(s) for diagram number 51
      CALL SSS1_0(W(1,6),W(1,3),W(1,7),GC_437,AMP(51))
C     Amplitude(s) for diagram number 52
      CALL SSS1_0(W(1,6),W(1,3),W(1,7),GC_438,AMP(52))
      CALL FFS1_3(W(1,4),W(1,5),GC_705,MDL_MH,MDL_WH,W(1,8))
C     Amplitude(s) for diagram number 53
      CALL SSS1_0(W(1,6),W(1,3),W(1,8),GC_260,AMP(53))
      CALL FFS2_3(W(1,4),W(1,5),GC_706,MDL_MH,MDL_WH,W(1,9))
C     Amplitude(s) for diagram number 54
      CALL SSS1_0(W(1,6),W(1,3),W(1,9),GC_260,AMP(54))
      CALL FFS2_3(W(1,4),W(1,5),GC_707,MDL_MH,MDL_WH,W(1,10))
C     Amplitude(s) for diagram number 55
      CALL SSS1_0(W(1,6),W(1,3),W(1,10),GC_260,AMP(55))
      CALL FFS2_3(W(1,4),W(1,5),GC_708,MDL_MH,MDL_WH,W(1,11))
C     Amplitude(s) for diagram number 56
      CALL SSS1_0(W(1,6),W(1,3),W(1,11),GC_260,AMP(56))
      CALL FFS2_3(W(1,4),W(1,5),GC_709,MDL_MH,MDL_WH,W(1,12))
C     Amplitude(s) for diagram number 57
      CALL SSS1_0(W(1,6),W(1,3),W(1,12),GC_260,AMP(57))
      CALL FFS2_3(W(1,4),W(1,5),GC_710,MDL_MH,MDL_WH,W(1,13))
C     Amplitude(s) for diagram number 58
      CALL SSS1_0(W(1,6),W(1,3),W(1,13),GC_260,AMP(58))
      CALL FFS2PH1_3(W(1,4),W(1,5),GC_674,MDL_MH1,MDL_WH1,W(1,17))
C     Amplitude(s) for diagram number 59
      CALL SSS1_0(W(1,6),W(1,3),W(1,17),GC_280,AMP(59))
C     Amplitude(s) for diagram number 60
      CALL SSS1_0(W(1,14),W(1,3),W(1,7),GC_260,AMP(60))
C     Amplitude(s) for diagram number 61
      CALL SSS1_0(W(1,14),W(1,3),W(1,17),GC_280,AMP(61))
C     Amplitude(s) for diagram number 62
      CALL SSS1_0(W(1,15),W(1,3),W(1,7),GC_260,AMP(62))
C     Amplitude(s) for diagram number 63
      CALL SSS1_0(W(1,15),W(1,3),W(1,17),GC_280,AMP(63))
C     Amplitude(s) for diagram number 64
      CALL SSS1_0(W(1,3),W(1,7),W(1,16),GC_280,AMP(64))
C     Amplitude(s) for diagram number 65
      CALL SSS1_0(W(1,3),W(1,8),W(1,16),GC_280,AMP(65))
C     Amplitude(s) for diagram number 66
      CALL SSS1_0(W(1,3),W(1,9),W(1,16),GC_280,AMP(66))
C     Amplitude(s) for diagram number 67
      CALL SSS1_0(W(1,3),W(1,10),W(1,16),GC_280,AMP(67))
C     Amplitude(s) for diagram number 68
      CALL SSS1_0(W(1,3),W(1,11),W(1,16),GC_280,AMP(68))
C     Amplitude(s) for diagram number 69
      CALL SSS1_0(W(1,3),W(1,12),W(1,16),GC_280,AMP(69))
C     Amplitude(s) for diagram number 70
      CALL SSS1_0(W(1,3),W(1,13),W(1,16),GC_280,AMP(70))
C     Amplitude(s) for diagram number 71
      CALL SSS1_0(W(1,3),W(1,16),W(1,17),GC_281,AMP(71))
C     Amplitude(s) for diagram number 72
      CALL FFSS2_0(W(1,4),W(1,5),W(1,3),W(1,6),GC_685,AMP(72))
C     Amplitude(s) for diagram number 73
      CALL FFSS1_0(W(1,4),W(1,5),W(1,3),W(1,6),GC_684,AMP(73))
      CALL VVS4_5_6_7P0_1(W(1,1),W(1,3),GC_224,GC_233,GC_237,GC_228
     $ ,ZERO,ZERO,W(1,6))
C     Amplitude(s) for diagram number 74
      CALL VVS4_5_6_7_0(W(1,6),W(1,2),W(1,7),GC_224,GC_233,GC_237
     $ ,GC_228,AMP(74))
C     Amplitude(s) for diagram number 75
      CALL VVS2_0(W(1,6),W(1,2),W(1,7),GC_265,AMP(75))
C     Amplitude(s) for diagram number 76
      CALL VVS4_0(W(1,6),W(1,2),W(1,7),GC_264,AMP(76))
C     Amplitude(s) for diagram number 77
      CALL VVS4_5_6_7_0(W(1,6),W(1,2),W(1,8),GC_224,GC_233,GC_237
     $ ,GC_228,AMP(77))
C     Amplitude(s) for diagram number 78
      CALL VVS4_5_6_7_0(W(1,6),W(1,2),W(1,9),GC_224,GC_233,GC_237
     $ ,GC_228,AMP(78))
C     Amplitude(s) for diagram number 79
      CALL VVS4_5_6_7_0(W(1,6),W(1,2),W(1,10),GC_224,GC_233,GC_237
     $ ,GC_228,AMP(79))
C     Amplitude(s) for diagram number 80
      CALL VVS4_5_6_7_0(W(1,6),W(1,2),W(1,11),GC_224,GC_233,GC_237
     $ ,GC_228,AMP(80))
C     Amplitude(s) for diagram number 81
      CALL VVS4_5_6_7_0(W(1,6),W(1,2),W(1,12),GC_224,GC_233,GC_237
     $ ,GC_228,AMP(81))
C     Amplitude(s) for diagram number 82
      CALL VVS4_5_6_7_0(W(1,6),W(1,2),W(1,13),GC_224,GC_233,GC_237
     $ ,GC_228,AMP(82))
C     Amplitude(s) for diagram number 83
      CALL VVS4_5_6_7_0(W(1,6),W(1,2),W(1,17),GC_242,GC_251,GC_255
     $ ,GC_246,AMP(83))
      CALL VVS2P0_1(W(1,1),W(1,3),GC_265,ZERO,ZERO,W(1,6))
C     Amplitude(s) for diagram number 84
      CALL VVS4_5_6_7_0(W(1,6),W(1,2),W(1,7),GC_224,GC_233,GC_237
     $ ,GC_228,AMP(84))
C     Amplitude(s) for diagram number 85
      CALL VVS4_5_6_7_0(W(1,6),W(1,2),W(1,17),GC_242,GC_251,GC_255
     $ ,GC_246,AMP(85))
      CALL VVS4P0_1(W(1,1),W(1,3),GC_264,ZERO,ZERO,W(1,6))
C     Amplitude(s) for diagram number 86
      CALL VVS4_5_6_7_0(W(1,6),W(1,2),W(1,7),GC_224,GC_233,GC_237
     $ ,GC_228,AMP(86))
C     Amplitude(s) for diagram number 87
      CALL VVS4_5_6_7_0(W(1,6),W(1,2),W(1,17),GC_242,GC_251,GC_255
     $ ,GC_246,AMP(87))
      CALL VVS4_5_6_7P0_1(W(1,2),W(1,3),GC_224,GC_233,GC_237,GC_228
     $ ,ZERO,ZERO,W(1,6))
C     Amplitude(s) for diagram number 88
      CALL VVS4_5_6_7_0(W(1,1),W(1,6),W(1,7),GC_224,GC_233,GC_237
     $ ,GC_228,AMP(88))
C     Amplitude(s) for diagram number 89
      CALL VVS2_0(W(1,1),W(1,6),W(1,7),GC_265,AMP(89))
C     Amplitude(s) for diagram number 90
      CALL VVS4_0(W(1,1),W(1,6),W(1,7),GC_264,AMP(90))
C     Amplitude(s) for diagram number 91
      CALL VVS4_5_6_7_0(W(1,1),W(1,6),W(1,8),GC_224,GC_233,GC_237
     $ ,GC_228,AMP(91))
C     Amplitude(s) for diagram number 92
      CALL VVS4_5_6_7_0(W(1,1),W(1,6),W(1,9),GC_224,GC_233,GC_237
     $ ,GC_228,AMP(92))
C     Amplitude(s) for diagram number 93
      CALL VVS4_5_6_7_0(W(1,1),W(1,6),W(1,10),GC_224,GC_233,GC_237
     $ ,GC_228,AMP(93))
C     Amplitude(s) for diagram number 94
      CALL VVS4_5_6_7_0(W(1,1),W(1,6),W(1,11),GC_224,GC_233,GC_237
     $ ,GC_228,AMP(94))
C     Amplitude(s) for diagram number 95
      CALL VVS4_5_6_7_0(W(1,1),W(1,6),W(1,12),GC_224,GC_233,GC_237
     $ ,GC_228,AMP(95))
C     Amplitude(s) for diagram number 96
      CALL VVS4_5_6_7_0(W(1,1),W(1,6),W(1,13),GC_224,GC_233,GC_237
     $ ,GC_228,AMP(96))
C     Amplitude(s) for diagram number 97
      CALL VVS4_5_6_7_0(W(1,1),W(1,6),W(1,17),GC_242,GC_251,GC_255
     $ ,GC_246,AMP(97))
      CALL VVS2P0_1(W(1,2),W(1,3),GC_265,ZERO,ZERO,W(1,6))
C     Amplitude(s) for diagram number 98
      CALL VVS4_5_6_7_0(W(1,1),W(1,6),W(1,7),GC_224,GC_233,GC_237
     $ ,GC_228,AMP(98))
C     Amplitude(s) for diagram number 99
      CALL VVS4_5_6_7_0(W(1,1),W(1,6),W(1,17),GC_242,GC_251,GC_255
     $ ,GC_246,AMP(99))
      CALL VVS4P0_1(W(1,2),W(1,3),GC_264,ZERO,ZERO,W(1,6))
C     Amplitude(s) for diagram number 100
      CALL VVS4_5_6_7_0(W(1,1),W(1,6),W(1,7),GC_224,GC_233,GC_237
     $ ,GC_228,AMP(100))
C     Amplitude(s) for diagram number 101
      CALL VVS4_5_6_7_0(W(1,1),W(1,6),W(1,17),GC_242,GC_251,GC_255
     $ ,GC_246,AMP(101))
      CALL VVSS4_3(W(1,1),W(1,2),W(1,3),GC_20,MDL_MH,MDL_WH,W(1,6))
C     Amplitude(s) for diagram number 102
      CALL FFS2_0(W(1,4),W(1,5),W(1,6),GC_661,AMP(102))
      CALL VVSS2_3(W(1,1),W(1,2),W(1,3),GC_21,MDL_MH,MDL_WH,W(1,6))
C     Amplitude(s) for diagram number 103
      CALL FFS2_0(W(1,4),W(1,5),W(1,6),GC_661,AMP(103))
      JAMP(1)=+2D0*(+AMP(1)+AMP(2)+AMP(3)+AMP(4)+AMP(5)+AMP(6)+AMP(7)
     $ +AMP(8)+AMP(9)+AMP(10)+AMP(11)+AMP(12)+AMP(13)+AMP(14)+AMP(15)
     $ +AMP(16)+AMP(17)+AMP(18)+AMP(19)+AMP(20)+AMP(21)+AMP(22)+AMP(23)
     $ +AMP(24)+AMP(25)+AMP(26)+AMP(27)+AMP(28)+AMP(29)+AMP(30)+AMP(31)
     $ +AMP(32)+AMP(33)+AMP(34)+AMP(35)+AMP(36)+AMP(37)+AMP(38)+AMP(39)
     $ +AMP(40)+AMP(41)+AMP(42)+AMP(43)+AMP(44)+AMP(45)+AMP(46)+AMP(47)
     $ +AMP(48)+AMP(49)+AMP(50)+AMP(51)+AMP(52)+AMP(53)+AMP(54)+AMP(55)
     $ +AMP(56)+AMP(57)+AMP(58)+AMP(59)+AMP(60)+AMP(61)+AMP(62)+AMP(63)
     $ +AMP(64)+AMP(65)+AMP(66)+AMP(67)+AMP(68)+AMP(69)+AMP(70)+AMP(71)
     $ +AMP(72)+AMP(73)+AMP(74)+AMP(75)+AMP(76)+AMP(77)+AMP(78)+AMP(79)
     $ +AMP(80)+AMP(81)+AMP(82)+AMP(83)+AMP(84)+AMP(85)+AMP(86)+AMP(87)
     $ +AMP(88)+AMP(89)+AMP(90)+AMP(91)+AMP(92)+AMP(93)+AMP(94)+AMP(95)
     $ +AMP(96)+AMP(97)+AMP(98)+AMP(99)+AMP(100)+AMP(101)+AMP(102)
     $ +AMP(103))

      M51_MATRIX = 0.D0
      DO I = 1, NCOLOR
        ZTEMP = (0.D0,0.D0)
        DO J = 1, NCOLOR
          ZTEMP = ZTEMP + CF(J,I)*JAMP(J)
        ENDDO
        M51_MATRIX = M51_MATRIX+ZTEMP*DCONJG(JAMP(I))/DENOM(I)
      ENDDO

      END

      SUBROUTINE M51_GET_VALUE(P, ALPHAS, NHEL ,ANS)
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=5)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
      INTEGER NHEL
      DOUBLE PRECISION ALPHAS
      REAL*8 PI
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: NHEL
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
CF2PY INTENT(IN) :: ALPHAS
C     ROUTINE FOR F2PY to read the benchmark point.    
C     the include file with the values of the parameters and masses 
      INCLUDE 'coupl.inc'

      PI = 3.141592653589793D0
      G = 2* DSQRT(ALPHAS*PI)
      CALL UPDATE_AS_PARAM()
      IF (NHEL.NE.0) THEN
        CALL M51_SMATRIXHEL(P, NHEL, ANS)
      ELSE
        CALL M51_SMATRIX(P, ANS)
      ENDIF
      RETURN
      END

      SUBROUTINE M51_INITIALISEMODEL(PATH)
C     ROUTINE FOR F2PY to read the benchmark point.    
      IMPLICIT NONE
      CHARACTER*512 PATH
CF2PY INTENT(IN) :: PATH
      CALL SETPARA(PATH)  !first call to setup the paramaters    
      RETURN
      END

      LOGICAL FUNCTION M51_IS_BORN_HEL_SELECTED(HELID)
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=5)
      INTEGER    NCOMB
      PARAMETER (NCOMB=16)
C     
C     ARGUMENTS
C     
      INTEGER HELID
C     
C     LOCALS
C     
      INTEGER I,J
      LOGICAL FOUNDIT
C     
C     GLOBALS
C     
      INTEGER HELC(NEXTERNAL,NCOMB)
      COMMON/M51_PROCESS_NHEL/HELC

      INTEGER POLARIZATIONS(0:NEXTERNAL,0:5)
      COMMON/M51_BORN_BEAM_POL/POLARIZATIONS
C     ----------
C     BEGIN CODE
C     ----------

      M51_IS_BORN_HEL_SELECTED = .TRUE.
      IF (POLARIZATIONS(0,0).EQ.-1) THEN
        RETURN
      ENDIF

      DO I=1,NEXTERNAL
        IF (POLARIZATIONS(I,0).EQ.-1) THEN
          CYCLE
        ENDIF
        FOUNDIT = .FALSE.
        DO J=1,POLARIZATIONS(I,0)
          IF (HELC(I,HELID).EQ.POLARIZATIONS(I,J)) THEN
            FOUNDIT = .TRUE.
            EXIT
          ENDIF
        ENDDO
        IF(.NOT.FOUNDIT) THEN
          M51_IS_BORN_HEL_SELECTED = .FALSE.
          RETURN
        ENDIF
      ENDDO

      RETURN
      END

